#!/usr/bin/env python3
"""
🦠 Condiciones Infecciosas - Base de Conocimiento Expandida
Basado en: ICD-10-CM 2026, IDSA Guidelines, WHO Guidelines, CDC Guidelines

Cobertura:
- Sepsis y Shock Séptico (A41/R65.21) ✓ nuevo
- Infección del Tracto Urinario (N39.0) ✓ nuevo
- Pielonefritis Aguda (N10) ✓ nuevo
- Celulitis y Absceso Cutáneo (L03/L02) ✓ nuevo
- Meningitis Bacteriana (G00) ✓ nuevo
- COVID-19 (U07.1) ✓ nuevo
- Influenza (J09-J11) ✓ nuevo
- Gastroenteritis Infecciosa (A09) ✓ nuevo
- Tuberculosis Pulmonar (A15) ✓ nuevo
"""

from dataclasses import dataclass


@dataclass
class MedicalCondition:
    """Condición médica completa"""

    icd10_code: str
    name: str
    category: str
    description: str
    symptoms: list
    risk_factors: list
    complications: list
    diagnostic_criteria: list
    differential_diagnosis: list
    treatment_protocol: list
    emergency_signs: list
    prognosis: str
    follow_up: list


INFECTIOUS_CONDITIONS = {
    # =========================================================================
    # SEPSIS Y SHOCK SÉPTICO (A41/R65.21)
    # Fuente: Surviving Sepsis Campaign 2021, Sepsis-3 Definition
    # =========================================================================
    "A41": MedicalCondition(
        icd10_code="A41",
        name="Sepsis y Shock Séptico",
        category="Infecciosas",
        description="Disfunción orgánica potencialmente mortal causada por una respuesta desregulada del huésped a la infección. El shock séptico es un subconjunto de sepsis con profundas anormalidades circulatorias, celulares y metabólicas",
        symptoms=[
            "SIGNOS DE INFECCIÓN:",
            "  - Fiebre (>38°C) o hipotermia (<36°C)",
            "  - Síntomas localizados según foco",
            "",
            "SIGNOS DE DISFUNCIÓN ORGÁNICA:",
            "  - Alteración del estado mental (confusión, desorientación)",
            "  - Taquipnea (FR >22/min)",
            "  - Hipotensión (PAS <100 mmHg)",
            "  - Taquicardia",
            "  - Oliguria (<0.5 mL/kg/h)",
            "  - Piel moteada, fría",
            "  - Llenado capilar prolongado (>3 seg)",
            "",
            "SHOCK SÉPTICO (adicionales):",
            "  - Hipotensión que requiere vasopresores para PAS ≥65 mmHg",
            "  - Lactato >2 mmol/L a pesar de resucitación hídrica",
        ],
        risk_factors=[
            "Edad extrema (<1 año, >65 años)",
            "Inmunosupresión (quimioterapia, esteroides, VIH)",
            "Diabetes mellitus",
            "Enfermedad renal crónica",
            "Cirrosis hepática",
            "Asplenia funcional o anatómica",
            "Cáncer activo",
            "Dispositivos invasivos (catéteres, sondas)",
            "Cirugía reciente",
            "Hospitalización prolongada",
            "Infección previa reciente",
            "Desnutrición",
        ],
        complications=[
            "Falla multiorgánica",
            "Síndrome de distrés respiratorio agudo (SDRA)",
            "Coagulación intravascular diseminada (CID)",
            "Insuficiencia renal aguda",
            "Isquemia intestinal",
            "Encefalopatía séptica",
            "Miocardiopatía séptica",
            "Polineuropatía/miopatía del paciente crítico",
            "Muerte (mortalidad 15-25% sepsis, 40-60% shock séptico)",
        ],
        diagnostic_criteria=[
            "DEFINICIÓN SEPSIS-3 (2016):",
            "  Sepsis = Infección sospechada/documentada + SOFA score ≥2 puntos",
            "",
            "CRITERIOS SOFA (Sequential Organ Failure Assessment):",
            "  - Respiratorio: PaO2/FiO2",
            "  - Coagulación: Plaquetas",
            "  - Hepático: Bilirrubina",
            "  - Cardiovascular: PAM y vasopresores",
            "  - Neurológico: Escala de Glasgow",
            "  - Renal: Creatinina y diuresis",
            "",
            "qSOFA (screening en urgencias, 2 de 3):",
            "  - Frecuencia respiratoria ≥22/min",
            "  - Alteración del estado mental",
            "  - Presión arterial sistólica ≤100 mmHg",
            "",
            "SHOCK SÉPTICO (Sepsis-3):",
            "  - Sepsis con:",
            "    • Necesidad de vasopresores para PAM ≥65 mmHg",
            "    • Lactato >2 mmol/L después de resucitación hídrica adecuada",
            "",
            "LABORATORIO:",
            "  - Hemocultivos (2 sets, antes de antibióticos si posible)",
            "  - Lactato sérico",
            "  - Hemograma, coagulación",
            "  - Función renal y hepática",
            "  - Procalcitonina",
            "  - Cultivos según foco sospechado",
        ],
        differential_diagnosis=[
            "SIRS no infeccioso (pancreatitis, quemados, trauma)",
            "Shock cardiogénico",
            "Shock hipovolémico",
            "Embolia pulmonar",
            "Insuficiencia suprarrenal aguda",
            "Reacción anafiláctica",
            "Intoxicación",
        ],
        treatment_protocol=[
            "BUNDLE DE LA HORA 1 (Surviving Sepsis 2021):",
            "",
            "1. MEDIR LACTATO:",
            "   - Re-medir si lactato inicial >2 mmol/L",
            "",
            "2. HEMOCULTIVOS antes de antibióticos:",
            "   - 2 sets de diferentes sitios",
            "   - No retrasar antibióticos si demora",
            "",
            "3. ANTIBIÓTICOS DE AMPLIO ESPECTRO:",
            "   - Dentro de 1 hora de reconocimiento",
            "   - Shock séptico: idealmente dentro de 30 minutos",
            "   - Cubrir patógenos probables según foco:",
            "     • Comunitario: Ceftriaxona 2g + (Vancomicina si MRSA)",
            "     • Nosocomial: Meropenem o Piperacilina-Tazobactam + Vancomicina",
            "     • Intraabdominal: agregar cobertura anaeróbica",
            "",
            "4. RESUCITACIÓN HÍDRICA:",
            "   - Cristaloides 30 mL/kg en primeras 3 horas si hipotensión o lactato >4",
            "   - Ringer lactato preferido sobre salino",
            "   - Reevaluar estado hídrico frecuentemente",
            "",
            "5. VASOPRESORES si hipotensión persiste post-fluidos:",
            "   - Norepinefrina primera línea (meta PAM ≥65 mmHg)",
            "   - Agregar Vasopresina si dosis alta de norepinefrina",
            "   - Considerar Dobutamina si disfunción miocárdica",
            "",
            "MANEJO ADICIONAL:",
            "   - Control de foco (drenaje de abscesos, retiro de dispositivos)",
            "   - Corticoides (Hidrocortisona 200mg/día) si shock refractario",
            "   - Hemoderivados conservadores (Hb <7 g/dL para transfundir)",
            "   - Profilaxis TVP y úlcera de estrés",
            "   - Control glucémico (140-180 mg/dL)",
        ],
        emergency_signs=[
            "TODO paciente con sepsis es emergencia médica",
            "Shock séptico: hipotensión refractaria a fluidos",
            "Lactato >4 mmol/L",
            "Alteración profunda del estado mental",
            "Insuficiencia respiratoria (SatO2 <90%)",
            "Oligoanuria",
            "Signos de CID (sangrado)",
            "Acidosis metabólica severa",
        ],
        prognosis="Mortalidad sepsis: 15-25%. Shock séptico: 40-60%. Cada hora de retraso en antibióticos aumenta mortalidad 7.6%.",
        follow_up=[
            "UCI hasta estabilización",
            "Desescalar antibióticos según cultivos (7-10 días típico)",
            "Evaluación de secuelas post-sepsis",
            "Rehabilitación funcional",
            "Seguimiento a las 4-6 semanas post-alta",
            "Screening de PTSD, depresión, deterioro cognitivo",
        ],
    ),
    # =========================================================================
    # INFECCIÓN DEL TRACTO URINARIO (N39.0)
    # Fuente: IDSA Guidelines UTI 2024, EAU Guidelines
    # =========================================================================
    "N39.0": MedicalCondition(
        icd10_code="N39.0",
        name="Infección del Tracto Urinario",
        category="Infecciosas",
        description="Infección bacteriana de las vías urinarias, clasificada como cistitis (ITU baja) o pielonefritis (ITU alta). La ITU no complicada afecta a mujeres sanas no embarazadas",
        symptoms=[
            "CISTITIS (ITU BAJA):",
            "  - Disuria (dolor/ardor al orinar)",
            "  - Polaquiuria (frecuencia aumentada)",
            "  - Urgencia miccional",
            "  - Dolor suprapúbico",
            "  - Hematuria (especialmente al final de micción)",
            "  - Orina turbia o maloliente",
            "  - Sin fiebre típicamente",
            "",
            "PIELONEFRITIS (ITU ALTA):",
            "  - Fiebre con escalofríos",
            "  - Dolor lumbar unilateral (puño-percusión positiva)",
            "  - Náuseas y vómitos",
            "  - Síntomas de cistitis asociados",
            "  - Malestar general",
        ],
        risk_factors=[
            "Sexo femenino (anatomía)",
            "Actividad sexual reciente",
            "Uso de espermicidas/diafragma",
            "Menopausia (atrofia)",
            "Historia de ITU previa",
            "Diabetes mellitus",
            "Embarazo",
            "Catéter urinario",
            "Anomalías urológicas estructurales",
            "Obstrucción urinaria (litiasis, HPB)",
            "Inmunosupresión",
            "Hospitalización reciente",
        ],
        complications=[
            "Pielonefritis (de cistitis no tratada)",
            "Absceso renal",
            "Pionefrosis",
            "Urosepsis",
            "Parto prematuro (embarazadas)",
            "Daño renal crónico (pielonefritis recurrente)",
        ],
        diagnostic_criteria=[
            "CISTITIS NO COMPLICADA:",
            "  - Diagnóstico clínico (síntomas típicos en mujer joven sana)",
            "  - No requiere urocultivo de rutina",
            "",
            "SOLICITAR UROCULTIVO SI:",
            "  - ITU complicada",
            "  - Pielonefritis",
            "  - Embarazo",
            "  - Síntomas atípicos o recurrencia",
            "  - Falta de respuesta a tratamiento",
            "  - Hombres",
            "",
            "UROANÁLISIS (tira reactiva):",
            "  - Nitritos positivos (bacterias gramnegativas)",
            "  - Esterasa leucocitaria positiva",
            "  - Leucocituria (>10 leucocitos/campo)",
            "  - Bacteriuria",
            "",
            "CRITERIOS DE UROCULTIVO POSITIVO:",
            "  - ≥10³ UFC/mL en mujer sintomática con disuria",
            "  - ≥10⁵ UFC/mL tradicionalmente",
            "",
            "ITU COMPLICADA (cualquiera de):",
            "  - Hombres",
            "  - Embarazadas",
            "  - Anomalía anatómica/funcional",
            "  - Catéter urinario",
            "  - Inmunosupresión",
            "  - Diabetes mellitus",
            "  - Pielonefritis",
            "  - Infección recurrente",
            "  - Patógeno resistente",
        ],
        differential_diagnosis=[
            "Uretritis (Chlamydia, gonorrea)",
            "Vaginitis",
            "Vulvovaginitis atrófica",
            "Síndrome uretral agudo",
            "Cistitis intersticial",
            "Prostatitis (hombres)",
            "Litiasis renal",
            "Tumor vesical",
        ],
        treatment_protocol=[
            "CISTITIS NO COMPLICADA (mujeres):",
            "  - Primera línea:",
            "    • Nitrofurantoína 100mg c/12h x 5 días (preferido)",
            "    • Fosfomicina 3g dosis única",
            "    • Trimetoprim-Sulfametoxazol 160/800mg c/12h x 3 días",
            "      (si resistencia local <20%)",
            "  - Segunda línea:",
            "    • Fluoroquinolonas (reservar para otras indicaciones)",
            "",
            "CISTITIS EN EMBARAZO:",
            "  - Nitrofurantoína (no en tercer trimestre)",
            "  - Cefalexina 500mg c/8h x 7 días",
            "  - Tratar bacteriuria asintomática",
            "",
            "CISTITIS EN HOMBRES:",
            "  - Siempre urocultivo",
            "  - TMP-SMX o fluoroquinolona x 7 días",
            "  - Evaluar próstata, descartar prostatitis",
            "",
            "ITU RECURRENTE (≥3/año o ≥2/6 meses):",
            "  - Profilaxis post-coital (Nitrofurantoína 50-100mg)",
            "  - Profilaxis continua a dosis baja",
            "  - Estrógenos vaginales en postmenopáusicas",
            "  - D-manosa, arándanos (evidencia limitada)",
            "  - Referir urología para estudio",
        ],
        emergency_signs=[
            "Signos de pielonefritis o urosepsis",
            "Fiebre alta con escalofríos",
            "Dolor lumbar severo",
            "Vómitos persistentes",
            "Signos de sepsis",
            "Retención urinaria aguda",
            "ITU en embarazada con fiebre",
        ],
        prognosis="Excelente con tratamiento adecuado. Cistitis: resolución en 1-3 días. Pielonefritis: mejoría en 48-72h.",
        follow_up=[
            "Cistitis no complicada: no requiere seguimiento si resolución",
            "ITU en embarazo: urocultivo de control post-tratamiento",
            "ITU recurrente: referir urología",
            "Pielonefritis: control en 48-72h",
            "Educación: hidratación, vaciamiento post-coital",
        ],
    ),
    # =========================================================================
    # PIELONEFRITIS AGUDA (N10)
    # Fuente: IDSA Guidelines 2022, EAU Guidelines
    # =========================================================================
    "N10": MedicalCondition(
        icd10_code="N10",
        name="Pielonefritis Aguda",
        category="Infecciosas",
        description="Infección bacteriana aguda del parénquima renal y sistema pielocalicial. Generalmente ascendente desde vía urinaria baja. Entidades causales más frecuentes: E. coli (80-90%)",
        symptoms=[
            "TRÍADA CLÁSICA:",
            "  - Fiebre (>38°C, con escalofríos)",
            "  - Dolor lumbar unilateral",
            "  - Náuseas/vómitos",
            "",
            "SÍNTOMAS ADICIONALES:",
            "  - Síntomas de cistitis (50-70%)",
            "  - Malestar general",
            "  - Anorexia",
            "  - Puño-percusión lumbar positiva",
            "  - Dolor en ángulo costovertebral",
            "  - Taquicardia",
            "",
            "FORMAS ATÍPICAS:",
            "  - Ancianos: confusión, deterioro funcional sin fiebre",
            "  - Diabéticos: presentación más insidiosa",
        ],
        risk_factors=[
            "Sexo femenino",
            "ITU baja no tratada",
            "Actividad sexual",
            "Embarazo",
            "Obstrucción urinaria (cálculos, HPB)",
            "Reflujo vesicoureteral",
            "Cateterización urinaria",
            "Diabetes mellitus",
            "Inmunosupresión",
            "Instrumentación urológica reciente",
            "Anomalías anatómicas",
        ],
        complications=[
            "Absceso renal/perinéfrico",
            "Pionefrosis (pus + obstrucción)",
            "Pielonefritis enfisematosa (gas, diabéticos)",
            "Necrosis papilar renal",
            "Urosepsis/shock séptico",
            "Insuficiencia renal aguda",
            "Parto prematuro (embarazadas)",
            "Pielonefritis crónica (cicatrices)",
        ],
        diagnostic_criteria=[
            "CLÍNICA + LABORATORIO:",
            "  - Fiebre + dolor lumbar + piuria",
            "",
            "UROANÁLISIS:",
            "  - Piuria (>10 leucocitos/campo)",
            "  - Bacteriuria",
            "  - Cilindros leucocitarios (específico de pielonefritis)",
            "  - Nitritos/esterasa leucocitaria positivos",
            "",
            "UROCULTIVO:",
            "  - Siempre antes de iniciar antibióticos",
            "  - Positivo: ≥10⁴ UFC/mL con clínica compatible",
            "",
            "HEMOCULTIVOS:",
            "  - Si fiebre alta, sepsis, o paciente que ingresa",
            "  - Positivos en 20-30%",
            "",
            "LABORATORIO GENERAL:",
            "  - Leucocitosis con desviación izquierda",
            "  - PCR/procalcitonina elevadas",
            "  - Función renal (puede estar alterada)",
            "",
            "IMAGEN (no siempre necesaria):",
            "  - TAC con contraste: Gold standard si:",
            "    • No mejoría en 48-72h",
            "    • Sospecha de complicación (absceso, obstrucción)",
            "    • Diabetes (pielonefritis enfisematosa)",
            "    • Hombres",
            "  - Ecografía: descartar obstrucción/hidronefrosis",
        ],
        differential_diagnosis=[
            "Cólico renal (litiasis)",
            "Apendicitis (derecha)",
            "Colecistitis aguda (derecha alta)",
            "Neumonía basal",
            "Dolor musculoesquelético",
            "Pancreatitis",
            "Enfermedad inflamatoria pélvica",
        ],
        treatment_protocol=[
            "PIELONEFRITIS NO COMPLICADA - AMBULATORIA:",
            "  Criterios: buen estado general, tolerancia oral, sin sepsis",
            "  - Ciprofloxacino 500mg c/12h x 7 días, o",
            "  - Levofloxacino 750mg/día x 5 días, o",
            "  - TMP-SMX 160/800mg c/12h x 14 días (si sensible)",
            "  - Ceftriaxona 1g IM dosis única + oral",
            "",
            "PIELONEFRITIS CON NECESIDAD DE HOSPITALIZACIÓN:",
            "  Indicaciones: vómitos, sepsis, comorbilidades, embarazo, obstrucción",
            "  - Ceftriaxona 1-2g IV/día, o",
            "  - Ciprofloxacino 400mg IV c/12h, o",
            "  - Piperacilina-Tazobactam 4.5g IV c/6h (si complicada)",
            "  - Duración: IV hasta mejoría, luego oral (total 7-14 días)",
            "",
            "PIELONEFRITIS EN EMBARAZO:",
            "  - Siempre hospitalizar inicialmente",
            "  - Ceftriaxona 1-2g IV/día, o Ampicilina + Gentamicina",
            "  - Profilaxis post-tratamiento hasta parto",
            "",
            "COMPLICACIONES (absceso, pionefrosis, enfisematosa):",
            "  - Antibióticos IV de amplio espectro",
            "  - Drenaje percutáneo o quirúrgico",
            "  - Nefrostomía si obstrucción",
        ],
        emergency_signs=[
            "Signos de sepsis/shock séptico",
            "Fiebre persistente >72h con antibióticos",
            "Dolor severo incontrolable",
            "Vómitos persistentes (no tolera oral)",
            "Oligoanuria",
            "Masa abdominal palpable (absceso)",
            "Gas en parénquima renal (enfisematosa)",
            "Pielonefritis en embarazada",
        ],
        prognosis="Excelente con tratamiento temprano y apropiado. Mejoría esperada en 48-72h. Mayor morbilidad en diabéticos, obstrucción, abscesos.",
        follow_up=[
            "Control clínico a las 48-72h",
            "Urocultivo de control: no necesario si respuesta clínica",
            "Imagen de control si complicaciones",
            "Evaluar anomalías urológicas si primer episodio en hombre o mujer con recurrencia",
            "Profilaxis en embarazadas hasta parto",
        ],
    ),
    # =========================================================================
    # CELULITIS (L03)
    # Fuente: IDSA Guidelines SSTI 2014, Cochrane Reviews
    # =========================================================================
    "L03": MedicalCondition(
        icd10_code="L03",
        name="Celulitis y Erisipela",
        category="Infecciosas",
        description="Infección bacteriana aguda de la piel y tejido celular subcutáneo (celulitis) o de la dermis superficial y linfáticos (erisipela). Causas principales: Streptococcus pyogenes y Staphylococcus aureus",
        symptoms=[
            "CELULITIS:",
            "  - Eritema difuso, sin bordes definidos",
            "  - Edema",
            "  - Calor local",
            "  - Dolor a la palpación",
            "  - Fiebre y malestar general",
            "  - Linfadenopatía regional",
            "  - Linfangitis (líneas rojas ascendentes)",
            "",
            "ERISIPELA:",
            "  - Eritema intenso con bordes elevados, bien definidos",
            "  - Superficie 'piel de naranja'",
            "  - Más superficial",
            "  - Más común en cara y miembros inferiores",
            "  - Fiebre alta con escalofríos",
            "",
            "LOCALIZACIONES FRECUENTES:",
            "  - Miembros inferiores (más común)",
            "  - Cara (erisipela)",
            "  - Miembros superiores",
            "  - Sitio quirúrgico/trauma",
        ],
        risk_factors=[
            "Puerta de entrada (trauma, úlcera, intertrigo, pie de atleta)",
            "Linfedema",
            "Insuficiencia venosa crónica",
            "Edema de cualquier causa",
            "Obesidad",
            "Diabetes mellitus",
            "Celulitis previa (recurrencia)",
            "Inmunosupresión",
            "Uso de drogas IV",
            "Safenectomía/linfadenectomía",
        ],
        complications=[
            "Absceso",
            "Fascitis necrotizante",
            "Bacteriemia/sepsis",
            "Osteomielitis (contigüidad)",
            "Trombosis venosa profunda",
            "Síndrome compartimental",
            "Glomerulonefritis post-estreptocócica",
            "Celulitis recurrente",
        ],
        diagnostic_criteria=[
            "DIAGNÓSTICO CLÍNICO:",
            "  - Eritema + edema + calor + dolor en área afectada",
            "  - Fiebre (presente en ~50%)",
            "  - No requiere cultivos de rutina",
            "",
            "CUÁNDO REALIZAR ESTUDIOS:",
            "  - Hemocultivos: si fiebre alta, inmunosupresión, signos sistémicos",
            "    (positivos solo en 2-4%)",
            "  - Cultivo de herida/absceso: si purulento",
            "  - Laboratorio: leucocitosis, PCR elevada",
            "",
            "IMAGEN (si sospecha de complicaciones):",
            "  - Ecografía: descartar absceso (indicación más común)",
            "  - RM: fascitis necrotizante, osteomielitis",
            "  - TAC: infección profunda",
            "",
            "DIFERENCIAR DE FASCITIS NECROTIZANTE:",
            "  - Dolor desproporcionado a hallazgos",
            "  - Toxicidad sistémica severa",
            "  - Crepitación",
            "  - Bullas hemorrágicas",
            "  - Necrosis cutánea",
            "  - Rápida progresión",
            "  - Falla de respuesta a antibióticos",
        ],
        differential_diagnosis=[
            "Trombosis venosa profunda",
            "Dermatitis de estasis",
            "Dermatitis de contacto",
            "Erisipeloide",
            "Gota aguda",
            "Artritis séptica",
            "Fascitis necrotizante",
            "Lipodermatoesclerosis",
            "Hematoma",
            "Picadura de insecto",
            "Síndrome de Wells",
        ],
        treatment_protocol=[
            "CELULITIS NO PURULENTA (sin absceso):",
            "  - Tratamiento empírico anti-estreptococo/estafilococo:",
            "    • Amoxicilina-Clavulánico 875/125mg c/12h x 5-10 días",
            "    • Cefalexina 500mg c/6h x 5-10 días",
            "    • Clindamicina 300-450mg c/8h (si alergia a penicilina)",
            "  - Duración: 5 días, extender si no mejoría",
            "",
            "CELULITIS PURULENTA (absceso):",
            "  - Incisión y drenaje (esencial)",
            "  - Antibióticos si: celulitis circundante extensa, signos sistémicos, inmunosupresión",
            "  - Cubrir MRSA si sospecha:",
            "    • TMP-SMX 1-2 tabletas DS c/12h, o",
            "    • Doxiciclina 100mg c/12h, o",
            "    • Clindamicina 300-450mg c/8h",
            "",
            "CELULITIS MODERADA-SEVERA (hospitalizar):",
            "  - Ceftriaxona 1-2g IV/día + Vancomicina 15-20mg/kg IV c/12h",
            "    (o Clindamicina IV)",
            "  - Cambiar a oral cuando mejoría y afebril 24-48h",
            "",
            "MEDIDAS ADICIONALES:",
            "  - Elevación del miembro afectado",
            "  - Analgesia",
            "  - Tratar puerta de entrada (intertrigo, pie de atleta)",
            "  - Manejo del edema/linfedema",
            "  - Delimitar eritema con marcador",
            "",
            "PROFILAXIS SECUNDARIA (recurrencia ≥3-4/año):",
            "  - Penicilina V 250mg c/12h o Penicilina benzatínica IM mensual",
        ],
        emergency_signs=[
            "Sospecha de FASCITIS NECROTIZANTE:",
            "  - Dolor severo desproporcionado",
            "  - Crepitación",
            "  - Necrosis/bullas hemorrágicas",
            "  - Toxicidad sistémica severa",
            "  - Rápida extensión (>1cm/h)",
            "Sepsis o shock",
            "Celulitis facial/periorbitaria (riesgo de trombosis seno cavernoso)",
            "Inmunosupresión severa",
            "Mordeduras con infección (animales, humanos)",
        ],
        prognosis="Excelente con tratamiento apropiado. Mejoría esperada en 24-48h. Eritema puede tardar más en resolver. Recurrencia común si factores de riesgo persisten.",
        follow_up=[
            "Control a las 48-72h para evaluar respuesta",
            "Reconsultar si empeoramiento o no mejoría en 48h",
            "Tratar factores predisponentes (intertrigo, linfedema)",
            "Educación sobre cuidado de heridas y piel",
            "Considerar profilaxis si recurrente",
        ],
    ),
    # =========================================================================
    # MENINGITIS BACTERIANA (G00)
    # Fuente: IDSA Guidelines Meningitis 2017, Cochrane Reviews
    # =========================================================================
    "G00": MedicalCondition(
        icd10_code="G00",
        name="Meningitis Bacteriana",
        category="Infecciosas",
        description="Infección bacteriana de las meninges (leptomeninges), emergencia médica con alta morbimortalidad. Agentes más frecuentes varían según edad: S. pneumoniae y N. meningitidis en adultos",
        symptoms=[
            "TRÍADA CLÁSICA (presente en <50%):",
            "  - Fiebre",
            "  - Cefalea intensa",
            "  - Rigidez de nuca",
            "",
            "SÍNTOMAS NEUROLÓGICOS:",
            "  - Alteración del nivel de conciencia",
            "  - Confusión, desorientación",
            "  - Fotofobia",
            "  - Convulsiones (20-30%)",
            "  - Déficits neurológicos focales (15%)",
            "",
            "SIGNOS MENÍNGEOS:",
            "  - Rigidez de nuca",
            "  - Signo de Kernig (resistencia a extensión de rodilla con cadera flexionada)",
            "  - Signo de Brudzinski (flexión de caderas al flexionar cuello)",
            "  - Posición en gatillo (opistotonos)",
            "",
            "OTROS:",
            "  - Náuseas y vómitos",
            "  - Petequias/púrpura (meningococo)",
            "  - Irritabilidad, llanto agudo (lactantes)",
            "  - Fontanela abombada (lactantes)",
        ],
        risk_factors=[
            "Edad extrema (<5 años, >65 años)",
            "Esplenectomía/asplenia funcional",
            "Inmunosupresión (VIH, quimioterapia)",
            "Déficit de complemento",
            "Hipogammaglobulinemia",
            "Fístula de LCR (post-trauma, congénita)",
            "Neurocirugía reciente",
            "Dispositivos de LCR (válvula VP)",
            "Otitis media/sinusitis/mastoiditis",
            "Endocarditis",
            "Hacinamiento (meningococo)",
            "Alcoholismo, cirrosis",
        ],
        complications=[
            "Edema cerebral e hipertensión intracraneal",
            "Herniación cerebral",
            "Hidrocefalia",
            "Vasculitis/trombosis de senos venosos",
            "Infarto cerebral",
            "Absceso cerebral",
            "Empiema subdural",
            "Pérdida auditiva (10-30%)",
            "Déficits neurológicos permanentes",
            "CID (meningococo)",
            "Síndrome de Waterhouse-Friderichsen",
            "Muerte (15-25% con tratamiento)",
        ],
        diagnostic_criteria=[
            "PUNCIÓN LUMBAR (diagnóstico definitivo):",
            "  Hallazgos típicos de LCR en meningitis bacteriana:",
            "  - Aspecto turbio",
            "  - Pleocitosis: >1000 células/mm³ (predominio neutrófilos >80%)",
            "  - Proteínas: >100-500 mg/dL",
            "  - Glucosa: <40 mg/dL o relación glucosa LCR/sangre <0.4",
            "  - Gram: positivo en 60-90%",
            "  - Cultivo: positivo en 80-90% (si no antibióticos previos)",
            "",
            "OTROS ESTUDIOS EN LCR:",
            "  - Antígenos bacterianos (neumococo, meningococo)",
            "  - PCR bacteriana (si cultivo negativo)",
            "  - Lactato LCR >3.5 mmol/L (sensible)",
            "  - Procalcitonina LCR",
            "",
            "HEMOCULTIVOS:",
            "  - Obtener antes de antibióticos (positivos 50-80%)",
            "",
            "IMAGEN (TAC/RM):",
            "  - Antes de PL si: inmunodeprimido, historia de lesión SNC, convulsiones recientes, papiledema, déficit focal, Glasgow <10",
            "  - NO retrasar antibióticos por imagen",
            "",
            "CONTRAINDICACIONES PL:",
            "  - Signos de HTE o herniación",
            "  - Inestabilidad hemodinámica",
            "  - Infección en sitio de punción",
            "  - Coagulopatía severa",
        ],
        differential_diagnosis=[
            "Meningitis viral (LCR diferente)",
            "Meningitis tuberculosa",
            "Meningitis fúngica",
            "Encefalitis",
            "Absceso cerebral",
            "Hemorragia subaracnoidea",
            "Migraña complicada",
            "Trombosis seno venoso cerebral",
            "Meningitis carcinomatosa",
        ],
        treatment_protocol=[
            "PRINCIPIO: Antibióticos empíricos inmediatos, NO esperar imagen/PL",
            "",
            "TRATAMIENTO EMPÍRICO (antes de cultivos):",
            "  Adultos (18-50 años):",
            "    - Ceftriaxona 2g IV c/12h + Vancomicina 15-20mg/kg IV c/12h",
            "  Adultos >50 años o inmunocomprometidos:",
            "    - Agregar Ampicilina 2g IV c/4h (cubrir Listeria)",
            "  Post-neurocirugía o trauma craneal:",
            "    - Cefepima o Meropenem + Vancomicina",
            "",
            "DEXAMETASONA ADYUVANTE:",
            "  - Dexametasona 0.15 mg/kg IV c/6h x 4 días",
            "  - Dar 15-20 min ANTES o CON primera dosis de antibiótico",
            "  - Beneficio demostrado en neumococo (reduce mortalidad/secuelas)",
            "  - Menor evidencia en otros patógenos",
            "",
            "DURACIÓN SEGÚN PATÓGENO:",
            "  - N. meningitidis: 7 días",
            "  - H. influenzae: 7 días",
            "  - S. pneumoniae: 10-14 días",
            "  - L. monocytogenes: 21 días",
            "  - Bacilos gramnegativos: 21 días",
            "",
            "PROFILAXIS DE CONTACTOS:",
            "  - Meningococo: Rifampicina, Ciprofloxacino, o Ceftriaxona",
            "  - H. influenzae tipo b: Rifampicina (si contacto susceptible)",
            "  - Contactos cercanos: convivientes, exposición a secreciones",
        ],
        emergency_signs=[
            "TODA meningitis bacteriana es EMERGENCIA",
            "Deterioro del nivel de conciencia",
            "Convulsiones",
            "Signos de herniación (anisocoria, postura de decorticación/descerebración)",
            "Púrpura fulminante (meningococo)",
            "Shock",
            "Parálisis de pares craneales",
            "Status epiléptico",
        ],
        prognosis="Mortalidad 15-25% con tratamiento. Secuelas neurológicas en 20-30% de sobrevivientes. Peor pronóstico: neumococo, coma al ingreso, convulsiones, edad extrema.",
        follow_up=[
            "UCI durante fase aguda",
            "Audiometría post-tratamiento (todos los pacientes)",
            "Evaluación neurológica y cognitiva",
            "Control de infección primaria (sinusitis, otitis)",
            "Evaluación de inmunodeficiencia si recurrente",
            "Vacunación post-recuperación (neumococo, meningococo)",
            "Rehabilitación si secuelas",
        ],
    ),
    # =========================================================================
    # COVID-19 (U07.1)
    # Fuente: WHO Guidelines 2023, NIH COVID-19 Treatment Guidelines
    # =========================================================================
    "U07.1": MedicalCondition(
        icd10_code="U07.1",
        name="COVID-19",
        category="Infecciosas",
        description="Enfermedad causada por el coronavirus SARS-CoV-2, con espectro que va desde asintomático hasta neumonía severa, SDRA y falla multiorgánica",
        symptoms=[
            "SÍNTOMAS COMUNES:",
            "  - Fiebre o febrícula",
            "  - Tos seca",
            "  - Fatiga",
            "  - Mialgias y artralgias",
            "  - Cefalea",
            "  - Odinofagia",
            "  - Congestión nasal/rinorrea",
            "",
            "SÍNTOMAS CARACTERÍSTICOS:",
            "  - Anosmia/hiposmia (pérdida del olfato)",
            "  - Ageusia/disgeusia (pérdida del gusto)",
            "",
            "SÍNTOMAS GASTROINTESTINALES:",
            "  - Diarrea",
            "  - Náuseas y vómitos",
            "  - Dolor abdominal",
            "",
            "SÍNTOMAS DE SEVERIDAD:",
            "  - Disnea",
            "  - Dolor torácico",
            "  - Confusión",
            "  - Cianosis",
        ],
        risk_factors=[
            "Edad ≥65 años",
            "Enfermedad cardiovascular",
            "Diabetes mellitus",
            "Obesidad (IMC ≥30)",
            "EPOC y enfermedad pulmonar crónica",
            "Enfermedad renal crónica",
            "Inmunosupresión (trasplante, quimioterapia, VIH mal controlado)",
            "Cáncer activo",
            "Embarazo",
            "Tabaquismo",
            "No vacunación",
            "Síndrome de Down",
        ],
        complications=[
            "Neumonía bilateral",
            "Síndrome de distrés respiratorio agudo (SDRA)",
            "Tormenta de citocinas",
            "Eventos tromboembólicos (TEP, TVP, ACV)",
            "Síndrome inflamatorio multisistémico (MIS-C en niños)",
            "Miocarditis",
            "Arritmias",
            "Lesión renal aguda",
            "COVID prolongado (Long COVID)",
            "Superinfección bacteriana/fúngica",
            "Muerte",
        ],
        diagnostic_criteria=[
            "PRUEBAS DIAGNÓSTICAS:",
            "  - RT-PCR (hisopado nasofaríngeo): Gold standard, alta S y E",
            "  - Test de antígeno rápido: menor sensibilidad, útil en sintomáticos",
            "  - PCR en saliva (alternativa)",
            "",
            "CLASIFICACIÓN DE SEVERIDAD (NIH):",
            "  - Asintomático: sin síntomas",
            "  - Leve: síntomas sin disnea ni imagen anormal",
            "  - Moderado: evidencia de enfermedad respiratoria baja (clínica o imagen), SatO2 ≥94%",
            "  - Severo: SatO2 <94%, PaO2/FiO2 <300, FR>30, infiltrados >50%",
            "  - Crítico: insuficiencia respiratoria, shock, falla multiorgánica",
            "",
            "LABORATORIO:",
            "  - Linfopenia (común)",
            "  - Elevación de PCR, ferritina, LDH, dímero D",
            "  - Troponinas, BNP si afectación cardíaca",
            "  - IL-6 (tormenta de citocinas)",
            "",
            "IMAGEN:",
            "  - TAC tórax: vidrio esmerilado bilateral, consolidaciones periféricas",
            "  - Rx tórax: opacidades bilaterales (menos sensible)",
        ],
        differential_diagnosis=[
            "Influenza",
            "Otras neumonías virales",
            "Neumonía bacteriana",
            "Neumonía por Pneumocystis (VIH)",
            "Exacerbación de EPOC/asma",
            "Insuficiencia cardíaca",
            "Embolia pulmonar",
        ],
        treatment_protocol=[
            "COVID-19 LEVE/MODERADO - AMBULATORIO:",
            "  - Tratamiento sintomático (paracetamol, hidratación)",
            "  - Antivirales en pacientes de alto riesgo (primeros 5-7 días):",
            "    • Paxlovid (nirmatrelvir-ritonavir) - preferido",
            "    • Remdesivir IV 3 días (si disponible ambulatorio)",
            "    • Molnupiravir (alternativa)",
            "  - Monitoreo de saturación (pulsioxímetro)",
            "",
            "COVID-19 MODERADO - HOSPITALIZADO:",
            "  - Oxígeno suplementario (meta SatO2 92-96%)",
            "  - Remdesivir 5 días",
            "  - Dexametasona 6mg/día x 10 días (si requiere O2)",
            "  - Anticoagulación profiláctica (HBPM)",
            "",
            "COVID-19 SEVERO/CRÍTICO:",
            "  - UCI, soporte respiratorio (CNAF, VNI, VMI)",
            "  - Dexametasona 6mg IV/día (o equivalente)",
            "  - Remdesivir (si <10 días síntomas)",
            "  - Considerar: Tocilizumab o Baricitinib si hipoxia progresiva + marcadores inflamatorios elevados",
            "  - Anticoagulación (dosis según protocolo institucional)",
            "  - Pronación si SDRA",
            "",
            "NO RECOMENDADOS (sin beneficio demostrado):",
            "  - Hidroxicloroquina",
            "  - Ivermectina",
            "  - Azitromicina (sin infección bacteriana)",
        ],
        emergency_signs=[
            "Disnea significativa o dificultad para respirar",
            "SatO2 <94% (o <90% si basal bajo)",
            "Dolor o presión torácica persistente",
            "Confusión de nueva aparición",
            "Incapacidad para mantenerse despierto",
            "Cianosis (labios, cara)",
            "Signos de shock",
        ],
        prognosis="La mayoría se recupera. Mortalidad global ~0.5-1% (mayor en no vacunados, ancianos, comorbilidades). Long COVID en 10-30%.",
        follow_up=[
            "Aislamiento según guías locales (5-10 días)",
            "Monitoreo de SatO2 si factores de riesgo",
            "Evaluación post-COVID si síntomas persistentes >4 semanas",
            "Rehabilitación pulmonar si enfermedad severa",
            "Vacunación (dosis posteriores) tras recuperación",
        ],
    ),
    # =========================================================================
    # GASTROENTERITIS INFECCIOSA (A09)
    # Fuente: IDSA Guidelines 2017, ACG Guidelines
    # =========================================================================
    "A09": MedicalCondition(
        icd10_code="A09",
        name="Gastroenteritis Infecciosa Aguda",
        category="Infecciosas",
        description="Inflamación de la mucosa gastrointestinal causada por agentes infecciosos (virus, bacterias, parásitos), caracterizada por diarrea aguda con o sin vómitos",
        symptoms=[
            "DIARREA (síntoma cardinal):",
            "  - Acuosa (viral, toxigénica) o",
            "  - Disentérica (sangre, moco - invasiva)",
            "  - Frecuencia aumentada (>3 deposiciones/día)",
            "",
            "OTROS SÍNTOMAS:",
            "  - Náuseas y vómitos (más prominentes en viral)",
            "  - Dolor abdominal tipo cólico",
            "  - Fiebre (más común en bacteriana invasiva)",
            "  - Tenesmo (disentería)",
            "  - Urgencia fecal",
            "",
            "SIGNOS DE DESHIDRATACIÓN:",
            "  - Sed intensa",
            "  - Sequedad de mucosas",
            "  - Disminución de turgencia cutánea",
            "  - Ojos hundidos",
            "  - Oliguria",
            "  - Hipotensión ortostática",
            "  - Taquicardia",
        ],
        risk_factors=[
            "Viaje reciente (diarrea del viajero)",
            "Consumo de alimentos de riesgo (mariscos crudos, huevos, carne poco cocida)",
            "Brotes epidémicos (guarderías, cruceros, restaurantes)",
            "Contacto con persona enferma",
            "Uso reciente de antibióticos (C. difficile)",
            "Inmunosupresión",
            "Edad extrema (niños, ancianos)",
            "Hospitalización",
            "Saneamiento deficiente",
        ],
        complications=[
            "Deshidratación severa",
            "Alteraciones electrolíticas (hipokalemia, hiponatremia)",
            "Insuficiencia renal aguda prerrenal",
            "Bacteriemia (Salmonella, especialmente en inmunocomprometidos)",
            "Síndrome urémico hemolítico (E. coli O157:H7)",
            "Síndrome de Guillain-Barré (Campylobacter)",
            "Artritis reactiva (Salmonella, Shigella, Campylobacter, Yersinia)",
            "Colitis pseudomembranosa (C. difficile)",
        ],
        diagnostic_criteria=[
            "DIAGNÓSTICO CLÍNICO (mayoría de casos):",
            "  - Historia clínica + examen físico",
            "  - No requiere estudios de rutina en casos leves",
            "",
            "INDICACIONES DE ESTUDIO DE HECES:",
            "  - Diarrea con sangre (disentería)",
            "  - Fiebre alta",
            "  - Diarrea severa o prolongada (>7 días)",
            "  - Hospitalización reciente / uso de antibióticos (C. difficile)",
            "  - Inmunosupresión",
            "  - Brote epidémico",
            "",
            "ESTUDIOS DE HECES:",
            "  - Coprocultivo (Salmonella, Shigella, Campylobacter)",
            "  - Toxina de C. difficile (PCR o EIA)",
            "  - Panel gastrointestinal molecular (PCR múltiple)",
            "  - Examen parasitológico (si diarrea prolongada, viajeros)",
            "  - Leucocitos fecales (menos usado)",
            "",
            "EVALUACIÓN DE DESHIDRATACIÓN:",
            "  - Leve: sed, mucosas secas, turgencia normal",
            "  - Moderada: turgencia reducida, ojos hundidos, taquicardia",
            "  - Severa: hipotensión, oliguria, letargia, shock",
        ],
        differential_diagnosis=[
            "Intoxicación alimentaria (toxinas preformadas)",
            "Diarrea asociada a antibióticos",
            "Enfermedad inflamatoria intestinal",
            "Síndrome de intestino irritable",
            "Colitis isquémica",
            "Diverticulitis",
            "Apendicitis",
            "Intolerancia a lactosa",
        ],
        treatment_protocol=[
            "REHIDRATACIÓN (base del tratamiento):",
            "  - Oral (preferida en deshidratación leve-moderada):",
            "    SRO (Sales de Rehidratación Oral) de OMS",
            "  - Intravenosa si: vómitos incoercibles, deshidratación severa, intolerancia oral",
            "    Ringer lactato o Salino 0.9%",
            "",
            "DIETA:",
            "  - No suspender alimentación (reiniciar temprano)",
            "  - Evitar lácteos transitoriamente (intolerancia secundaria a lactosa)",
            "  - Dieta blanda, fraccionada",
            "",
            "ANTIDIARREICOS:",
            "  - Loperamida: puede usarse en diarrea acuosa sin fiebre ni sangre",
            "  - CONTRAINDICADA en: disentería, fiebre alta, sospecha de C. difficile",
            "",
            "ANTIBIÓTICOS (indicados solo en casos específicos):",
            "  - Diarrea del viajero moderada-severa:",
            "    Azitromicina 1g dosis única o 500mg x 3 días",
            "    (o Ciprofloxacino 500mg c/12h x 3 días, pero resistencia creciente)",
            "  - Shigella: Azitromicina o Ciprofloxacino x 3 días",
            "  - Campylobacter: Azitromicina x 3 días",
            "  - C. difficile: Vancomicina oral 125mg c/6h x 10 días (primera línea)",
            "    o Fidaxomicina 200mg c/12h x 10 días",
            "  - Salmonella no tifoidea:",
            "    Generalmente no tratar (prolonga portador). Tratar si: bacteriemia,",
            "    inmunosupresión, edad extrema, prótesis vasculares",
            "",
            "NO DAR ANTIBIÓTICOS EN:",
            "  - Gastroenteritis viral (norovirus, rotavirus)",
            "  - E. coli O157:H7 (puede precipitar SUH)",
        ],
        emergency_signs=[
            "Deshidratación severa",
            "Hipotensión, shock",
            "Sangrado gastrointestinal significativo",
            "Incapacidad de tolerar líquidos orales",
            "Fiebre alta con apariencia tóxica",
            "Abdomen agudo",
            "Síntomas neurológicos (SUH, botulismo)",
            "Inmunodeprimido con diarrea severa",
        ],
        prognosis="Excelente en inmunocompetentes. Resolución espontánea en 2-5 días (viral) o 5-7 días (bacteriana). Mayor morbilidad en extremos de edad.",
        follow_up=[
            "No requiere seguimiento si resolución completa",
            "Reconsultar si: diarrea >7 días, sangre, fiebre persistente, deshidratación",
            "Coprocultivo de control no necesario (excepto manipuladores de alimentos, C. difficile)",
            "Evaluación de parasitosis si diarrea crónica post-viaje",
        ],
    ),
}


def get_all_infectious_conditions():
    """Retorna todas las condiciones infecciosas"""
    return INFECTIOUS_CONDITIONS


def get_condition(icd10_code: str):
    """Obtiene una condición específica por código ICD-10"""
    return INFECTIOUS_CONDITIONS.get(icd10_code)
