#!/usr/bin/env python3
"""
🫀 Condiciones Cardiovasculares - Base de Conocimiento Expandida
Basado en: ICD-10-CM 2026, AHA/ACC Guidelines, ESC Guidelines

Cobertura:
- Síndrome Coronario Agudo (I21) ✓ existente
- Hipertensión Arterial (I10) ✓ existente
- Insuficiencia Cardíaca (I50) ✓ nuevo
- Fibrilación Auricular (I48) ✓ nuevo
- Embolia Pulmonar (I26) ✓ nuevo
- Trombosis Venosa Profunda (I80) ✓ nuevo
- Endocarditis Infecciosa (I33) ✓ nuevo
- Pericarditis (I30) ✓ nuevo
"""

from dataclasses import dataclass
from typing import List

# Importar desde el módulo principal si existe
try:
    from medical_knowledge_base import MedicalCondition
except ImportError:

    @dataclass
    class MedicalCondition:
        """Condición médica completa"""

        icd10_code: str
        name: str
        category: str
        description: str
        symptoms: List[str]
        risk_factors: List[str]
        complications: List[str]
        diagnostic_criteria: List[str]
        differential_diagnosis: List[str]
        treatment_protocol: List[str]
        emergency_signs: List[str]
        prognosis: str
        follow_up: List[str]


CARDIOVASCULAR_CONDITIONS = {
    # =========================================================================
    # INFARTO AGUDO DE MIOCARDIO (I21)
    # Fuente: ESC Guidelines for STEMI 2023, AHA/ACC NSTEMI 2023
    # =========================================================================
    "I21": MedicalCondition(
        icd10_code="I21",
        name="Infarto Agudo de Miocardio",
        category="Cardiovascular",
        description="Necrosis del miocardio por oclusión trombótica de una arteria coronaria, manifestándose como STEMI o NSTEMI según cambios electrocardiográficos",
        symptoms=[
            "Dolor torácico opresivo (>20 min)",
            "Irradiación a brazo izquierdo, mandíbula, espalda o epigastrio",
            "Diaforesis profusa",
            "Disnea",
            "Náuseas y vómitos",
            "Sensación de muerte inminente",
            "Síncope o presíncope",
            "Fatiga extrema (más común en mujeres y diabéticos)",
            "Presentación atípica: dolor abdominal, confusión (ancianos)",
        ],
        risk_factors=[
            "Hipertensión arterial",
            "Diabetes mellitus",
            "Dislipidemia (LDL elevado, HDL bajo)",
            "Tabaquismo activo o pasivo",
            "Obesidad y sedentarismo",
            "Antecedentes familiares de enfermedad coronaria precoz",
            "Edad (>45 años hombres, >55 años mujeres)",
            "Síndrome metabólico",
            "Estrés crónico",
            "Consumo de cocaína",
        ],
        complications=[
            "Arritmias (FV, TV, bloqueos)",
            "Shock cardiogénico",
            "Insuficiencia cardíaca aguda",
            "Rotura de pared libre o septum",
            "Insuficiencia mitral aguda (rotura de músculo papilar)",
            "Aneurisma ventricular",
            "Trombosis mural y embolismo",
            "Pericarditis post-infarto (Síndrome de Dressler)",
            "Muerte súbita cardíaca",
        ],
        diagnostic_criteria=[
            "Elevación de troponinas con patrón de ascenso/descenso",
            "STEMI: Elevación del ST ≥1mm en 2 derivaciones contiguas",
            "NSTEMI: Sin elevación ST pero con troponinas elevadas",
            "Nuevo bloqueo de rama izquierda",
            "Síntomas de isquemia miocárdica",
            "Cambios en la motilidad segmentaria (ECO/RMN)",
            "Identificación de trombo coronario (coronariografía)",
        ],
        differential_diagnosis=[
            "Angina inestable",
            "Disección aórtica",
            "Embolia pulmonar",
            "Pericarditis aguda",
            "Espasmo coronario (Prinzmetal)",
            "Miocarditis",
            "Síndrome de Tako-Tsubo",
            "Dolor torácico musculoesquelético",
            "ERGE con espasmo esofágico",
        ],
        treatment_protocol=[
            "MONA: Morfina, Oxígeno, Nitroglicerina, Aspirina (carga 300mg)",
            "Antiagregación dual: Aspirina + Inhibidor P2Y12 (clopidogrel/ticagrelor)",
            "Anticoagulación: Heparina no fraccionada o enoxaparina",
            "STEMI: Angioplastia primaria <90 min (puerta-balón) o fibrinólisis",
            "NSTEMI: Estrategia invasiva temprana (<24h) según riesgo",
            "Beta-bloqueadores (metoprolol) si no contraindicados",
            "IECA/ARA-II iniciados dentro de 24h",
            "Estatinas alta intensidad (atorvastatina 80mg)",
            "Rehabilitación cardíaca post-alta",
        ],
        emergency_signs=[
            "Dolor torácico persistente >20 minutos",
            "Inestabilidad hemodinámica (hipotensión, shock)",
            "Arritmias ventriculares malignas",
            "Edema agudo de pulmón",
            "Signos de bajo gasto cardíaco",
        ],
        prognosis="Mortalidad hospitalaria 5-8% con reperfusión oportuna. FEVI post-infarto determina pronóstico a largo plazo. Supervivencia a 5 años >85% con tratamiento óptimo.",
        follow_up=[
            "Ecocardiograma para evaluar FEVI en 6-12 semanas",
            "Control cardiológico mensual primeros 3 meses",
            "Rehabilitación cardíaca programa completo",
            "Control de factores de riesgo cardiovascular",
            "Adherencia a doble antiagregación por 12 meses",
            "Evaluación de isquemia residual si síntomas",
        ],
    ),
    # =========================================================================
    # HIPERTENSIÓN ARTERIAL (I10)
    # Fuente: ESC/ESH Guidelines 2023, AHA/ACC Hypertension 2023
    # =========================================================================
    "I10": MedicalCondition(
        icd10_code="I10",
        name="Hipertensión Arterial Esencial",
        category="Cardiovascular",
        description="Elevación sostenida de la presión arterial sistémica ≥140/90 mmHg (o ≥130/80 según AHA), principal factor de riesgo cardiovascular modificable",
        symptoms=[
            "Generalmente asintomática (asesino silencioso)",
            "Cefalea occipital matutina",
            "Mareo o vértigo",
            "Acúfenos",
            "Epistaxis",
            "Visión borrosa",
            "Disnea de esfuerzo",
            "Palpitaciones",
            "Fatiga",
        ],
        risk_factors=[
            "Edad avanzada",
            "Antecedentes familiares de HTA",
            "Raza afrodescendiente",
            "Obesidad (IMC >30)",
            "Alto consumo de sodio",
            "Bajo consumo de potasio",
            "Sedentarismo",
            "Consumo excesivo de alcohol",
            "Estrés crónico",
            "Apnea obstructiva del sueño",
            "Diabetes mellitus",
            "Dislipidemia",
        ],
        complications=[
            "Enfermedad coronaria e infarto de miocardio",
            "Insuficiencia cardíaca",
            "Accidente cerebrovascular isquémico/hemorrágico",
            "Enfermedad renal crónica",
            "Retinopatía hipertensiva",
            "Aneurisma y disección aórtica",
            "Enfermedad arterial periférica",
            "Fibrilación auricular",
            "Demencia vascular",
        ],
        diagnostic_criteria=[
            "PA ≥140/90 mmHg en consultorio (2+ mediciones)",
            "PA ≥135/85 mmHg en MAPA (promedio 24h)",
            "PA ≥135/85 mmHg en AMPA (promedio domiciliario)",
            "Clasificación: Normal (<120/80), Elevada (120-129/<80)",
            "Estadio 1: 130-139/80-89 mmHg",
            "Estadio 2: ≥140/90 mmHg",
            "Crisis hipertensiva: ≥180/120 mmHg",
        ],
        differential_diagnosis=[
            "HTA de bata blanca",
            "HTA enmascarada",
            "Hipertensión secundaria:",
            "  - Enfermedad renal parenquimatosa",
            "  - Estenosis arteria renal",
            "  - Feocromocitoma",
            "  - Síndrome de Cushing",
            "  - Hiperaldosteronismo primario",
            "  - Coartación aórtica",
            "  - Apnea del sueño",
            "HTA inducida por fármacos (AINEs, corticoides)",
        ],
        treatment_protocol=[
            "Modificaciones del estilo de vida:",
            "  - Reducción de sodio (<2g/día)",
            "  - Dieta DASH rica en frutas y verduras",
            "  - Ejercicio aeróbico 150 min/semana",
            "  - Mantener peso saludable (IMC 18.5-24.9)",
            "  - Moderar alcohol y cesar tabaquismo",
            "Farmacoterapia primera línea:",
            "  - IECA (enalapril, lisinopril) o ARA-II (losartán, valsartán)",
            "  - Calcioantagonistas (amlodipino, nifedipino)",
            "  - Diuréticos tiazídicos (hidroclorotiazida, clortalidona)",
            "Combinaciones: IECA/ARA-II + CCB o diurético",
            "Meta: <130/80 mmHg en mayoría de pacientes",
        ],
        emergency_signs=[
            "Crisis hipertensiva ≥180/120 mmHg",
            "Encefalopatía hipertensiva (cefalea, confusión, convulsiones)",
            "Hemorragia intracraneal",
            "Disección aórtica aguda",
            "Edema agudo de pulmón hipertensivo",
            "Síndrome coronario agudo",
            "Eclampsia en embarazo",
        ],
        prognosis="Con tratamiento adecuado y control de PA <130/80, reducción del 20-25% en eventos cardiovasculares. Sin tratamiento, riesgo de complicaciones aumenta exponencialmente.",
        follow_up=[
            "Control mensual hasta alcanzar metas de PA",
            "Posteriormente control cada 3-6 meses",
            "Laboratorios anuales: función renal, electrolitos, perfil lipídico",
            "EKG anual para detectar HVI",
            "Fondo de ojo periódico",
            "Evaluación de daño de órgano blanco",
        ],
    ),
    # =========================================================================
    # ANGINA DE PECHO (I20)
    # Fuente: ESC Guidelines Chronic Coronary Syndromes 2024
    # =========================================================================
    "I20": MedicalCondition(
        icd10_code="I20",
        name="Angina de Pecho",
        category="Cardiovascular",
        description="Síndrome clínico de dolor o malestar torácico causado por isquemia miocárdica transitoria, sin necrosis, debido a desbalance entre demanda y aporte de oxígeno",
        symptoms=[
            "Dolor torácico opresivo o constrictivo retroesternal",
            "Duración típica 2-10 minutos",
            "Desencadenado por esfuerzo físico o estrés emocional",
            "Alivio con reposo o nitroglicerina sublingual",
            "Irradiación a brazo izquierdo, cuello, mandíbula",
            "Disnea asociada",
            "Angina equivalente: disnea de esfuerzo aislada (diabéticos, ancianos)",
        ],
        risk_factors=[
            "Enfermedad coronaria aterosclerótica",
            "Hipertensión arterial",
            "Diabetes mellitus",
            "Dislipidemia",
            "Tabaquismo",
            "Obesidad",
            "Antecedentes familiares de cardiopatía isquémica",
            "Edad avanzada",
            "Síndrome metabólico",
        ],
        complications=[
            "Progresión a angina inestable",
            "Infarto agudo de miocardio",
            "Arritmias",
            "Insuficiencia cardíaca",
            "Muerte súbita cardíaca",
        ],
        diagnostic_criteria=[
            "Angina típica: 3 criterios (retroesternal, desencadenada por esfuerzo, alivia con reposo/NTG)",
            "Angina atípica: 2 de 3 criterios",
            "Dolor no anginoso: 0-1 criterios",
            "ECG: Puede ser normal o mostrar cambios isquémicos durante episodio",
            "Prueba de esfuerzo positiva (depresión ST ≥1mm)",
            "Angio-TAC coronario para evaluar anatomía",
            "Coronariografía para diagnóstico definitivo",
        ],
        differential_diagnosis=[
            "ERGE y espasmo esofágico",
            "Costocondritis",
            "Dolor musculoesquelético",
            "Ansiedad y trastorno de pánico",
            "Pericarditis",
            "Embolia pulmonar",
            "Neumotórax",
            "Disección aórtica",
        ],
        treatment_protocol=[
            "Control de factores de riesgo",
            "Antianginosos:",
            "  - Nitroglicerina sublingual para episodios agudos",
            "  - Beta-bloqueadores (primera línea): metoprolol, bisoprolol",
            "  - Calcioantagonistas: amlodipino, diltiazem",
            "  - Nitratos de acción prolongada: mononitrato de isosorbide",
            "  - Ranolazina como segunda línea",
            "Prevención secundaria:",
            "  - Aspirina 100mg/día",
            "  - Estatinas alta intensidad",
            "  - IECA si disfunción VI o diabetes",
            "Revascularización: según anatomía y síntomas",
        ],
        emergency_signs=[
            "Angina de reposo (angina inestable)",
            "Angina de inicio reciente severa",
            "Angina in crescendo",
            "Duración prolongada >20 minutos",
            "No responde a nitroglicerina",
            "Síntomas vegetativos asociados",
        ],
        prognosis="Angina estable: supervivencia a 5 años >90% con tratamiento óptimo. Pronóstico depende de extensión de enfermedad coronaria y función ventricular.",
        follow_up=[
            "Control cardiológico cada 3-6 meses",
            "Prueba de esfuerzo anual o si cambio de síntomas",
            "Ecocardiograma si deterioro clínico",
            "Optimización de factores de riesgo",
            "Evaluación de calidad de vida y capacidad funcional",
        ],
    ),
    # =========================================================================
    # INSUFICIENCIA CARDÍACA (I50)
    # Fuente: ESC Guidelines for Heart Failure 2021, AHA/ACC 2022
    # =========================================================================
    "I50": MedicalCondition(
        icd10_code="I50",
        name="Insuficiencia Cardíaca",
        category="Cardiovascular",
        description="Síndrome clínico caracterizado por la incapacidad del corazón de mantener un gasto cardíaco adecuado para las demandas metabólicas del organismo",
        symptoms=[
            "Disnea de esfuerzo progresiva",
            "Ortopnea (disnea en decúbito)",
            "Disnea paroxística nocturna",
            "Edema de miembros inferiores bilateral",
            "Fatiga y debilidad",
            "Nicturia",
            "Tos nocturna",
            "Hepatomegalia dolorosa",
            "Distensión venosa yugular",
            "Aumento de peso (retención hídrica)",
            "Anorexia, náuseas",
            "Confusión (en casos severos)",
        ],
        risk_factors=[
            "Cardiopatía isquémica",
            "Hipertensión arterial crónica",
            "Diabetes mellitus",
            "Valvulopatías",
            "Miocardiopatía (dilatada, hipertrófica, restrictiva)",
            "Arritmias crónicas (FA)",
            "Cardiotoxicidad por quimioterapia",
            "Consumo de alcohol crónico",
            "Obesidad",
            "Apnea del sueño",
            "Enfermedad renal crónica",
            "Anemia crónica",
        ],
        complications=[
            "Edema agudo de pulmón",
            "Shock cardiogénico",
            "Arritmias ventriculares",
            "Tromboembolismo sistémico y pulmonar",
            "Insuficiencia renal (síndrome cardiorrenal)",
            "Insuficiencia hepática congestiva",
            "Caquexia cardíaca",
            "Muerte súbita cardíaca",
        ],
        diagnostic_criteria=[
            "Síntomas típicos de IC (disnea, fatiga, edemas)",
            "Signos de IC (ingurgitación yugular, estertores, edema)",
            "Evidencia objetiva de disfunción cardíaca:",
            "  - FEVI reducida (<40%) = ICFEr",
            "  - FEVI levemente reducida (40-49%) = ICFEmr",
            "  - FEVI preservada (≥50%) = ICFEp",
            "BNP >100 pg/mL o NT-proBNP >300 pg/mL",
            "Ecocardiograma con alteraciones estructurales/funcionales",
            "Clasificación funcional NYHA (I-IV)",
        ],
        differential_diagnosis=[
            "EPOC exacerbado",
            "Neumonía",
            "Síndrome nefrótico",
            "Cirrosis hepática",
            "Insuficiencia venosa crónica",
            "Embolia pulmonar",
            "Anemia severa",
            "Obesidad mórbida",
        ],
        treatment_protocol=[
            "ICFEr (FEVI <40%) - Cuádruple terapia:",
            "  1. IECA/ARA-II o Sacubitril-Valsartán",
            "  2. Beta-bloqueador (Carvedilol, Bisoprolol, Metoprolol)",
            "  3. Antagonista mineralocorticoide (Espironolactona, Eplerenona)",
            "  4. iSGLT2 (Dapagliflozina, Empagliflozina)",
            "Diuréticos de asa para congestión (Furosemida)",
            "Digoxina si FA con respuesta ventricular rápida",
            "Restricción de sodio (<2g/día) y líquidos (1.5-2L/día)",
            "Dispositivos: DAI si FEVI ≤35%, TRC si BCRI",
            "Trasplante cardíaco en casos refractarios",
        ],
        emergency_signs=[
            "Edema agudo de pulmón (disnea severa, esputo rosado)",
            "Hipotensión <90 mmHg sistólica",
            "Saturación de O2 <90%",
            "Oliguria <0.5 mL/kg/h",
            "Alteración del estado mental",
            "Extremidades frías y moteadas (shock)",
            "Lactato >2 mmol/L",
        ],
        prognosis="Mortalidad a 5 años 50-75% sin tratamiento óptimo. Con tratamiento actual: supervivencia mejorada significativamente. FEVI es el principal predictor pronóstico.",
        follow_up=[
            "Control cada 1-2 semanas hasta estabilización",
            "Luego cada 3-6 meses",
            "Ecocardiograma cada 6-12 meses",
            "Monitoreo de función renal y electrolitos",
            "BNP/NT-proBNP para seguimiento",
            "Peso diario por el paciente",
            "Vacunación (influenza, neumococo)",
            "Rehabilitación cardíaca",
        ],
    ),
    # =========================================================================
    # FIBRILACIÓN AURICULAR (I48)
    # Fuente: ESC Guidelines AF 2020, AHA/ACC 2023
    # =========================================================================
    "I48": MedicalCondition(
        icd10_code="I48",
        name="Fibrilación Auricular",
        category="Cardiovascular",
        description="Taquiarritmia supraventricular caracterizada por activación auricular descoordinada con deterioro consecuente de la función mecánica auricular",
        symptoms=[
            "Palpitaciones irregulares",
            "Fatiga",
            "Disnea de esfuerzo",
            "Mareos",
            "Dolor o molestia torácica",
            "Ansiedad",
            "Síncope (raro)",
            "Intolerancia al ejercicio",
            "Puede ser asintomática (30-40%)",
        ],
        risk_factors=[
            "Edad avanzada (>65 años)",
            "Hipertensión arterial",
            "Insuficiencia cardíaca",
            "Cardiopatía isquémica",
            "Valvulopatía mitral",
            "Hipertiroidismo",
            "Obesidad",
            "Apnea obstructiva del sueño",
            "Diabetes mellitus",
            "Enfermedad renal crónica",
            "Consumo excesivo de alcohol",
            "Cirugía cardíaca reciente",
        ],
        complications=[
            "Accidente cerebrovascular isquémico (riesgo 5x)",
            "Embolismo sistémico",
            "Insuficiencia cardíaca",
            "Deterioro cognitivo",
            "Disminución de calidad de vida",
            "Taquicardiomiopatía",
            "Muerte",
        ],
        diagnostic_criteria=[
            "ECG de 12 derivaciones mostrando:",
            "  - Ausencia de ondas P organizadas",
            "  - Ondas fibrilatorias (ondas f) irregulares",
            "  - Intervalos R-R irregularmente irregulares",
            "  - Frecuencia ventricular variable (típicamente 100-160 lpm sin tratamiento)",
            "Clasificación temporal:",
            "  - Paroxística: <7 días, autolimitada",
            "  - Persistente: >7 días o requiere cardioversión",
            "  - Persistente de larga duración: >12 meses",
            "  - Permanente: aceptada, sin intentos de ritmo sinusal",
            "Score CHA2DS2-VASc para riesgo tromboembólico",
        ],
        differential_diagnosis=[
            "Flutter auricular",
            "Taquicardia auricular multifocal",
            "Taquicardia supraventricular",
            "Extrasístoles auriculares frecuentes",
            "Síndrome de Wolff-Parkinson-White",
            "Artefacto en ECG",
        ],
        treatment_protocol=[
            "ESTRATEGIA ABC:",
            "A - Anticoagulación:",
            "  - CHA2DS2-VASc ≥2 (hombres) ≥3 (mujeres): Anticoagulación",
            "  - ACODs preferidos: Apixabán, Rivaroxabán, Dabigatrán, Edoxabán",
            "  - Warfarina si valvulopatía mitral mecánica/estenosis moderada-severa",
            "B - Better symptom control (control de síntomas):",
            "  - Control de frecuencia: Beta-bloqueadores, Verapamilo/Diltiazem, Digoxina",
            "  - Control de ritmo: Cardioversión, Amiodarona, Flecainida, Propafenona",
            "  - Ablación con catéter si falla tratamiento médico",
            "C - Comorbidities (tratar comorbilidades):",
            "  - Control de HTA, DM, IC",
            "  - Pérdida de peso si obesidad",
            "  - Tratamiento de apnea del sueño",
            "  - Reducción de alcohol",
        ],
        emergency_signs=[
            "Respuesta ventricular rápida >150 lpm con inestabilidad",
            "Hipotensión <90 mmHg",
            "Dolor torácico isquémico",
            "Insuficiencia cardíaca descompensada",
            "Síncope",
            "Signos de ACV agudo (déficit neurológico)",
            "Shock cardiogénico",
        ],
        prognosis="FA duplica mortalidad y quintuplica riesgo de ACV. Con anticoagulación adecuada y control de frecuencia/ritmo, pronóstico significativamente mejorado.",
        follow_up=[
            "Control cada 1-3 meses inicialmente",
            "Luego cada 6-12 meses si estable",
            "Monitoreo de INR si warfarina (mensual)",
            "Función renal y hepática periódica con ACODs",
            "Holter anual para evaluar control de frecuencia",
            "Ecocardiograma cada 1-2 años",
            "Evaluación de síntomas (EHRA score)",
        ],
    ),
    # =========================================================================
    # EMBOLIA PULMONAR (I26)
    # Fuente: ESC Guidelines PE 2019, CHEST Guidelines
    # =========================================================================
    "I26": MedicalCondition(
        icd10_code="I26",
        name="Embolia Pulmonar",
        category="Cardiovascular",
        description="Obstrucción aguda de las arterias pulmonares por trombos, generalmente provenientes del sistema venoso profundo de miembros inferiores",
        symptoms=[
            "Disnea de inicio súbito (73%)",
            "Dolor torácico pleurítico (66%)",
            "Taquipnea (>20 rpm)",
            "Taquicardia",
            "Tos seca o con hemoptisis",
            "Síncope (en EP masiva)",
            "Dolor o edema en miembro inferior (signos de TVP)",
            "Ansiedad",
            "Diaforesis",
            "Cianosis (en casos severos)",
        ],
        risk_factors=[
            "Trombosis venosa profunda previa",
            "Inmovilización prolongada (viajes >6h, hospitalización)",
            "Cirugía reciente (especialmente ortopédica)",
            "Traumatismo",
            "Cáncer activo",
            "Embarazo y puerperio",
            "Anticonceptivos orales/TRH",
            "Obesidad",
            "Tabaquismo",
            "Trombofilias hereditarias (Factor V Leiden, mutación protrombina)",
            "Insuficiencia cardíaca",
            "Síndrome antifosfolípido",
            "Edad avanzada",
        ],
        complications=[
            "Shock obstructivo",
            "Paro cardiorrespiratorio",
            "Infarto pulmonar",
            "Hipertensión pulmonar tromboembólica crónica",
            "Insuficiencia ventricular derecha",
            "Muerte (mortalidad 7-11% a 30 días sin tratamiento)",
        ],
        diagnostic_criteria=[
            "Evaluación de probabilidad clínica (Wells, Geneva):",
            "  - Wells PE: signos TVP, diagnóstico alternativo menos probable, FC>100, inmovilización/cirugía, antecedente TVP/EP, hemoptisis, cáncer",
            "Dímero D:",
            "  - <500 ng/mL (o ajustado por edad >50: edad x 10) descarta EP si probabilidad baja-intermedia",
            "Angiotomografía de arterias pulmonares (AngioTAC):",
            "  - Gold standard, visualiza trombos",
            "Gammagrafía V/Q si contraindicación a contraste",
            "Ecocardiograma: signos de sobrecarga VD",
            "Troponinas y BNP: estratificación pronóstica",
        ],
        differential_diagnosis=[
            "Síndrome coronario agudo",
            "Disección aórtica",
            "Neumonía",
            "Neumotórax",
            "Pericarditis",
            "Pleuritis",
            "Ansiedad/hiperventilación",
            "Exacerbación de EPOC/asma",
            "Costocondritis",
        ],
        treatment_protocol=[
            "EP de ALTO RIESGO (shock/hipotensión):",
            "  - Trombólisis sistémica (Alteplasa 100mg IV en 2h)",
            "  - Anticoagulación inmediata con heparina",
            "  - Soporte hemodinámico (vasopresores)",
            "  - Considerar embolectomía si trombólisis contraindicada",
            "EP de RIESGO INTERMEDIO-ALTO:",
            "  - Anticoagulación + monitorización estrecha en UCI",
            "  - Trombólisis de rescate si deterioro",
            "EP de RIESGO BAJO-INTERMEDIO:",
            "  - Anticoagulación: HBPM → ACODs",
            "  - ACODs directos: Rivaroxabán, Apixabán (preferidos)",
            "  - Duración: 3 meses mínimo, indefinida si factor persistente",
            "PREVENCIÓN SECUNDARIA:",
            "  - Anticoagulación prolongada según riesgo-beneficio",
            "  - Medias de compresión si síndrome post-trombótico",
        ],
        emergency_signs=[
            "Hipotensión sistólica <90 mmHg o caída >40 mmHg",
            "Shock (extremidades frías, oliguria, confusión)",
            "Saturación O2 <90%",
            "Paro cardiorrespiratorio",
            "Síncope",
            "Bradicardia severa",
            "Cianosis central",
        ],
        prognosis="Mortalidad 2-4% con tratamiento adecuado. EP masiva sin tratamiento: 30% mortalidad. Riesgo de HPTEC: 2-4%.",
        follow_up=[
            "Control 1-2 semanas post-alta",
            "Evaluación a los 3 meses: continuar anticoagulación?",
            "Búsqueda de cáncer oculto si EP no provocada",
            "Ecocardiograma a 3-6 meses si disfunción VD inicial",
            "Despistaje de HPTEC si disnea persistente",
            "Evaluación de trombofilias si recurrencia o historia familiar",
        ],
    ),
    # =========================================================================
    # TROMBOSIS VENOSA PROFUNDA (I80)
    # Fuente: ACCP Guidelines 2021, ESC Guidelines VTE
    # =========================================================================
    "I80": MedicalCondition(
        icd10_code="I80",
        name="Trombosis Venosa Profunda",
        category="Cardiovascular",
        description="Formación de un trombo en el sistema venoso profundo, más frecuentemente en miembros inferiores",
        symptoms=[
            "Edema unilateral de miembro inferior",
            "Dolor en pantorrilla o muslo",
            "Aumento de temperatura local",
            "Eritema en trayecto venoso",
            "Empastamiento de pantorrilla",
            "Signo de Homans positivo (dolor con dorsiflexión)",
            "Diferencia de perímetro >3cm con miembro contralateral",
            "Cordón venoso palpable",
            "Puede ser asintomática",
        ],
        risk_factors=[
            "Inmovilización prolongada",
            "Cirugía reciente (ortopédica, abdominal)",
            "Traumatismo de miembro inferior",
            "Cáncer activo",
            "Embarazo y puerperio",
            "Anticonceptivos orales/TRH",
            "Obesidad (IMC >30)",
            "Edad >60 años",
            "TVP/EP previa",
            "Trombofilias hereditarias",
            "Viajes prolongados >6 horas",
            "Catéter venoso central",
            "Insuficiencia cardíaca/respiratoria",
        ],
        complications=[
            "Embolia pulmonar (complicación más grave)",
            "Síndrome post-trombótico (20-50%)",
            "Úlceras venosas crónicas",
            "Recurrencia de TVP",
            "Hipertensión pulmonar tromboembólica crónica",
            "Gangrena venosa (rara, flegmasia)",
        ],
        diagnostic_criteria=[
            "Score de Wells para TVP:",
            "  - Cáncer activo (+1), parálisis/inmovilización (+1)",
            "  - Reposo en cama >3 días o cirugía <12 sem (+1)",
            "  - Dolor localizado en trayecto venoso (+1)",
            "  - Edema de toda la extremidad (+1)",
            "  - Edema de pantorrilla >3cm (+1)",
            "  - Edema con fóvea (+1), venas colaterales (+1)",
            "  - TVP previa (+1)",
            "  - Diagnóstico alternativo más probable (-2)",
            "ALGORITMO DIAGNÓSTICO:",
            "  - Probabilidad baja + Dímero D negativo: excluye TVP",
            "  - Probabilidad alta o Dímero D positivo: Ecografía doppler",
            "Ecografía doppler venosa: Gold standard",
            "  - Falta de compresibilidad de la vena",
            "  - Ausencia de flujo",
            "  - Visualización directa del trombo",
        ],
        differential_diagnosis=[
            "Celulitis",
            "Rotura de quiste de Baker",
            "Hematoma muscular",
            "Linfedema",
            "Insuficiencia venosa crónica",
            "Síndrome compartimental",
            "Rotura muscular",
            "Artritis",
        ],
        treatment_protocol=[
            "ANTICOAGULACIÓN (base del tratamiento):",
            "  - ACODs preferidos: Rivaroxabán, Apixabán (sin necesidad de HBPM previa)",
            "  - Alternativa: HBPM → Warfarina (INR 2-3)",
            "  - Duración mínima: 3 meses",
            "DURACIÓN SEGÚN CONTEXTO:",
            "  - Factor provocador transitorio mayor: 3 meses",
            "  - Factor provocador menor o no provocada: ≥3 meses, considerar indefinida",
            "  - Cáncer activo: HBPM o ACOD indefinido",
            "  - Recurrencia: anticoagulación indefinida",
            "MEDIDAS ADICIONALES:",
            "  - Deambulación precoz",
            "  - Elevación de miembro",
            "  - Medias de compresión (30-40 mmHg) para prevenir síndrome post-trombótico",
            "FILTRO DE VENA CAVA INFERIOR:",
            "  - Solo si anticoagulación contraindicada o falla",
        ],
        emergency_signs=[
            "Sospecha de embolia pulmonar (disnea, dolor torácico)",
            "Flegmasia alba dolens (edema masivo, palidez)",
            "Flegmasia cerulea dolens (edema, cianosis, amenaza de gangrena)",
            "Isquemia arterial concomitante",
            "Síndrome compartimental",
        ],
        prognosis="Con anticoagulación adecuada: excelente. Riesgo de EP en TVP proximal no tratada: 50%. Síndrome post-trombótico: 20-50%.",
        follow_up=[
            "Control clínico a las 2 semanas",
            "INR semanal si warfarina hasta estabilidad",
            "Evaluación a 3 meses: duración de anticoagulación",
            "Función renal periódica con ACODs",
            "Evaluación de síndrome post-trombótico",
            "Búsqueda de cáncer oculto si TVP no provocada en >40 años",
        ],
    ),
    # =========================================================================
    # ENDOCARDITIS INFECCIOSA (I33)
    # Fuente: ESC Guidelines IE 2015, AHA Guidelines
    # =========================================================================
    "I33": MedicalCondition(
        icd10_code="I33",
        name="Endocarditis Infecciosa",
        category="Cardiovascular",
        description="Infección del endocardio valvular o mural, típicamente caracterizada por vegetaciones en las válvulas cardíacas",
        symptoms=[
            "Fiebre (90%) - puede ser intermitente o persistente",
            "Escalofríos y sudoración nocturna",
            "Soplo cardíaco nuevo o cambiante (85%)",
            "Fatiga y malestar general",
            "Pérdida de peso",
            "Artralgias y mialgias",
            "Fenómenos embólicos:",
            "  - Petequias (conjuntivales, mucosas)",
            "  - Hemorragias en astilla (uñas)",
            "  - Nódulos de Osler (dedos, dolorosos)",
            "  - Manchas de Janeway (palmas/plantas, indoloras)",
            "  - Manchas de Roth (retina)",
            "Esplenomegalia",
            "Déficit neurológico (embolismo cerebral)",
        ],
        risk_factors=[
            "Valvulopatía previa (reumática, degenerativa)",
            "Prótesis valvular",
            "Endocarditis previa",
            "Cardiopatía congénita",
            "Uso de drogas intravenosas",
            "Catéteres venosos centrales",
            "Hemodiálisis",
            "Diabetes mellitus",
            "Inmunosupresión",
            "Mala higiene dental",
            "Procedimientos dentales recientes",
        ],
        complications=[
            "Insuficiencia cardíaca (causa más común de mortalidad)",
            "Embolismos sistémicos (cerebral, esplénico, renal)",
            "ACV embólico",
            "Aneurismas micóticos",
            "Abscesos perivalvulares",
            "Bloqueo auriculoventricular",
            "Glomerulonefritis",
            "Sepsis",
            "Muerte (mortalidad 15-30%)",
        ],
        diagnostic_criteria=[
            "CRITERIOS DE DUKE MODIFICADOS:",
            "CRITERIOS MAYORES:",
            "  1. Hemocultivos positivos:",
            "     - 2 hemocultivos con microorganismo típico (S. aureus, S. viridans, HACEK, Enterococcus)",
            "     - Hemocultivos persistentemente positivos",
            "  2. Evidencia de afectación endocárdica:",
            "     - Ecocardiograma: vegetación, absceso, nueva dehiscencia protésica",
            "     - Nueva regurgitación valvular",
            "CRITERIOS MENORES:",
            "  - Predisposición (condición cardíaca, uso drogas IV)",
            "  - Fiebre ≥38°C",
            "  - Fenómenos vasculares (embolismos, aneurisma micótico)",
            "  - Fenómenos inmunológicos (Osler, Roth, factor reumatoide)",
            "  - Evidencia microbiológica que no cumple criterio mayor",
            "DIAGNÓSTICO: 2 mayores, o 1 mayor + 3 menores, o 5 menores",
        ],
        differential_diagnosis=[
            "Fiebre de origen desconocido",
            "Lupus eritematoso sistémico",
            "Fiebre reumática aguda",
            "Neoplasias (linfoma, leucemia)",
            "Tuberculosis",
            "Infección de catéter",
            "Osteomielitis",
        ],
        treatment_protocol=[
            "ANTIBIOTICOTERAPIA (4-6 semanas IV):",
            "  - Válvula nativa, S. viridans sensible:",
            "    Penicilina G o Ceftriaxona + Gentamicina",
            "  - S. aureus válvula nativa:",
            "    Oxacilina/Nafcilina (o Vancomicina si MRSA) + Gentamicina inicial",
            "  - Prótesis valvular:",
            "    Vancomicina + Rifampicina + Gentamicina",
            "  - Empírico: Ampicilina-Sulbactam + Gentamicina (o Vancomicina)",
            "INDICACIONES DE CIRUGÍA:",
            "  - Insuficiencia cardíaca refractaria",
            "  - Infección no controlada (fiebre persistente, extensión local)",
            "  - Prevención de embolismo (vegetación grande >10mm)",
            "  - Absceso perivalvular",
            "  - Endocarditis fúngica",
            "PROFILAXIS POST-TRATAMIENTO:",
            "  - Higiene dental rigurosa",
            "  - Profilaxis antes de procedimientos de alto riesgo",
        ],
        emergency_signs=[
            "Insuficiencia cardíaca aguda",
            "Shock séptico",
            "ACV embólico",
            "Rotura de aneurisma micótico",
            "Bloqueo AV completo (extensión a sistema de conducción)",
            "Hemoptisis masiva",
        ],
        prognosis="Mortalidad hospitalaria 15-20%. Mayor en EI protésica, S. aureus, insuficiencia cardíaca, embolismo cerebral. Supervivencia a 5 años: 60-70%.",
        follow_up=[
            "Control semanal durante antibioticoterapia",
            "Ecocardiograma al finalizar tratamiento",
            "Hemocultivos de control",
            "Evaluación dental",
            "Control cardiológico cada 3-6 meses primer año",
            "Educación sobre profilaxis de endocarditis",
        ],
    ),
    # =========================================================================
    # PERICARDITIS (I30)
    # Fuente: ESC Guidelines Pericardial Diseases 2015
    # =========================================================================
    "I30": MedicalCondition(
        icd10_code="I30",
        name="Pericarditis Aguda",
        category="Cardiovascular",
        description="Inflamación del pericardio, típicamente de etiología viral o idiopática, caracterizada por dolor torácico y cambios electrocardiográficos",
        symptoms=[
            "Dolor torácico pleurítico (>85%):",
            "  - Agudo, lancinante",
            "  - Retroesternal o precordial",
            "  - Empeora con inspiración y decúbito",
            "  - Mejora al sentarse e inclinarse hacia adelante",
            "Fiebre (usualmente bajo grado)",
            "Tos seca",
            "Disnea",
            "Malestar general",
            "Pródromo viral previo (frecuente)",
            "Frote pericárdico a la auscultación (patognomónico)",
        ],
        risk_factors=[
            "Infección viral reciente (Coxsackie, Echovirus, adenovirus)",
            "Tuberculosis (en áreas endémicas)",
            "Enfermedad autoinmune (LES, AR)",
            "Insuficiencia renal (uremia)",
            "Post-infarto de miocardio (Síndrome de Dressler)",
            "Post-cirugía cardíaca o trauma torácico",
            "Neoplasias",
            "Radioterapia torácica",
            "Hipotiroidismo",
        ],
        complications=[
            "Derrame pericárdico",
            "Taponamiento cardíaco",
            "Pericarditis constrictiva",
            "Pericarditis recurrente (20-30%)",
            "Miopericarditis (afectación miocárdica asociada)",
        ],
        diagnostic_criteria=[
            "DIAGNÓSTICO: ≥2 de los siguientes criterios:",
            "  1. Dolor torácico típico (pleurítico, mejora sentado)",
            "  2. Frote pericárdico",
            "  3. Cambios ECG:",
            "     - Elevación difusa del ST (cóncava hacia arriba)",
            "     - Depresión del PR",
            "     - Inversión de ondas T (tardía)",
            "  4. Derrame pericárdico nuevo o en aumento",
            "ESTUDIOS COMPLEMENTARIOS:",
            "  - PCR y VSG elevados",
            "  - Leucocitosis leve",
            "  - Troponinas: pueden elevarse si miopericarditis",
            "  - Ecocardiograma: descartar derrame",
            "  - Rx tórax: puede mostrar cardiomegalia si derrame grande",
        ],
        differential_diagnosis=[
            "Síndrome coronario agudo",
            "Embolia pulmonar",
            "Disección aórtica",
            "Neumonía",
            "Pleuritis",
            "Costocondritis",
            "Herpes zóster",
            "ERGE",
        ],
        treatment_protocol=[
            "PERICARDITIS NO COMPLICADA (ambulatorio):",
            "  - Reposo relativo (evitar ejercicio hasta resolución)",
            "  - AINEs: Ibuprofeno 600mg c/8h o Aspirina 750-1000mg c/8h",
            "    (por 1-2 semanas, luego reducir gradualmente)",
            "  - Colchicina 0.5mg c/12h (3 meses) - reduce recurrencias",
            "  - Protección gástrica",
            "CORTICOIDES (segunda línea):",
            "  - Solo si contraindicación a AINEs/aspirina",
            "  - Prednisona 0.25-0.5 mg/kg/día con descenso lento",
            "  - Aumentan riesgo de recurrencia",
            "PERICARDITIS RECURRENTE:",
            "  - Colchicina prolongada (≥6 meses)",
            "  - Considerar Azatioprina, Anakinra si refractaria",
            "INDICACIONES DE HOSPITALIZACIÓN:",
            "  - Fiebre alta >38°C",
            "  - Curso subagudo",
            "  - Derrame pericárdico grande",
            "  - Elevación de troponinas (miopericarditis)",
            "  - Fallo a tratamiento inicial",
        ],
        emergency_signs=[
            "Taponamiento cardíaco:",
            "  - Hipotensión",
            "  - Ingurgitación yugular",
            "  - Ruidos cardíacos apagados",
            "  - Taquicardia",
            "  - Pulso paradójico >10 mmHg",
            "Signos de miopericarditis severa",
            "Inestabilidad hemodinámica",
        ],
        prognosis="Excelente para pericarditis viral/idiopática. Resolución en 1-2 semanas con tratamiento. Recurrencia: 20-30%. Constricción: <1%.",
        follow_up=[
            "Control a la semana de inicio de tratamiento",
            "Ecocardiograma de control si derrame inicial",
            "PCR/VSG para guiar duración del tratamiento",
            "Control al mes y a los 3 meses",
            "Evitar ejercicio intenso hasta normalización de marcadores",
            "Educación sobre signos de recurrencia",
        ],
    ),
}


def get_all_cardiovascular_conditions():
    """Retorna todas las condiciones cardiovasculares"""
    return CARDIOVASCULAR_CONDITIONS


def get_condition(icd10_code: str):
    """Obtiene una condición específica por código ICD-10"""
    return CARDIOVASCULAR_CONDITIONS.get(icd10_code)
