#!/usr/bin/env python3
"""
🫄 Condiciones Gastrointestinales - Base de Conocimiento Expandida
Basado en: ICD-10-CM 2026, ACG Guidelines, ASGE Guidelines, AGA Guidelines

Cobertura:
- Apendicitis Aguda (K35) ✓ nuevo
- Colelitiasis y Colecistitis (K80/K81) ✓ nuevo
- Pancreatitis Aguda (K85) ✓ nuevo
- Enfermedad por Reflujo Gastroesofágico (K21) ✓ nuevo
- Úlcera Péptica (K25/K26/K27) ✓ nuevo
- Hemorragia Digestiva Alta (K92.0) ✓ nuevo
- Hemorragia Digestiva Baja (K92.1) ✓ nuevo
- Obstrucción Intestinal (K56) ✓ nuevo
- Enfermedad Inflamatoria Intestinal (K50/K51) ✓ nuevo
- Cirrosis Hepática (K74) ✓ nuevo
"""

from dataclasses import dataclass
from typing import List

try:
    from medical_knowledge_base import MedicalCondition
except ImportError:

    @dataclass
    class MedicalCondition:
        """Condición médica completa"""

        icd10_code: str
        name: str
        category: str
        description: str
        symptoms: List[str]
        risk_factors: List[str]
        complications: List[str]
        diagnostic_criteria: List[str]
        differential_diagnosis: List[str]
        treatment_protocol: List[str]
        emergency_signs: List[str]
        prognosis: str
        follow_up: List[str]


GASTROINTESTINAL_CONDITIONS = {
    # =========================================================================
    # APENDICITIS AGUDA (K35)
    # Fuente: WSES Guidelines 2020, SAGES, ACR Appropriateness Criteria
    # =========================================================================
    "K35": MedicalCondition(
        icd10_code="K35",
        name="Apendicitis Aguda",
        category="Gastrointestinal",
        description="Inflamación aguda del apéndice cecal, típicamente causada por obstrucción luminal por fecalito, hiperplasia linfoide o menos frecuentemente cuerpos extraños o tumores",
        symptoms=[
            "Dolor abdominal (secuencia clásica):",
            "  1. Dolor periumbilical inicial vago (visceral)",
            "  2. Migración a fosa ilíaca derecha (6-12h)",
            "  3. Localización en punto de McBurney",
            "Anorexia (casi universal)",
            "Náuseas y vómitos (generalmente post-dolor)",
            "Febrícula (37.5-38°C)",
            "A la exploración:",
            "  - Dolor en punto de McBurney (sensibilidad 50-94%)",
            "  - Signo de Blumberg (rebote) positivo",
            "  - Signo de Rovsing (dolor FID al presionar FII)",
            "  - Signo del psoas (dolor al extender cadera)",
            "  - Signo del obturador (dolor al rotar internamente)",
            "  - Defensa muscular localizada",
        ],
        risk_factors=[
            "Edad (pico 10-30 años)",
            "Sexo masculino (ligeramente mayor riesgo)",
            "Dieta baja en fibra",
            "Historia familiar",
            "Infecciones (post-virales)",
            "Cuerpos extraños (raro)",
        ],
        complications=[
            "Perforación (20-30% al diagnóstico)",
            "Absceso periapendicular",
            "Peritonitis localizada y generalizada",
            "Pileflebitis (tromboflebitis portal)",
            "Sepsis",
            "Obstrucción intestinal por adherencias (post-cirugía)",
            "Infección de sitio quirúrgico",
        ],
        diagnostic_criteria=[
            "SCORE DE ALVARADO (MANTRELS):",
            "  - Migración del dolor (1 punto)",
            "  - Anorexia (1 punto)",
            "  - Náuseas/vómitos (1 punto)",
            "  - Dolor en FID (2 puntos)",
            "  - Rebote positivo (1 punto)",
            "  - Elevación de temperatura (1 punto)",
            "  - Leucocitosis >10,000 (2 puntos)",
            "  - Desviación izquierda >75% neutrófilos (1 punto)",
            "  Interpretación:",
            "    - ≤4: Baja probabilidad",
            "    - 5-6: Compatible, requiere imagen",
            "    - 7-8: Alta probabilidad",
            "    - 9-10: Muy alta probabilidad",
            "",
            "LABORATORIO:",
            "  - Leucocitosis (10,000-18,000/μL)",
            "  - Neutrofilia con desviación izquierda",
            "  - PCR elevada (menos específica)",
            "",
            "IMAGEN (si score intermedio o duda):",
            "  - TAC abdomen-pelvis con contraste IV: S>95%, E>95%",
            "    (Gold standard en adultos)",
            "  - Ecografía: primera elección en embarazadas, niños, mujeres jóvenes",
            "    S 75-90%, signo diana >6mm no compresible",
            "  - RM: alternativa en embarazadas",
        ],
        differential_diagnosis=[
            "Gastroenteritis aguda",
            "Linfadenitis mesentérica",
            "Enfermedad inflamatoria pélvica",
            "Embarazo ectópico",
            "Quiste ovárico roto/torsión",
            "Endometriosis",
            "Diverticulitis de Meckel",
            "Enfermedad de Crohn",
            "Obstrucción intestinal",
            "Cólico renal derecho",
            "Infección urinaria",
            "Diverticulitis cecal",
        ],
        treatment_protocol=[
            "TRATAMIENTO ESTÁNDAR: APENDICECTOMÍA",
            "  - Laparoscópica preferida (menor morbilidad)",
            "  - Abierta si no disponible o complicaciones locales",
            "  - Idealmente dentro de 24h del diagnóstico",
            "",
            "APENDICITIS NO COMPLICADA:",
            "  - Antibióticos perioperatorios (dosis única):",
            "    Cefazolina 2g IV + Metronidazol 500mg IV",
            "  - Cirugía temprana",
            "  - Alta a las 24-48h si evolución favorable",
            "",
            "APENDICITIS COMPLICADA (perforada/absceso):",
            "  - Antibióticos de amplio espectro:",
            "    Piperacilina-Tazobactam 4.5g IV c/6h, o",
            "    Ciprofloxacino + Metronidazol",
            "  - Duración: 4-7 días post-cirugía",
            "  - Absceso >3-5cm: considerar drenaje percutáneo primero",
            "",
            "TRATAMIENTO ANTIBIÓTICO SOLO (casos seleccionados):",
            "  - Considerar en: apendicitis no complicada en pacientes seleccionados",
            "  - Riesgo de recurrencia: 20-30%",
            "  - Requiere seguimiento estrecho",
        ],
        emergency_signs=[
            "Dolor abdominal severo difuso (peritonitis)",
            "Fiebre alta >38.5°C con taquicardia",
            "Defensa abdominal generalizada",
            "Hipotensión (shock séptico)",
            "Deterioro rápido del estado general",
            "Silencio abdominal (íleo)",
        ],
        prognosis="Excelente si tratamiento oportuno. Mortalidad <0.1% no complicada, 0.5-3% si perforada. Complicaciones aumentan con retraso diagnóstico.",
        follow_up=[
            "Control post-quirúrgico a los 7-14 días",
            "Revisión de histopatología (descartar neoplasia en >40 años)",
            "Signos de alarma para reconsultar: fiebre, dolor creciente, vómitos",
            "Seguimiento endoscópico si neoplasia apendicular",
        ],
    ),
    # =========================================================================
    # COLECISTITIS AGUDA (K81.0) y COLELITIASIS (K80)
    # Fuente: Tokyo Guidelines 2018 (TG18), WSES 2020
    # =========================================================================
    "K80": MedicalCondition(
        icd10_code="K80",
        name="Colelitiasis con Colecistitis Aguda",
        category="Gastrointestinal",
        description="Inflamación aguda de la vesícula biliar, generalmente secundaria a obstrucción del conducto cístico por un cálculo biliar",
        symptoms=[
            "Dolor en hipocondrio derecho/epigastrio:",
            "  - Inicio brusco, severo",
            "  - Constante (no cólico, a diferencia del biliar simple)",
            "  - Duración >6 horas",
            "  - Irradiación a espalda derecha o escápula",
            "  - Exacerbado por movimiento y respiración",
            "Fiebre (38-39°C)",
            "Náuseas y vómitos",
            "Anorexia",
            "A la exploración:",
            "  - Signo de Murphy positivo (patognomónico)",
            "  - Defensa en hipocondrio derecho",
            "  - Vesícula palpable (33%)",
            "Ictericia leve (si coledocolitiasis asociada)",
        ],
        risk_factors=[
            "Las 4 F: Female, Forty, Fertile, Fat",
            "Sexo femenino (2-3x)",
            "Edad >40 años",
            "Obesidad (IMC >30)",
            "Pérdida rápida de peso",
            "Embarazo y multiparidad",
            "Anticonceptivos orales/TRH",
            "Diabetes mellitus",
            "Cirrosis hepática",
            "Enfermedad ileal (Crohn, resección)",
            "Nutrición parenteral total",
            "Historia familiar",
        ],
        complications=[
            "Gangrena vesicular (7-20%)",
            "Perforación (10% de gangrenosas)",
            "Absceso perivesicular",
            "Colangitis aguda",
            "Pancreatitis biliar",
            "Fístula colecistoentérica",
            "Íleo biliar",
            "Vesícula de porcelana (riesgo neoplasia)",
            "Sepsis",
        ],
        diagnostic_criteria=[
            "CRITERIOS DIAGNÓSTICOS TG18:",
            "A. Signos locales de inflamación:",
            "  - Signo de Murphy",
            "  - Masa/dolor/defensa en cuadrante superior derecho",
            "B. Signos sistémicos de inflamación:",
            "  - Fiebre (>38°C)",
            "  - PCR elevada",
            "  - Leucocitosis",
            "C. Imagen confirmatoria:",
            "  - Diagnóstico definitivo: A + B + C",
            "  - Diagnóstico sospechoso: A + B",
            "",
            "LABORATORIO:",
            "  - Leucocitosis (12,000-15,000/μL)",
            "  - PCR elevada",
            "  - Elevación leve de bilirrubina y fosfatasa alcalina",
            "  - Transaminasas normales o ligeramente elevadas",
            "",
            "ECOGRAFÍA ABDOMINAL (primera elección):",
            "  - Litiasis vesicular",
            "  - Engrosamiento de pared vesicular (>4mm)",
            "  - Líquido perivesicular",
            "  - Signo de Murphy ecográfico",
            "  - S 88%, E 80%",
            "",
            "CLASIFICACIÓN DE SEVERIDAD TG18:",
            "  - Grado I (Leve): sin disfunción orgánica",
            "  - Grado II (Moderada): leucocitosis >18,000, masa palpable, síntomas >72h, inflamación local marcada",
            "  - Grado III (Severa): disfunción orgánica (cardiovascular, neurológica, respiratoria, renal, hepática, hematológica)",
        ],
        differential_diagnosis=[
            "Cólico biliar simple",
            "Colangitis aguda",
            "Úlcera péptica perforada",
            "Pancreatitis aguda",
            "Apendicitis (alta)",
            "Hepatitis aguda",
            "Absceso hepático",
            "Neumonía basal derecha",
            "Pielonefritis derecha",
            "Síndrome coronario agudo (IAM inferior)",
        ],
        treatment_protocol=[
            "TRATAMIENTO INICIAL (todas las severidades):",
            "  - NPO (nada por boca)",
            "  - Hidratación IV",
            "  - Analgesia: Ketorolaco, Metamizol, opioides si severo",
            "  - Antibióticos IV:",
            "    Leve-Moderada: Ceftriaxona 1-2g/día + Metronidazol 500mg c/8h",
            "    Severa: Piperacilina-Tazobactam 4.5g c/6h o Meropenem",
            "",
            "COLECISTECTOMÍA LAPAROSCÓPICA:",
            "  - GRADO I: Cirugía temprana (<72h, idealmente <24h)",
            "  - GRADO II: Cirugía temprana si posible, o diferida si alto riesgo",
            "  - GRADO III: Primero estabilizar, considerar drenaje vesicular percutáneo",
            "",
            "COLECISTOSTOMÍA PERCUTÁNEA:",
            "  - Indicada en grado III o alto riesgo quirúrgico",
            "  - Puente a cirugía diferida",
            "",
            "CPRE:",
            "  - Si coledocolitiasis asociada",
            "  - Pre o post-colecistectomía según protocolo institucional",
        ],
        emergency_signs=[
            "Colecistitis gangrenosa o perforada:",
            "  - Fiebre alta >39°C",
            "  - Dolor severo generalizado",
            "  - Defensa abdominal difusa",
            "  - Shock (hipotensión, taquicardia)",
            "  - Alteración del estado mental",
            "Colangitis aguda (Triada de Charcot: fiebre, ictericia, dolor HCD)",
            "Péntada de Reynolds (+ shock + confusión)",
        ],
        prognosis="Excelente con colecistectomía temprana. Mortalidad <1% grado I-II, hasta 10% grado III. Conversión a abierta: 5-30%.",
        follow_up=[
            "Control a los 7-14 días post-cirugía",
            "Dieta progresiva, inicialmente baja en grasas",
            "Signos de alarma: ictericia, fiebre, dolor severo",
            "Histopatología de vesícula (descartar neoplasia)",
            "Si coledocolitiasis residual: CPRE",
        ],
    ),
    # =========================================================================
    # PANCREATITIS AGUDA (K85)
    # Fuente: Atlanta Classification 2012, ACG Guidelines 2024
    # =========================================================================
    "K85": MedicalCondition(
        icd10_code="K85",
        name="Pancreatitis Aguda",
        category="Gastrointestinal",
        description="Inflamación aguda del páncreas con activación prematura de enzimas pancreáticas y autodigestión del órgano. Etiología biliar y alcohólica representan >80% de casos",
        symptoms=[
            "Dolor epigástrico/mesogástrico:",
            "  - Inicio agudo, severo (pico en minutos a horas)",
            "  - Constante, no cólico",
            "  - Irradiación en cinturón a espalda (50%)",
            "  - Empeora con ingesta, mejora al inclinarse hacia adelante",
            "Náuseas y vómitos persistentes",
            "Distensión abdominal",
            "Fiebre",
            "Taquicardia",
            "Defensa epigástrica",
            "Íleo paralítico",
            "Signos de gravedad:",
            "  - Equimosis periumbilical (signo de Cullen)",
            "  - Equimosis en flancos (signo de Grey-Turner)",
            "  - Derrame pleural (más frecuente izquierdo)",
            "Ictericia (si biliar)",
        ],
        risk_factors=[
            "ETIOLOGÍA (Mnemotécnico: I GET SMASHED):",
            "  I - Idiopática",
            "  G - Gallstones (colelitiasis, 40%)",
            "  E - Etanol (alcohol, 30%)",
            "  T - Trauma/Tumores",
            "  S - Steroids",
            "  M - Mumps (parotiditis) y otros virus",
            "  A - Autoinmune",
            "  S - Scorpion sting, Sphincter of Oddi dysfunction",
            "  H - Hiperlipidemia (TG>1000), Hipercalcemia, Hipotermia",
            "  E - ERCP/CPRE",
            "  D - Drugs (Azatioprina, Valproato, Furosemida, etc.)",
        ],
        complications=[
            "LOCALES:",
            "  - Colecciones líquidas peripancreáticas agudas",
            "  - Pseudoquiste pancreático (>4 semanas)",
            "  - Necrosis pancreática estéril",
            "  - Necrosis pancreática infectada (walled-off necrosis)",
            "  - Pseudoaneurisma arterial",
            "  - Trombosis portal/esplénica",
            "  - Necrosis colónica",
            "SISTÉMICAS:",
            "  - Síndrome de respuesta inflamatoria sistémica (SIRS)",
            "  - Falla orgánica múltiple",
            "  - SDRA",
            "  - Insuficiencia renal aguda",
            "  - CID",
            "  - Shock",
            "  - Muerte",
        ],
        diagnostic_criteria=[
            "DIAGNÓSTICO: ≥2 de 3 criterios:",
            "  1. Dolor abdominal característico",
            "  2. Lipasa o amilasa ≥3x límite superior normal",
            "  3. Hallazgos de imagen compatibles",
            "",
            "LABORATORIO:",
            "  - Lipasa sérica: más específica, permanece elevada más tiempo",
            "  - Amilasa sérica: eleva más rápido, menos específica",
            "  - No correlacionan con severidad",
            "  - Leucocitosis, hemoconcentración",
            "  - Elevación de PCR (pico a las 48-72h)",
            "  - Hipocalcemia, hiperglucemia",
            "  - Alteración de función hepática (si biliar)",
            "",
            "IMAGEN:",
            "  - TAC con contraste: Gold standard para severidad",
            "    (diferir 72-96h si diagnóstico claro para evaluar necrosis)",
            "  - Ecografía: detectar litiasis biliar",
            "  - RM/CPRM: alternativa a TAC, mejor para ver ductos",
            "",
            "CLASIFICACIÓN DE ATLANTA 2012:",
            "  - Leve: sin falla orgánica ni complicaciones locales",
            "  - Moderadamente severa: falla orgánica transitoria (<48h) o complicación local",
            "  - Severa: falla orgánica persistente (>48h)",
            "",
            "SCORES PRONÓSTICOS:",
            "  - BISAP (al ingreso): BUN>25, Alteración mental, SIRS, Edad>60, Derrame pleural",
            "  - APACHE II, Ranson, CTSI",
        ],
        differential_diagnosis=[
            "Úlcera péptica perforada",
            "Colecistitis aguda",
            "Colangitis aguda",
            "Obstrucción intestinal",
            "Isquemia mesentérica",
            "Infarto agudo de miocardio (inferior)",
            "Disección aórtica",
            "Rotura de aneurisma aórtico",
            "Embarazo ectópico",
        ],
        treatment_protocol=[
            "SOPORTE INICIAL (primeras 24-48h críticas):",
            "  - Resucitación hídrica agresiva:",
            "    Ringer lactato 250-500 mL/h (ajustar según respuesta)",
            "    Meta: diuresis >0.5 mL/kg/h, normalizar BUN",
            "  - NPO inicial",
            "  - Analgesia: Morfina o Meperidina (NO contraindicados)",
            "  - Oxígeno si hipoxemia",
            "  - Monitorización estrecha",
            "",
            "NUTRICIÓN:",
            "  - Alimentación enteral temprana (<24-48h) preferida sobre parenteral",
            "  - Iniciar dieta oral si tolera y sin dolor",
            "  - Sonda nasoyeyunal si vómitos persistentes",
            "",
            "MANEJO ETIOLÓGICO:",
            "  - Biliar: CPRE urgente (<24h) si colangitis o ictericia obstructiva",
            "  - Colecistectomía en misma hospitalización si biliar leve",
            "  - Alcohólica: abstinencia, vitaminas B",
            "  - Hipertrigliceridemia: insulina, plasmaféresis si TG >1000-2000",
            "",
            "ANTIBIÓTICOS:",
            "  - NO profilácticos de rutina (incluso en necrosis estéril)",
            "  - Indicados solo si: infección documentada (necrosis infectada, colangitis)",
            "  - Meropenem, Imipenem (buena penetración pancreática)",
            "",
            "NECROSIS INFECTADA:",
            "  - Antibióticos + drenaje",
            "  - Drenaje paso a paso: percutáneo → endoscópico → necrosectomía quirúrgica",
            "  - Diferir intervención >4 semanas si posible",
        ],
        emergency_signs=[
            "Shock (hipotensión, taquicardia, oliguria)",
            "Disnea severa (SDRA)",
            "Abdomen agudo (peritonitis)",
            "Alteración del estado mental",
            "Sangrado gastrointestinal",
            "Síndrome compartimental abdominal",
            "Fiebre alta con deterioro (necrosis infectada)",
        ],
        prognosis="Leve: mortalidad <1%, recuperación completa. Severa: mortalidad 10-30%. Necrosis infectada: mayor morbilidad. Recurrencia si causa no corregida.",
        follow_up=[
            "Control a las 2-4 semanas post-alta",
            "Colecistectomía programada si biliar (idealmente misma hospitalización o <2 sem)",
            "Cesación de alcohol (esencial)",
            "Control de triglicéridos si causa",
            "TAC de control si complicaciones locales",
            "Evaluación de función pancreática exocrina/endocrina si recurrente",
        ],
    ),
    # =========================================================================
    # ENFERMEDAD POR REFLUJO GASTROESOFÁGICO (K21)
    # Fuente: ACG Guidelines GERD 2022, AGA Guidelines
    # =========================================================================
    "K21": MedicalCondition(
        icd10_code="K21",
        name="Enfermedad por Reflujo Gastroesofágico (ERGE)",
        category="Gastrointestinal",
        description="Condición que ocurre cuando el reflujo del contenido gástrico causa síntomas molestos y/o complicaciones. Es uno de los trastornos digestivos más prevalentes",
        symptoms=[
            "SÍNTOMAS TÍPICOS:",
            "  - Pirosis (ardor retroesternal ascendente)",
            "  - Regurgitación ácida",
            "  - Peor postprandial, al acostarse",
            "  - Alivio con antiácidos",
            "",
            "SÍNTOMAS ATÍPICOS (extraesofágicos):",
            "  - Tos crónica (especialmente nocturna)",
            "  - Laringitis (disfonía matutina)",
            "  - Asma de difícil control",
            "  - Erosiones dentales",
            "  - Dolor torácico no cardíaco",
            "  - Globo faríngeo",
            "  - Faringitis recurrente",
            "",
            "SÍNTOMAS DE ALARMA:",
            "  - Disfagia progresiva",
            "  - Odinofagia",
            "  - Pérdida de peso involuntaria",
            "  - Anemia",
            "  - Hematemesis/melena",
        ],
        risk_factors=[
            "Obesidad (principal factor modificable)",
            "Hernia hiatal",
            "Embarazo",
            "Tabaquismo",
            "Alcohol",
            "Comidas copiosas/grasas",
            "Comida tardía/acostarse post-ingesta",
            "Bebidas carbonatadas, café, chocolate, menta",
            "Medicamentos (calcioantagonistas, nitratos, teofilina, AINEs)",
            "Esclerodermia",
            "Gastroparesia",
        ],
        complications=[
            "Esofagitis erosiva (clasificación Los Ángeles A-D)",
            "Estenosis esofágica péptica",
            "Esófago de Barrett (metaplasia intestinal, precáncer)",
            "Adenocarcinoma esofágico",
            "Hemorragia esofágica",
            "Úlcera esofágica",
        ],
        diagnostic_criteria=[
            "DIAGNÓSTICO CLÍNICO (empírico):",
            "  - Síntomas típicos (pirosis, regurgitación)",
            "  - Sin síntomas de alarma",
            "  - Respuesta a prueba terapéutica con IBP",
            "",
            "ENDOSCOPIA INDICADA SI:",
            "  - Síntomas de alarma",
            "  - No respuesta a IBP (8 semanas)",
            "  - Múltiples factores de riesgo para Barrett",
            "  - Síntomas de larga evolución (>5 años)",
            "  - Edad >50 años con síntomas nuevos",
            "",
            "pHMETRÍA/IMPEDANCIOMETRÍA (estándar de referencia):",
            "  - Síntomas refractarios sin esofagitis",
            "  - Pre-cirugía antirreflujo",
            "  - Post-cirugía con síntomas recurrentes",
            "  - Síntomas atípicos sin respuesta a IBP",
            "",
            "CLASIFICACIÓN ENDOSCÓPICA (Los Ángeles):",
            "  - Grado A: erosiones ≤5mm",
            "  - Grado B: erosiones >5mm, no confluentes",
            "  - Grado C: erosiones confluentes <75% circunferencia",
            "  - Grado D: erosiones ≥75% circunferencia",
        ],
        differential_diagnosis=[
            "Enfermedad coronaria",
            "Esofagitis eosinofílica",
            "Esofagitis infecciosa (CMV, Candida, Herpes)",
            "Esofagitis por píldoras",
            "Dispepsia funcional",
            "Acalasia",
            "Espasmo esofágico difuso",
            "Cáncer esofágico o gástrico",
        ],
        treatment_protocol=[
            "MODIFICACIÓN DEL ESTILO DE VIDA:",
            "  - Pérdida de peso si sobrepeso/obesidad",
            "  - Elevar cabecera de la cama 15-20 cm",
            "  - Evitar acostarse <3h post-cena",
            "  - Evitar comidas copiosas/grasas",
            "  - Cesación tabáquica",
            "  - Evitar alcohol",
            "",
            "TRATAMIENTO FARMACOLÓGICO:",
            "  1. IBP (inhibidores de bomba de protones) - primera línea:",
            "     Omeprazol 20mg, Esomeprazol 20mg, Pantoprazol 40mg",
            "     Lansoprazol 30mg, Rabeprazol 20mg - antes del desayuno",
            "     Duración: 4-8 semanas, luego a demanda o dosis mínima efectiva",
            "",
            "  2. Antagonistas H2 (alternativa menor potencia):",
            "     Ranitidina, Famotidina (menos usados actualmente)",
            "",
            "  3. Antiácidos/Alginatos (alivio sintomático rápido):",
            "     Hidróxido de aluminio/magnesio, Gaviscon",
            "",
            "ERGE REFRACTARIA (no respuesta a IBP x 8 sem):",
            "  - Verificar adherencia (30 min antes de comida)",
            "  - IBP 2 veces al día",
            "  - Confirmar diagnóstico: endoscopia, pHmetría",
            "  - Considerar: esofagitis eosinofílica, trastorno funcional",
            "",
            "CIRUGÍA ANTIRREFLUJO (Funduplicatura):",
            "  - Indicada si: respuesta a IBP pero intolerancia o preferencia",
            "  - Síntomas de regurgitación volumétrica",
            "  - Hernia hiatal grande",
        ],
        emergency_signs=[
            "Disfagia completa (impactación alimentaria)",
            "Hematemesis o melena",
            "Dolor torácico severo (descartar SCA)",
            "Pérdida de peso rápida (descartar malignidad)",
            "Odinofagia severa (descartar úlcera/perforación)",
        ],
        prognosis="Crónica pero manejable. 80% responden a IBP. Riesgo de Barrett: 10-15% de ERGE crónica. Riesgo de adenocarcinoma en Barrett: 0.5%/año.",
        follow_up=[
            "Control a las 4-8 semanas de tratamiento",
            "Endoscopia de screening Barrett en ERGE crónica con factores de riesgo",
            "Vigilancia endoscópica si Barrett (cada 1-3 años según displasia)",
            "Intentar reducir a dosis mínima efectiva de IBP",
            "Evaluación de síntomas atípicos que no responden",
        ],
    ),
    # =========================================================================
    # HEMORRAGIA DIGESTIVA ALTA (K92.0)
    # Fuente: ACG Guidelines UGI Bleeding 2021, ESGE Guidelines
    # =========================================================================
    "K92.0": MedicalCondition(
        icd10_code="K92.0",
        name="Hemorragia Digestiva Alta",
        category="Gastrointestinal",
        description="Sangrado gastrointestinal originado proximal al ligamento de Treitz. Causas más frecuentes: úlcera péptica, várices esofágicas, erosiones gastroduodenales, Mallory-Weiss",
        symptoms=[
            "HEMATEMESIS:",
            "  - Vómito de sangre roja fresca (sangrado activo/reciente)",
            "  - Vómito en 'borra de café' (sangre digerida)",
            "MELENA:",
            "  - Heces negras, alquitranadas, malolientes",
            "  - Indica >50-100 mL de sangre en TGI",
            "HEMATOQUECIA:",
            "  - Sangre roja por recto (HDA masiva con tránsito rápido)",
            "",
            "SÍNTOMAS DE HIPOVOLEMIA:",
            "  - Mareos, debilidad",
            "  - Palidez",
            "  - Taquicardia",
            "  - Hipotensión",
            "  - Síncope",
            "  - Alteración mental (shock)",
            "",
            "SÍNTOMAS ASOCIADOS A ETIOLOGÍA:",
            "  - Dolor epigástrico (úlcera)",
            "  - Uso de AINEs/aspirina",
            "  - Alcoholismo, hepatopatía (várices)",
            "  - Vómitos previos intensos (Mallory-Weiss)",
        ],
        risk_factors=[
            "CAUSAS NO VARICOSAS (80%):",
            "  - Úlcera péptica (H. pylori, AINEs)",
            "  - Erosiones gastroduodenales",
            "  - Esofagitis erosiva",
            "  - Mallory-Weiss",
            "  - Neoplasias",
            "  - Lesión de Dieulafoy",
            "  - Malformaciones arteriovenosas",
            "CAUSAS VARICOSAS (20%):",
            "  - Cirrosis hepática",
            "  - Hipertensión portal",
            "FACTORES DE RIESGO DE SANGRADO:",
            "  - AINEs, aspirina, anticoagulantes, antiplaquetarios",
            "  - Infección por H. pylori",
            "  - Edad avanzada",
            "  - Comorbilidades",
            "  - HDA previa",
        ],
        complications=[
            "Shock hipovolémico",
            "Falla multiorgánica",
            "Aspiración",
            "Síndrome coronario agudo (por anemia)",
            "Resangrado",
            "Necesidad de cirugía de emergencia",
            "Muerte (mortalidad 2-10%)",
        ],
        diagnostic_criteria=[
            "EVALUACIÓN INICIAL:",
            "  - ABC (vía aérea, respiración, circulación)",
            "  - Signos vitales, nivel de conciencia",
            "  - Hemograma urgente (puede ser normal inicialmente)",
            "  - Coagulación, función hepática, función renal",
            "  - Grupo y cruzar sangre",
            "",
            "ESTRATIFICACIÓN DE RIESGO:",
            "  Glasgow-Blatchford Score (GBS) - pre-endoscopia:",
            "    BUN, Hemoglobina, PAS, FC, Melena, Síncope, Hepatopatía, IC",
            "    - GBS 0-1: muy bajo riesgo, puede manejarse ambulatorio",
            "    - GBS ≥6: alto riesgo",
            "",
            "  Rockall Score - post-endoscopia:",
            "    Edad, Shock, Comorbilidades, Diagnóstico, Estigmas de sangrado",
            "",
            "ENDOSCOPIA DIGESTIVA ALTA:",
            "  - Diagnóstica y terapéutica",
            "  - Timing:",
            "    • Muy alto riesgo/inestable: <12h (idealmente <6h)",
            "    • Alto riesgo: <24h",
            "    • Bajo riesgo: <72h o ambulatoria",
            "",
            "CLASIFICACIÓN ENDOSCÓPICA FORREST (úlceras):",
            "  - Ia: Sangrado arterial activo - alto riesgo",
            "  - Ib: Sangrado en napa - alto riesgo",
            "  - IIa: Vaso visible no sangrante - alto riesgo",
            "  - IIb: Coágulo adherido - riesgo intermedio",
            "  - IIc: Mancha pigmentada - bajo riesgo",
            "  - III: Base limpia - bajo riesgo",
        ],
        differential_diagnosis=[
            "Hemorragia digestiva baja",
            "Epistaxis deglutida",
            "Hemoptisis",
            "Ingesta de hierro/bismuto (heces oscuras)",
            "Ingesta de remolacha (heces rojizas)",
        ],
        treatment_protocol=[
            "RESUCITACIÓN INICIAL:",
            "  - 2 vías periféricas gruesas (16-18G)",
            "  - Cristaloides (meta PAS >90, FC <100, diuresis >0.5 mL/kg/h)",
            "  - Transfusión si Hb <7 g/dL (umbral <8 en coronarios)",
            "  - Plaquetas si <50,000 con sangrado activo",
            "  - Reversión de anticoagulación si indicado",
            "  - Protección de vía aérea si alteración mental o hematemesis masiva",
            "",
            "TRATAMIENTO FARMACOLÓGICO PRE-ENDOSCOPIA:",
            "  - IBP IV en bolo + infusión (Omeprazol 80mg bolo, luego 8mg/h x 72h)",
            "    (o 40mg c/12h si no infusión disponible)",
            "  - Procinético: Eritromicina 250mg IV 30-90 min pre-EGD (mejora visualización)",
            "",
            "SANGRADO VARICOSO (sospecha o confirmado):",
            "  - Terlipresina 2mg IV c/4h o Octreótido 50μg bolo + 50μg/h",
            "  - Antibióticos profilácticos: Ceftriaxona 1g/día x 7 días",
            "",
            "TRATAMIENTO ENDOSCÓPICO:",
            "  - Sangrado no varicoso: inyección (adrenalina), clips, termocoagulación",
            "  - Sangrado varicoso: ligadura con bandas (elección), escleroterapia",
            "  - Hemospray/polvos hemostáticos",
            "",
            "POST-ENDOSCOPIA:",
            "  - IBP oral dosis alta x 8-12 semanas",
            "  - Erradicación H. pylori si positivo",
            "  - Suspender/evaluar AINEs, anticoagulantes",
            "",
            "FRACASO ENDOSCÓPICO/RESANGRADO:",
            "  - Segunda endoscopia",
            "  - Angioembolización",
            "  - Cirugía",
            "  - TIPS si sangrado varicoso refractario",
        ],
        emergency_signs=[
            "Hematemesis masiva con inestabilidad",
            "Shock hipovolémico (PAS <90, FC >120, palidez, sudoración)",
            "Síncope",
            "Alteración del estado mental",
            "Sangrado activo con caída de hemoglobina",
            "Signos de aspiración",
        ],
        prognosis="Mortalidad global 2-10%. Mayor en: edad avanzada, comorbilidades, sangrado varicoso, resangrado, necesidad de cirugía. La mayoría cesa espontáneamente.",
        follow_up=[
            "Control de hemoglobina post-estabilización",
            "Endoscopia de control a las 6-8 semanas (si úlcera gástrica, para biopsias y confirmar cicatrización)",
            "Test de H. pylori y erradicación",
            "Evaluación de necesidad de anticoagulación/AINEs",
            "Prevención secundaria con IBP si factores de riesgo persistentes",
            "Profilaxis secundaria de várices (betabloqueadores, ligadura programada)",
        ],
    ),
    # =========================================================================
    # OBSTRUCCIÓN INTESTINAL (K56)
    # Fuente: WSES Guidelines, ACG Guidelines
    # =========================================================================
    "K56": MedicalCondition(
        icd10_code="K56",
        name="Obstrucción Intestinal",
        category="Gastrointestinal",
        description="Interrupción mecánica o funcional del tránsito intestinal. Puede ser completa o parcial, de intestino delgado (más frecuente) o grueso",
        symptoms=[
            "SÍNTOMAS CARDINALES:",
            "  - Dolor abdominal cólico (intermitente)",
            "  - Distensión abdominal",
            "  - Náuseas y vómitos:",
            "    • Precoces y biliosos (obstrucción alta)",
            "    • Tardíos y fecaloides (obstrucción baja)",
            "  - Ausencia de evacuación de gases y heces (obstrucción completa)",
            "",
            "EXPLORACIÓN FÍSICA:",
            "  - Distensión abdominal",
            "  - Timpanismo",
            "  - Ruidos hidroaéreos de lucha (metálicos, incrementados)",
            "  - Silencio abdominal (íleo o necrosis)",
            "  - Cicatrices quirúrgicas",
            "  - Hernias (inguinal, femoral, umbilical)",
            "  - Masas abdominales",
            "  - Tacto rectal: ampolla vacía, masa, sangre",
        ],
        risk_factors=[
            "INTESTINO DELGADO (80% de obstrucciones):",
            "  - Adherencias post-quirúrgicas (60-75%)",
            "  - Hernias (inguinal, femoral, incisional)",
            "  - Neoplasias",
            "  - Enfermedad de Crohn",
            "  - Bezoares",
            "  - Cuerpos extraños",
            "  - Intususcepción",
            "  - Vólvulo",
            "INTESTINO GRUESO:",
            "  - Neoplasias (60%)",
            "  - Vólvulo (sigmoide, cecal)",
            "  - Diverticulitis",
            "  - Impactación fecal",
            "  - Hernias",
        ],
        complications=[
            "Deshidratación y alteraciones electrolíticas",
            "Estrangulación (compromiso vascular)",
            "Necrosis intestinal",
            "Perforación",
            "Peritonitis",
            "Sepsis",
            "Shock",
            "Falla multiorgánica",
            "Muerte",
        ],
        diagnostic_criteria=[
            "RADIOGRAFÍA SIMPLE DE ABDOMEN:",
            "  - Niveles hidroaéreos múltiples",
            "  - Dilatación de asas (ID >3cm, colon >6cm, ciego >9cm)",
            "  - Signo de 'pila de monedas' (válvulas conniventes)",
            "  - Ausencia de gas en recto",
            "",
            "TAC ABDOMEN CON CONTRASTE (estándar):",
            "  - Punto de transición",
            "  - Causa de obstrucción",
            "  - Signos de estrangulación:",
            "    • Engrosamiento de pared",
            "    • Falta de realce mucoso",
            "    • Líquido libre",
            "    • Signo del remolino (vólvulo)",
            "    • Neumatosis intestinal",
            "",
            "LABORATORIO:",
            "  - Leucocitosis (más elevada si estrangulación)",
            "  - Lactato elevado (isquemia)",
            "  - Alteraciones electrolíticas (hipopotasemia, alcalosis)",
            "  - Elevación de creatinina (deshidratación)",
            "",
            "CLASIFICACIÓN:",
            "  - Parcial vs. Completa",
            "  - Simple vs. Estrangulada",
            "  - Alta vs. Baja",
        ],
        differential_diagnosis=[
            "Íleo paralítico (pseudo-obstrucción)",
            "Síndrome de Ogilvie",
            "Gastroparesia",
            "Impactación fecal",
            "Apendicitis",
            "Diverticulitis",
            "Pancreatitis aguda",
            "Isquemia mesentérica",
            "Cólico renal",
        ],
        treatment_protocol=[
            "MANEJO INICIAL (todas las obstrucciones):",
            "  - NPO",
            "  - SNG a derivación (descompresión)",
            "  - Reposición de líquidos y electrolitos IV",
            "  - Sonda vesical (monitoreo de diuresis)",
            "  - Analgesia",
            "",
            "OBSTRUCCIÓN DE INTESTINO DELGADO POR ADHERENCIAS:",
            "  - Manejo conservador inicial (48-72h) si:",
            "    • Obstrucción parcial",
            "    • Sin signos de estrangulación",
            "    • Sin cirugía reciente",
            "  - Contraste hidrosoluble (Gastrografin):",
            "    • Diagnóstico (si llega a colon en 24h → resolución probable)",
            "    • Puede ser terapéutico (efecto osmótico)",
            "",
            "CIRUGÍA URGENTE/EMERGENTE indicada si:",
            "  - Signos de estrangulación o peritonitis",
            "  - Hernia incarcerada/estrangulada",
            "  - Obstrucción completa sin mejoría en 48-72h",
            "  - Obstrucción de asa cerrada",
            "  - Neumatosis intestinal o gas portal",
            "",
            "OBSTRUCCIÓN DE INTESTINO GRUESO:",
            "  - Evaluación oncológica si neoplasia",
            "  - Stent endoscópico como puente a cirugía (si indicado)",
            "  - Cirugía: resección, colostomía/ileostomía",
            "",
            "VÓLVULO DE SIGMOIDES:",
            "  - Descompresión endoscópica inicial (si viable)",
            "  - Sigmoidectomía electiva/urgente",
        ],
        emergency_signs=[
            "Signos de ESTRANGULACIÓN:",
            "  - Dolor abdominal continuo (no cólico)",
            "  - Fiebre >38°C",
            "  - Taquicardia persistente",
            "  - Leucocitosis marcada",
            "  - Acidosis metabólica/lactato elevado",
            "  - Signos peritoneales (defensa, rebote)",
            "  - Deterioro clínico",
            "Obstrucción de asa cerrada",
            "Neumatosis intestinal",
        ],
        prognosis="Sin estrangulación: buen pronóstico. Con estrangulación: mortalidad 10-30%. Recurrencia de obstrucción por adherencias: 10-30%.",
        follow_up=[
            "Control post-quirúrgico según procedimiento",
            "Dieta progresiva con resolución del íleo",
            "Evaluación oncológica si neoplasia",
            "Prevención de adherencias (membrana anti-adherencia en cirugía)",
            "Educación sobre signos de recurrencia",
        ],
    ),
    # =========================================================================
    # CIRROSIS HEPÁTICA (K74)
    # Fuente: AASLD Guidelines, EASL Guidelines
    # =========================================================================
    "K74": MedicalCondition(
        icd10_code="K74",
        name="Cirrosis Hepática",
        category="Gastrointestinal",
        description="Estadio avanzado de fibrosis hepática con distorsión de la arquitectura hepática, nódulos de regeneración e hipertensión portal. Representa la vía final común de múltiples hepatopatías crónicas",
        symptoms=[
            "CIRROSIS COMPENSADA (puede ser asintomática):",
            "  - Fatiga",
            "  - Debilidad",
            "  - Pérdida de peso",
            "  - Anorexia",
            "  - Molestia en hipocondrio derecho",
            "",
            "CIRROSIS DESCOMPENSADA:",
            "  - Ictericia",
            "  - Ascitis (distensión abdominal)",
            "  - Edema de miembros inferiores",
            "  - Encefalopatía hepática (confusión, asterixis)",
            "  - Hemorragia digestiva (várices)",
            "",
            "SIGNOS FÍSICOS:",
            "  - Hepatomegalia (inicial) o hígado pequeño (avanzado)",
            "  - Esplenomegalia",
            "  - Eritema palmar",
            "  - Arañas vasculares (telangiectasias)",
            "  - Ginecomastia",
            "  - Atrofia testicular",
            "  - Pérdida de vello corporal",
            "  - Uñas de Muehrcke, uñas de Terry",
            "  - Contractura de Dupuytren (alcohólica)",
            "  - Circulación colateral abdominal (cabeza de medusa)",
            "  - Fetor hepático",
        ],
        risk_factors=[
            "ETIOLOGÍA:",
            "  - Alcohol (30-40%)",
            "  - Hepatitis C crónica (25-30%)",
            "  - Enfermedad hepática grasa no alcohólica/MASH (20-25%)",
            "  - Hepatitis B crónica",
            "  - Hepatitis autoinmune",
            "  - Colangitis biliar primaria",
            "  - Colangitis esclerosante primaria",
            "  - Hemocromatosis",
            "  - Enfermedad de Wilson",
            "  - Déficit de alfa-1 antitripsina",
            "  - Cirrosis biliar secundaria",
            "  - Cirrosis cardíaca",
            "  - Cirrosis criptogénica",
        ],
        complications=[
            "HIPERTENSIÓN PORTAL y sus consecuencias:",
            "  - Várices esofágicas y gástricas (hemorragia)",
            "  - Ascitis",
            "  - Síndrome hepatorrenal",
            "  - Encefalopatía hepática",
            "  - Peritonitis bacteriana espontánea (PBE)",
            "  - Esplenomegalia e hiperesplenismo",
            "OTRAS:",
            "  - Carcinoma hepatocelular (riesgo 1-8%/año)",
            "  - Síndrome hepatopulmonar",
            "  - Hipertensión portopulmonar",
            "  - Coagulopatía",
            "  - Desnutrición",
            "  - Osteoporosis",
        ],
        diagnostic_criteria=[
            "DIAGNÓSTICO:",
            "  - Biopsia hepática (gold standard, no siempre necesaria)",
            "  - Hallazgos clínicos + imagen + laboratorio",
            "",
            "LABORATORIO:",
            "  - Transaminasas: normales o elevadas",
            "  - Fosfatasa alcalina y GGT elevadas",
            "  - Bilirrubina elevada (descompensada)",
            "  - Albúmina baja (<3.5 g/dL)",
            "  - Tiempo de protrombina/INR prolongado",
            "  - Plaquetas bajas (<150,000 - hiperesplenismo)",
            "  - Globulinas elevadas",
            "",
            "IMAGEN:",
            "  - Ecografía: hígado nodular, heterogéneo, esplenomegalia, ascitis",
            "  - Elastografía hepática (Fibroscan): >12-14 kPa sugiere cirrosis",
            "  - TAC/RM: nódulos, signos de hipertensión portal",
            "",
            "ENDOSCOPIA:",
            "  - Screening de várices esofágicas",
            "",
            "CLASIFICACIÓN DE CHILD-PUGH:",
            "  Parámetros: Bilirrubina, Albúmina, INR, Ascitis, Encefalopatía",
            "  - Clase A (5-6 puntos): compensada, buena función",
            "  - Clase B (7-9 puntos): compromiso moderado",
            "  - Clase C (10-15 puntos): descompensada, mala función",
            "",
            "SCORE MELD:",
            "  - Bilirrubina, INR, Creatinina",
            "  - Predictor de mortalidad a 90 días",
            "  - Usado para priorización de trasplante",
        ],
        differential_diagnosis=[
            "Insuficiencia cardíaca derecha",
            "Pericarditis constrictiva",
            "Síndrome de Budd-Chiari",
            "Carcinomatosis peritoneal",
            "Síndrome nefrótico",
            "Tuberculosis peritoneal",
        ],
        treatment_protocol=[
            "MANEJO ETIOLÓGICO:",
            "  - Abstinencia absoluta de alcohol",
            "  - Tratamiento de hepatitis B/C",
            "  - Control de síndrome metabólico (MASH)",
            "  - Tratamiento de hepatitis autoinmune",
            "  - Quelación de hierro (hemocromatosis)",
            "",
            "MANEJO DE COMPLICACIONES:",
            "",
            "VÁRICES ESOFÁGICAS:",
            "  - Profilaxis primaria: betabloqueadores no selectivos (propranolol, carvedilol)",
            "    o ligadura endoscópica si várices grandes o manchas rojas",
            "  - Hemorragia aguda: resucitación + octreótido/terlipresina + ligadura urgente",
            "",
            "ASCITIS:",
            "  - Restricción de sodio (<2g/día)",
            "  - Diuréticos: Espironolactona 100mg + Furosemida 40mg (ratio 100:40)",
            "  - Paracentesis evacuadora si ascitis a tensión (+ albúmina si >5L)",
            "  - TIPS si refractaria",
            "",
            "PERITONITIS BACTERIANA ESPONTÁNEA:",
            "  - Ceftriaxona 2g/día o Cefotaxima IV x 5 días",
            "  - Albúmina IV día 1 y 3",
            "  - Profilaxis secundaria: Norfloxacino 400mg/día",
            "",
            "ENCEFALOPATÍA HEPÁTICA:",
            "  - Identificar y tratar precipitantes",
            "  - Lactulosa 15-30mL c/8h (meta: 2-3 deposiciones blandas/día)",
            "  - Rifaximina 550mg c/12h (prevención de recurrencia)",
            "",
            "SCREENING DE HEPATOCARCINOMA:",
            "  - Ecografía + AFP cada 6 meses",
            "",
            "TRASPLANTE HEPÁTICO:",
            "  - Cirrosis descompensada (MELD ≥15)",
            "  - Hepatocarcinoma dentro de criterios de Milán",
        ],
        emergency_signs=[
            "Hemorragia digestiva por várices",
            "Encefalopatía hepática grado III-IV (coma)",
            "Peritonitis bacteriana espontánea",
            "Síndrome hepatorrenal",
            "Sepsis",
            "Falla hepática aguda sobre crónica (ACLF)",
        ],
        prognosis="Variable según estadio. Child A: supervivencia a 5 años 80-90%. Child C: supervivencia a 1 año 35-45%. MELD predice mortalidad a corto plazo. Trasplante puede ser curativo.",
        follow_up=[
            "Child A: control cada 6 meses",
            "Child B-C: control cada 3 meses o más frecuente",
            "Endoscopia de screening: al diagnóstico, luego según hallazgos",
            "Ecografía + AFP cada 6 meses (HCC)",
            "Evaluación para trasplante hepático si indicado",
            "Vacunación (hepatitis A y B, influenza, neumococo)",
            "Evitar nefrotóxicos, sedantes, AINEs",
        ],
    ),
}


def get_all_gastrointestinal_conditions():
    """Retorna todas las condiciones gastrointestinales"""
    return GASTROINTESTINAL_CONDITIONS


def get_condition(icd10_code: str):
    """Obtiene una condición específica por código ICD-10"""
    return GASTROINTESTINAL_CONDITIONS.get(icd10_code)
