#!/usr/bin/env python3
"""
🫁 Condiciones Respiratorias - Base de Conocimiento Expandida
Basado en: ICD-10-CM 2026, GOLD 2024, GINA 2024, ATS/IDSA Guidelines

Cobertura:
- Neumonía Adquirida en Comunidad (J18) ✓ existente
- EPOC (J44) ✓ nuevo
- Asma Bronquial (J45) ✓ nuevo
- Infección Respiratoria Aguda Superior (J06) ✓ nuevo
- Insuficiencia Respiratoria (J96) ✓ nuevo
- Bronquitis Aguda (J20) ✓ nuevo
- COVID-19 Respiratorio (U07.1) ✓ nuevo
- Derrame Pleural (J90) ✓ nuevo
- Neumotórax (J93) ✓ nuevo
"""

from dataclasses import dataclass
from typing import List

try:
    from medical_knowledge_base import MedicalCondition
except ImportError:

    @dataclass
    class MedicalCondition:
        """Condición médica completa"""

        icd10_code: str
        name: str
        category: str
        description: str
        symptoms: List[str]
        risk_factors: List[str]
        complications: List[str]
        diagnostic_criteria: List[str]
        differential_diagnosis: List[str]
        treatment_protocol: List[str]
        emergency_signs: List[str]
        prognosis: str
        follow_up: List[str]


RESPIRATORY_CONDITIONS = {
    # =========================================================================
    # EPOC - ENFERMEDAD PULMONAR OBSTRUCTIVA CRÓNICA (J44)
    # Fuente: GOLD 2024 (Global Initiative for Chronic Obstructive Lung Disease)
    # =========================================================================
    "J44": MedicalCondition(
        icd10_code="J44",
        name="Enfermedad Pulmonar Obstructiva Crónica (EPOC)",
        category="Respiratorio",
        description="Enfermedad pulmonar prevenible y tratable caracterizada por síntomas respiratorios persistentes y limitación del flujo aéreo debido a anormalidades de vías aéreas y/o alveolares",
        symptoms=[
            "Disnea progresiva (síntoma cardinal)",
            "Tos crónica (puede ser intermitente o diaria)",
            "Expectoración crónica",
            "Sibilancias",
            "Opresión torácica",
            "Fatiga",
            "Pérdida de peso (en estadios avanzados)",
            "Edema de miembros inferiores (cor pulmonale)",
            "Cianosis (en casos severos)",
            "Uso de músculos accesorios",
        ],
        risk_factors=[
            "Tabaquismo (>90% de casos)",
            "Exposición a humo de biomasa",
            "Exposición ocupacional (polvos, químicos)",
            "Contaminación ambiental",
            "Déficit de alfa-1 antitripsina",
            "Antecedente de tuberculosis",
            "Asma crónica no tratada",
            "Bajo peso al nacer/infecciones respiratorias en infancia",
            "Historia de infecciones respiratorias frecuentes",
        ],
        complications=[
            "Exacerbaciones agudas (principal causa de morbimortalidad)",
            "Insuficiencia respiratoria crónica",
            "Cor pulmonale (insuficiencia cardíaca derecha)",
            "Hipertensión pulmonar",
            "Neumotórax",
            "Cáncer de pulmón (riesgo aumentado)",
            "Depresión y ansiedad",
            "Osteoporosis",
            "Caquexia",
            "Policitemia secundaria",
        ],
        diagnostic_criteria=[
            "ESPIROMETRÍA POST-BRONCODILATADOR (obligatoria):",
            "  - FEV1/FVC <0.70 confirma obstrucción persistente",
            "CLASIFICACIÓN DE SEVERIDAD (GOLD 1-4 por FEV1):",
            "  - GOLD 1 (Leve): FEV1 ≥80% predicho",
            "  - GOLD 2 (Moderada): 50% ≤ FEV1 < 80%",
            "  - GOLD 3 (Severa): 30% ≤ FEV1 < 50%",
            "  - GOLD 4 (Muy severa): FEV1 <30%",
            "EVALUACIÓN COMBINADA ABE (síntomas + exacerbaciones):",
            "  - mMRC o CAT para síntomas",
            "  - Historia de exacerbaciones (≥2 moderadas o ≥1 hospitalización)",
            "ESTUDIOS COMPLEMENTARIOS:",
            "  - Rx tórax: hiperinsuflación, aplanamiento diafragmático",
            "  - Gasometría arterial si FEV1 <50% o signos de hipoxemia",
            "  - Alfa-1 antitripsina si <45 años o historia familiar",
        ],
        differential_diagnosis=[
            "Asma bronquial",
            "Insuficiencia cardíaca",
            "Bronquiectasias",
            "Tuberculosis",
            "Cáncer de pulmón",
            "Fibrosis pulmonar",
            "Tos crónica por otros medicamentos (IECA)",
        ],
        treatment_protocol=[
            "CESACIÓN TABÁQUICA (lo más importante):",
            "  - Consejería + farmacoterapia (vareniclina, bupropión, TRN)",
            "TRATAMIENTO FARMACOLÓGICO ESCALONADO:",
            "  Grupo A (pocos síntomas, bajo riesgo):",
            "    - Broncodilatador según necesidad (SABA o SAMA)",
            "  Grupo B (más síntomas, bajo riesgo):",
            "    - LABA o LAMA de mantenimiento",
            "    - Si persisten síntomas: LABA + LAMA",
            "  Grupo E (exacerbaciones):",
            "    - LABA + LAMA inicial",
            "    - Si eosinófilos ≥300: LABA + LAMA + ICS",
            "BRONCODILATADORES:",
            "  - LABA: Formoterol, Salmeterol, Indacaterol, Olodaterol",
            "  - LAMA: Tiotropio, Glicopirronio, Umeclidinio, Aclidinio",
            "  - Combinaciones: Tiotropio-Olodaterol, Umeclidinio-Vilanterol",
            "ICS (si eosinófilos elevados y exacerbaciones):",
            "  - Budesonida, Fluticasona (en combinación con LABA)",
            "OXIGENOTERAPIA:",
            "  - Si PaO2 ≤55 mmHg o SatO2 ≤88% en reposo",
            "REHABILITACIÓN PULMONAR (altamente efectiva)",
            "VACUNACIÓN: Influenza anual, Neumococo",
        ],
        emergency_signs=[
            "EXACERBACIÓN SEVERA:",
            "  - Disnea en reposo",
            "  - Frecuencia respiratoria >30/min",
            "  - SatO2 <90%",
            "  - Uso de músculos accesorios marcado",
            "  - Cianosis de nueva aparición",
            "  - Alteración del estado mental",
            "  - Edemas periféricos de nueva aparición",
            "  - Inestabilidad hemodinámica",
        ],
        prognosis="Variable según severidad. FEV1 y frecuencia de exacerbaciones son principales predictores. Índice BODE (BMI, Obstrucción, Disnea, Ejercicio) para pronóstico.",
        follow_up=[
            "Control cada 3-12 meses según severidad",
            "Espirometría anual",
            "Evaluación de técnica inhalatoria en cada visita",
            "Monitoreo de exacerbaciones",
            "Evaluación de síntomas (CAT, mMRC)",
            "Screening de comorbilidades (CV, osteoporosis, depresión)",
            "Vacunación anual influenza",
        ],
    ),
    # =========================================================================
    # ASMA BRONQUIAL (J45)
    # Fuente: GINA 2024 (Global Initiative for Asthma)
    # =========================================================================
    "J45": MedicalCondition(
        icd10_code="J45",
        name="Asma Bronquial",
        category="Respiratorio",
        description="Enfermedad inflamatoria crónica de las vías aéreas con hiperreactividad bronquial y obstrucción reversible del flujo aéreo",
        symptoms=[
            "Disnea episódica",
            "Sibilancias (especialmente espiratorias)",
            "Tos seca o productiva",
            "Opresión torácica",
            "Síntomas empeoran:",
            "  - Por la noche o madrugada",
            "  - Con ejercicio",
            "  - Con exposición a alérgenos o irritantes",
            "  - Con infecciones respiratorias",
            "  - Con cambios de clima",
            "Variabilidad de síntomas",
            "Síntomas mejoran con broncodilatadores",
        ],
        risk_factors=[
            "Atopia personal o familiar (rinitis, eczema)",
            "Historia familiar de asma",
            "Exposición a alérgenos (ácaros, polen, mascotas, hongos)",
            "Exposición a humo de tabaco",
            "Contaminación ambiental",
            "Infecciones respiratorias virales en infancia",
            "Obesidad",
            "Exposición ocupacional",
            "Sexo masculino en infancia, femenino en adultos",
        ],
        complications=[
            "Exacerbaciones severas (crisis asmática)",
            "Remodelación de vía aérea (asma crónica)",
            "Insuficiencia respiratoria",
            "Neumotórax (raro)",
            "Status asmático",
            "Efectos secundarios de corticoides sistémicos crónicos",
            "Muerte por asma (prevenible)",
        ],
        diagnostic_criteria=[
            "HISTORIA CLÍNICA:",
            "  - Síntomas respiratorios variables (sibilancias, disnea, tos, opresión)",
            "  - Más de un síntoma",
            "  - Síntomas varían en intensidad y tiempo",
            "  - Empeoran por noche/madrugada, con ejercicio, alérgenos, infecciones",
            "DEMOSTRACIÓN DE OBSTRUCCIÓN VARIABLE:",
            "  - Espirometría: FEV1/FVC reducido con:",
            "    Reversibilidad: aumento FEV1 ≥12% y ≥200mL post-broncodilatador",
            "  - Variabilidad del PEF diurno >10% en adultos",
            "  - Test de provocación bronquial positivo (metacolina, ejercicio)",
            "CLASIFICACIÓN DE CONTROL:",
            "  - Bien controlada: síntomas diurnos ≤2/sem, nocturnos 0, rescate ≤2/sem, sin limitación",
            "  - Parcialmente controlada: 1-2 de los anteriores presentes",
            "  - No controlada: ≥3 de los anteriores presentes",
            "CLASIFICACIÓN DE SEVERIDAD (retrospectiva por tratamiento necesario):",
            "  - Leve, Moderada, Severa",
        ],
        differential_diagnosis=[
            "EPOC",
            "Disfunción de cuerdas vocales",
            "Insuficiencia cardíaca",
            "Bronquiectasias",
            "Fibrosis quística",
            "ERGE con síntomas respiratorios",
            "Rinosinusitis con goteo post-nasal",
            "Tos inducida por fármacos (IECA)",
            "Hiperventilación/ansiedad",
        ],
        treatment_protocol=[
            "GINA 2024 - ENFOQUE BASADO EN TRACKS:",
            "TRACK 1 (preferido): ICS-Formoterol como mantenimiento y rescate (MART)",
            "TRACK 2 (alternativo): ICS mantenimiento + SABA rescate",
            "",
            "ESCALONES DE TRATAMIENTO (Track 1 preferido):",
            "  Paso 1-2: ICS-Formoterol a demanda (asma leve)",
            "  Paso 3: ICS-Formoterol dosis baja diario",
            "  Paso 4: ICS-Formoterol dosis media",
            "  Paso 5: Agregar LAMA, considerar biológicos",
            "",
            "MEDICAMENTOS:",
            "  ICS: Budesonida, Beclometasona, Fluticasona, Ciclesonida",
            "  LABA: Formoterol, Salmeterol, Vilanterol",
            "  LAMA: Tiotropio (add-on en asma severa)",
            "  Combinaciones: Budesonida-Formoterol, Fluticasona-Salmeterol",
            "  Biológicos (asma severa): Omalizumab, Mepolizumab, Benralizumab, Dupilumab",
            "",
            "TRATAMIENTO NO FARMACOLÓGICO:",
            "  - Evitar desencadenantes",
            "  - Educación y plan de acción escrito",
            "  - Técnica de inhalación correcta",
            "  - Control de comorbilidades (rinitis, ERGE)",
            "",
            "NUNCA USAR SABA SOLO SIN ICS (aumenta riesgo de exacerbaciones)",
        ],
        emergency_signs=[
            "EXACERBACIÓN SEVERA/CRISIS ASMÁTICA:",
            "  - Disnea en reposo, habla con palabras",
            "  - FR >30/min",
            "  - FC >120/min",
            "  - SatO2 <90%",
            "  - PEF <50% del predicho o mejor personal",
            "  - Uso de músculos accesorios",
            "  - Agitación, confusión, somnolencia",
            "  - Tórax silente (muy grave)",
            "  - Cianosis",
            "  - Incapacidad para hablar frases",
        ],
        prognosis="Excelente con tratamiento adecuado. La mayoría de pacientes pueden lograr buen control. Mortalidad por asma ha disminuido pero sigue siendo prevenible.",
        follow_up=[
            "Control 1-3 meses después de inicio/cambio de tratamiento",
            "Luego cada 3-12 meses según control",
            "Espirometría al diagnóstico, 3-6 meses post-inicio, luego periódica",
            "Evaluación de control en cada visita",
            "Revisión de técnica inhalatoria y adherencia",
            "Actualización de plan de acción",
            "Considerar reducir escalón si control por ≥3 meses",
        ],
    ),
    # =========================================================================
    # INFECCIÓN RESPIRATORIA AGUDA SUPERIOR (J06)
    # Fuente: IDSA Guidelines, UpToDate
    # =========================================================================
    "J06": MedicalCondition(
        icd10_code="J06",
        name="Infección Respiratoria Aguda de Vías Superiores",
        category="Respiratorio",
        description="Infección aguda, generalmente viral, que afecta nariz, faringe, laringe y senos paranasales. Incluye resfriado común, faringitis viral y rinosinusitis aguda viral",
        symptoms=[
            "Rinorrea (inicialmente hialina, puede tornarse mucopurulenta)",
            "Congestión nasal",
            "Estornudos",
            "Odinofagia (dolor de garganta)",
            "Tos seca o productiva",
            "Febrícula o fiebre leve",
            "Cefalea",
            "Malestar general",
            "Mialgias leves",
            "Disfonía (si laringitis)",
            "Otalgia (referida o por otitis)",
        ],
        risk_factors=[
            "Contacto con personas infectadas",
            "Estaciones frías (otoño-invierno)",
            "Niños en edad escolar",
            "Trabajadores de salud/educación",
            "Tabaquismo",
            "Hacinamiento",
            "Inmunosupresión",
            "Estrés crónico y falta de sueño",
        ],
        complications=[
            "Sinusitis bacteriana secundaria",
            "Otitis media aguda",
            "Exacerbación de asma/EPOC",
            "Neumonía (raro, más en ancianos/inmunosuprimidos)",
            "Convulsiones febriles (niños)",
        ],
        diagnostic_criteria=[
            "DIAGNÓSTICO CLÍNICO (no requiere estudios):",
            "  - Síntomas de inicio agudo",
            "  - Duración típica 7-10 días",
            "  - Ausencia de signos de alarma",
            "CUANDO SOSPECHAR INFECCIÓN BACTERIANA:",
            "  - Síntomas >10 días sin mejoría",
            "  - Síntomas severos: fiebre alta ≥39°C, rinorrea purulenta o dolor facial ≥3 días",
            "  - Empeoramiento tras mejoría inicial (doble enfermar)",
            "CRITERIOS DE CENTOR MODIFICADO (faringitis estreptocócica):",
            "  - Fiebre >38°C (+1)",
            "  - Ausencia de tos (+1)",
            "  - Adenopatía cervical anterior (+1)",
            "  - Exudado amigdalino (+1)",
            "  - Edad 3-14 años (+1), 15-44 años (0), ≥45 años (-1)",
            "  - Score ≥3: considerar test rápido/cultivo",
        ],
        differential_diagnosis=[
            "Rinitis alérgica",
            "Influenza (inicio más abrupto, mialgias severas)",
            "COVID-19",
            "Faringitis estreptocócica",
            "Mononucleosis infecciosa",
            "Sinusitis bacteriana",
            "Cuerpo extraño nasal (niños)",
        ],
        treatment_protocol=[
            "TRATAMIENTO SINTOMÁTICO (antibióticos NO indicados):",
            "  - Hidratación abundante",
            "  - Reposo relativo",
            "  - Analgésicos/antipiréticos: Paracetamol 500-1000mg c/6-8h",
            "    o Ibuprofeno 400mg c/6-8h",
            "  - Descongestionantes nasales tópicos (máximo 3-5 días):",
            "    Oximetazolina, Xilometazolina",
            "  - Lavados nasales con solución salina",
            "  - Miel para tos (>1 año de edad)",
            "  - Dextrometorfano si tos muy molesta",
            "",
            "ANTIBIÓTICOS SOLO SI:",
            "  - Faringitis con alta sospecha de S. pyogenes (Centor ≥4):",
            "    Amoxicilina 500mg c/8h x 10 días, o Penicilina V",
            "  - Sinusitis bacteriana confirmada o alta sospecha:",
            "    Amoxicilina-Clavulánico 875/125mg c/12h x 5-7 días",
            "",
            "EDUCACIÓN:",
            "  - Curso natural de 7-10 días",
            "  - Los antibióticos NO acortan evolución de IRA viral",
            "  - Signos de alarma para reconsultar",
        ],
        emergency_signs=[
            "Dificultad respiratoria",
            "Estridor (posible epiglotitis)",
            "Incapacidad para tragar/babeo",
            "Rigidez de nuca (meningitis)",
            "Fiebre muy alta >40°C persistente",
            "Deterioro rápido del estado general",
            "Edema facial o periorbitario (complicación sinusal)",
        ],
        prognosis="Excelente. Autolimitada en 7-10 días. La mayoría de complicaciones son evitables con seguimiento adecuado.",
        follow_up=[
            "No requiere seguimiento rutinario",
            "Reconsultar si:",
            "  - Síntomas >10 días sin mejoría",
            "  - Empeoramiento después de mejoría inicial",
            "  - Aparición de signos de alarma",
            "  - Fiebre persistente >3 días",
        ],
    ),
    # =========================================================================
    # INSUFICIENCIA RESPIRATORIA (J96)
    # Fuente: ATS/ERS Guidelines, ARDS Network
    # =========================================================================
    "J96": MedicalCondition(
        icd10_code="J96",
        name="Insuficiencia Respiratoria Aguda",
        category="Respiratorio",
        description="Incapacidad del sistema respiratorio para mantener un intercambio gaseoso adecuado, resultando en hipoxemia y/o hipercapnia",
        symptoms=[
            "Disnea severa",
            "Taquipnea (FR >30/min)",
            "Uso de músculos accesorios",
            "Aleteo nasal",
            "Tiraje intercostal/supraclavicular",
            "Cianosis central y periférica",
            "Taquicardia",
            "Alteración del estado mental (agitación, confusión, somnolencia)",
            "Diaforesis",
            "Incapacidad para hablar frases completas",
            "Posición de trípode",
        ],
        risk_factors=[
            "EPOC exacerbado",
            "Neumonía severa",
            "Asma severa (status asmático)",
            "SDRA (sepsis, aspiración, trauma)",
            "Edema pulmonar cardiogénico",
            "Embolia pulmonar masiva",
            "Neumotórax a tensión",
            "Enfermedades neuromusculares",
            "Sobredosis de sedantes/opioides",
            "Obesidad mórbida (hipoventilación)",
            "Traumatismo torácico",
        ],
        complications=[
            "Paro cardiorrespiratorio",
            "Daño hipóxico cerebral",
            "Falla multiorgánica",
            "Neumonía asociada a ventilación mecánica",
            "Barotrauma (en ventilación mecánica)",
            "Tromboembolismo venoso (inmovilización)",
            "Delirium en UCI",
            "Debilidad adquirida en UCI",
            "Muerte",
        ],
        diagnostic_criteria=[
            "GASOMETRÍA ARTERIAL (diagnóstico definitivo):",
            "TIPO I (Hipoxémica):",
            "  - PaO2 <60 mmHg (o SatO2 <90%) respirando aire ambiente",
            "  - PaCO2 normal o baja",
            "  - Causas: neumonía, SDRA, edema pulmonar, TEP",
            "TIPO II (Hipercápnica):",
            "  - PaCO2 >50 mmHg con pH <7.35",
            "  - PaO2 puede estar baja",
            "  - Causas: EPOC, sobredosis, neuromusculares",
            "ÍNDICES DE SEVERIDAD:",
            "  - PaO2/FiO2 (índice Kirby):",
            "    >400: Normal",
            "    200-300: SDRA leve",
            "    100-200: SDRA moderado",
            "    <100: SDRA severo",
            "  - Gradiente A-a de O2",
            "EVALUACIÓN INICIAL:",
            "  - ABC (vía aérea, respiración, circulación)",
            "  - Oximetría de pulso continua",
            "  - Rx tórax urgente",
            "  - ECG",
        ],
        differential_diagnosis=[
            "Según etiología subyacente:",
            "- Causas pulmonares (neumonía, EPOC, asma, SDRA)",
            "- Causas cardiovasculares (IC, TEP)",
            "- Causas neurológicas (ACV, intoxicaciones)",
            "- Causas neuromusculares (Guillain-Barré, miastenia)",
            "- Causas de vía aérea (obstrucción, angioedema)",
        ],
        treatment_protocol=[
            "SOPORTE INICIAL (ABCDE):",
            "  - Asegurar vía aérea permeable",
            "  - Oxígeno suplementario inmediato",
            "  - Monitorización continua",
            "",
            "OXIGENOTERAPIA:",
            "  - Cánula nasal: 1-6 L/min (FiO2 24-44%)",
            "  - Mascarilla simple: 6-10 L/min (FiO2 40-60%)",
            "  - Mascarilla con reservorio: 10-15 L/min (FiO2 60-95%)",
            "  - Cánula nasal de alto flujo: hasta 60 L/min, FiO2 ajustable",
            "  - Meta: SatO2 ≥90% (88-92% en EPOC retenedores)",
            "",
            "VENTILACIÓN NO INVASIVA (VNI):",
            "  - Indicada en: EPOC exacerbado, edema pulmonar, inmunosuprimidos",
            "  - CPAP o BiPAP",
            "",
            "VENTILACIÓN MECÁNICA INVASIVA:",
            "  - Si falla VNI, deterioro, incapacidad de proteger vía aérea",
            "  - Estrategia protectora: Vt 6 mL/kg peso ideal, P plateau <30 cmH2O",
            "  - PEEP según FiO2 (tablas ARDS Network)",
            "",
            "TRATAMIENTO ESPECÍFICO SEGÚN CAUSA:",
            "  - Broncodilatadores (EPOC, asma)",
            "  - Antibióticos (neumonía)",
            "  - Diuréticos (edema pulmonar)",
            "  - Anticoagulación (TEP)",
            "  - Corticoides (EPOC, asma, algunas causas de SDRA)",
        ],
        emergency_signs=[
            "TODO paciente con insuficiencia respiratoria es urgencia médica",
            "Signos de gravedad extrema:",
            "  - Cianosis central",
            "  - Alteración profunda del nivel de conciencia",
            "  - Bradicardia (signo pre-paro)",
            "  - Respiración agónica o gasping",
            "  - Paro respiratorio inminente",
            "  - Hipotensión",
        ],
        prognosis="Variable según etiología. SDRA: mortalidad 35-45%. EPOC exacerbado con VNI: buen pronóstico. Sin tratamiento: fatal.",
        follow_up=[
            "UCI hasta estabilización",
            "Weaning de ventilación mecánica según protocolos",
            "Rehabilitación respiratoria post-alta",
            "Control de causa subyacente",
            "Oxigenoterapia domiciliaria si indicada",
            "Seguimiento en 1-2 semanas post-alta",
        ],
    ),
    # =========================================================================
    # BRONQUITIS AGUDA (J20)
    # Fuente: ACCP Guidelines, Cochrane Reviews
    # =========================================================================
    "J20": MedicalCondition(
        icd10_code="J20",
        name="Bronquitis Aguda",
        category="Respiratorio",
        description="Inflamación aguda del árbol traqueobronquial, generalmente de etiología viral, caracterizada por tos que persiste más de 5 días",
        symptoms=[
            "Tos (síntoma predominante)",
            "  - Inicialmente seca, luego productiva",
            "  - Duración típica 10-20 días (puede durar hasta 3-4 semanas)",
            "Expectoración (puede ser clara, mucoide o purulenta)",
            "  - El color purulento NO indica infección bacteriana",
            "Dolor torácico o malestar por la tos",
            "Fatiga",
            "Febrícula (fiebre alta es rara)",
            "Síntomas de IRA concomitantes (rinorrea, odinofagia)",
            "Sibilancias transitorias",
            "Disnea leve",
        ],
        risk_factors=[
            "Tabaquismo (activo o pasivo)",
            "Exposición a irritantes ambientales",
            "Infección de vía aérea superior previa",
            "Reflujo gastroesofágico",
            "Asma o hiperreactividad bronquial",
            "Inmunosupresión",
            "Estación fría",
        ],
        complications=[
            "Tos prolongada (>3 semanas)",
            "Neumonía (poco frecuente)",
            "Exacerbación de asma o EPOC",
            "Sinusitis secundaria",
        ],
        diagnostic_criteria=[
            "DIAGNÓSTICO CLÍNICO:",
            "  - Tos aguda de >5 días duración",
            "  - Sin evidencia de neumonía (sin fiebre alta, sin disnea severa, sin crepitantes focales)",
            "  - No requiere estudios de rutina",
            "",
            "CUANDO REALIZAR Rx TÓRAX (descartar neumonía):",
            "  - Fiebre >38°C persistente",
            "  - FC >100/min o FR >24/min",
            "  - Estertores crepitantes focales",
            "  - SatO2 <94%",
            "  - Ancianos o inmunocomprometidos con síntomas severos",
            "",
            "DIAGNÓSTICO DIFERENCIAL CON OTRAS CAUSAS DE TOS:",
            "  - Si tos >3 semanas: considerar asma, ERGE, goteo post-nasal",
            "  - Procalcitonina puede ayudar a diferenciar viral vs bacteriano",
        ],
        differential_diagnosis=[
            "Neumonía",
            "Asma (especialmente tos variante asma)",
            "EPOC exacerbado",
            "Tos post-infecciosa",
            "Tos por IECA",
            "Reflujo gastroesofágico",
            "Goteo post-nasal",
            "Tuberculosis",
            "Tos ferina",
        ],
        treatment_protocol=[
            "ANTIBIÓTICOS NO INDICADOS DE RUTINA",
            "  - >90% son virales",
            "  - Antibióticos NO reducen duración ni severidad",
            "  - Contribuyen a resistencia bacteriana",
            "",
            "TRATAMIENTO SINTOMÁTICO:",
            "  - Hidratación adecuada",
            "  - Analgésicos/antipiréticos: Paracetamol o Ibuprofeno",
            "  - Miel para la tos (efectiva, >1 año edad)",
            "  - Dextrometorfano o Codeína (si tos muy disruptiva)",
            "  - Broncodilatadores inhalados (si sibilancias): Salbutamol",
            "",
            "CONSIDERAR ANTIBIÓTICOS SOLO EN:",
            "  - Sospecha de infección por Bordetella pertussis:",
            "    Azitromicina 500mg día 1, luego 250mg días 2-5",
            "  - Pacientes ancianos con comorbilidades severas",
            "  - Inmunocomprometidos",
            "",
            "EDUCACIÓN:",
            "  - Tos puede durar 2-3 semanas (es normal)",
            "  - Expectoración purulenta NO significa infección bacteriana",
        ],
        emergency_signs=[
            "Disnea significativa",
            "SatO2 <92%",
            "Fiebre alta persistente (>38.5°C por >3 días)",
            "Hemoptisis significativa",
            "Dolor torácico pleurítico",
            "Deterioro del estado general",
        ],
        prognosis="Excelente. Autolimitada, resolución en 2-3 semanas. La tos puede persistir más tiempo en fumadores.",
        follow_up=[
            "No requiere seguimiento de rutina",
            "Reconsultar si:",
            "  - Tos persiste >4 semanas",
            "  - Aparecen signos de alarma",
            "  - Fiebre alta >3 días",
            "  - Hemoptisis",
            "Consejería antitabáquica si fumador",
        ],
    ),
    # =========================================================================
    # DERRAME PLEURAL (J90)
    # Fuente: BTS Guidelines Pleural Disease 2023
    # =========================================================================
    "J90": MedicalCondition(
        icd10_code="J90",
        name="Derrame Pleural",
        category="Respiratorio",
        description="Acumulación anormal de líquido en el espacio pleural, pudiendo ser trasudado (falla cardíaca, cirrosis) o exudado (infecciones, neoplasias, inflamación)",
        symptoms=[
            "Disnea (proporcional al tamaño del derrame)",
            "Dolor torácico pleurítico (más en exudados)",
            "Tos seca",
            "Disminución de murmullo vesicular en base afectada",
            "Matidez a la percusión",
            "Disminución de frémito táctil",
            "Egobroncofonía en límite superior del derrame",
            "Síntomas de la enfermedad subyacente:",
            "  - Edemas, ortopnea (IC)",
            "  - Fiebre, expectoración (neumonía)",
            "  - Pérdida de peso (malignidad)",
        ],
        risk_factors=[
            "TRASUDADOS (más comunes):",
            "  - Insuficiencia cardíaca",
            "  - Cirrosis hepática",
            "  - Síndrome nefrótico",
            "  - Hipoalbuminemia",
            "EXUDADOS:",
            "  - Neumonía bacteriana (derrame paraneumónico)",
            "  - Tuberculosis",
            "  - Neoplasias (pulmonar, mama, linfoma)",
            "  - Embolia pulmonar",
            "  - Enfermedades autoinmunes (AR, LES)",
            "  - Pancreatitis aguda",
        ],
        complications=[
            "Empiema (infección del espacio pleural)",
            "Derrame loculado",
            "Atrapamiento pulmonar",
            "Insuficiencia respiratoria",
            "Neumotórax post-toracocentesis",
            "Hemotórax",
        ],
        diagnostic_criteria=[
            "IMAGEN:",
            "  - Rx tórax PA y lateral: borramiento seno costofrénico",
            "    (visible con >200-300 mL de líquido)",
            "  - Ecografía torácica: más sensible, guía toracocentesis",
            "  - TAC: caracteriza derrame, detecta lesiones asociadas",
            "",
            "TORACOCENTESIS DIAGNÓSTICA:",
            "  - Indicada si: causa desconocida, sospecha de exudado",
            "  - No necesaria si: IC conocida con derrame bilateral pequeño",
            "",
            "CRITERIOS DE LIGHT (exudado si ≥1):",
            "  - Proteínas líquido/suero >0.5",
            "  - LDH líquido/suero >0.6",
            "  - LDH líquido >2/3 del límite superior normal sérico",
            "",
            "ANÁLISIS DEL LÍQUIDO PLEURAL:",
            "  - Aspecto, pH, glucosa, LDH, proteínas",
            "  - Citología, Gram, cultivo",
            "  - ADA (adenosin deaminasa) si sospecha TB",
            "  - Amilasa si sospecha pancreatitis/rotura esofágica",
        ],
        differential_diagnosis=[
            "Consolidación pulmonar (neumonía)",
            "Atelectasia",
            "Elevación diafragmática",
            "Masa pulmonar periférica",
            "Hemotórax",
            "Quilotórax",
        ],
        treatment_protocol=[
            "TRATAMIENTO DE LA CAUSA SUBYACENTE:",
            "  - IC: diuréticos, optimización de tratamiento cardíaco",
            "  - Cirrosis: restricción de sodio, diuréticos",
            "  - Infecciones: antibióticos apropiados",
            "",
            "TORACOCENTESIS TERAPÉUTICA:",
            "  - Indicada si: derrame grande sintomático",
            "  - Máximo 1-1.5L en una sesión (evitar edema de reexpansión)",
            "",
            "DERRAME PARANEUMÓNICO COMPLICADO/EMPIEMA:",
            "  - pH <7.2, glucosa <60, LDH >1000, pus o bacterias",
            "  - Requiere drenaje con tubo de tórax",
            "  - Fibrinolíticos intrapleurales (alteplasa + DNasa)",
            "  - Cirugía (VATS) si falla drenaje",
            "",
            "DERRAME MALIGNO:",
            "  - Toracocentesis evacuadora repetida",
            "  - Pleurodesis química (talco) si recurrente",
            "  - Catéter pleural tunelizado",
            "",
            "DERRAME TUBERCULOSO:",
            "  - Tratamiento antituberculoso estándar",
            "  - Generalmente no requiere drenaje",
        ],
        emergency_signs=[
            "Derrame masivo con insuficiencia respiratoria",
            "Sospecha de hemotórax",
            "Empiema con sepsis",
            "Neumotórax a tensión post-procedimiento",
            "Derrame que crece rápidamente",
        ],
        prognosis="Depende de la etiología. Derrames benignos: buen pronóstico. Derrame maligno: pronóstico reservado (mediana supervivencia 4-6 meses).",
        follow_up=[
            "Rx tórax de control post-toracocentesis",
            "Seguimiento según etiología",
            "Control de líquido pleural en derrames recurrentes",
            "Evaluación oncológica si derrame maligno",
            "Control de enfermedad de base",
        ],
    ),
    # =========================================================================
    # NEUMOTÓRAX (J93)
    # Fuente: BTS Guidelines Spontaneous Pneumothorax, ACCP
    # =========================================================================
    "J93": MedicalCondition(
        icd10_code="J93",
        name="Neumotórax",
        category="Respiratorio",
        description="Presencia de aire en el espacio pleural que causa colapso pulmonar parcial o total. Puede ser espontáneo (primario o secundario) o traumático",
        symptoms=[
            "Dolor torácico pleurítico súbito (90%)",
            "  - Unilateral, ipsilateral",
            "  - Puede irradiar a hombro o espalda",
            "Disnea de inicio agudo",
            "Tos seca",
            "Ansiedad",
            "A la exploración:",
            "  - Disminución de murmullo vesicular",
            "  - Timpanismo a la percusión",
            "  - Disminución de frémito táctil",
            "  - Desviación traqueal (si a tensión)",
            "Puede ser asintomático (neumotórax pequeño)",
        ],
        risk_factors=[
            "NEUMOTÓRAX ESPONTÁNEO PRIMARIO:",
            "  - Varones jóvenes altos y delgados",
            "  - Tabaquismo (aumenta riesgo 20x)",
            "  - Antecedente personal o familiar",
            "  - Cambios de presión atmosférica",
            "NEUMOTÓRAX ESPONTÁNEO SECUNDARIO:",
            "  - EPOC (más frecuente)",
            "  - Fibrosis quística",
            "  - Asma severa",
            "  - Fibrosis pulmonar",
            "  - Neumonía (P. jirovecii en VIH)",
            "  - Neoplasia pulmonar",
            "  - Conectivopatías (Marfan, Ehlers-Danlos)",
            "TRAUMÁTICO/IATROGÉNICO:",
            "  - Trauma torácico penetrante o cerrado",
            "  - Toracocentesis, biopsia pulmonar, catéter central",
            "  - Ventilación mecánica",
        ],
        complications=[
            "Neumotórax a tensión (emergencia vital)",
            "Neumotórax recurrente (30-50% sin tratamiento)",
            "Hemoneumotórax",
            "Pioneumotórax (infección)",
            "Insuficiencia respiratoria",
            "Paro cardiorrespiratorio (si tensión)",
        ],
        diagnostic_criteria=[
            "Rx TÓRAX (diagnóstico inicial):",
            "  - Línea de pleura visceral visible",
            "  - Ausencia de marcas pulmonares lateralmente",
            "  - Mejor visible en espiración",
            "",
            "TAMAÑO (según BTS):",
            "  - Pequeño: <2cm entre pulmón y pared torácica a nivel hiliar",
            "  - Grande: ≥2cm",
            "",
            "TAC (no rutinario):",
            "  - Dudas diagnósticas",
            "  - Evaluar enfermedad pulmonar subyacente",
            "  - Búsqueda de bullas",
            "",
            "ECOGRAFÍA POINT-OF-CARE:",
            "  - Ausencia de deslizamiento pulmonar",
            "  - Punto pulmonar (muy específico)",
            "  - Útil en trauma y UCI",
            "",
            "NEUMOTÓRAX A TENSIÓN (diagnóstico clínico):",
            "  - NO esperar Rx si sospecha alta",
            "  - Disnea severa, hipotensión, taquicardia",
            "  - Ingurgitación yugular, desviación traqueal",
            "  - Descompresión inmediata",
        ],
        differential_diagnosis=[
            "Neumonía",
            "Derrame pleural",
            "Costocondritis",
            "Embolia pulmonar",
            "Síndrome coronario agudo",
            "Herpes zóster (fase pre-eruptiva)",
            "Rotura esofágica",
        ],
        treatment_protocol=[
            "NEUMOTÓRAX A TENSIÓN (emergencia):",
            "  - Descompresión con aguja (2do espacio intercostal, línea medioclavicular)",
            "  - Seguido de tubo de tórax",
            "",
            "NEUMOTÓRAX ESPONTÁNEO PRIMARIO:",
            "  - Pequeño + asintomático: observación, oxígeno",
            "  - Pequeño + sintomático: aspiración simple",
            "  - Grande o falla aspiración: tubo de tórax (calibre pequeño 8-14F)",
            "",
            "NEUMOTÓRAX ESPONTÁNEO SECUNDARIO:",
            "  - Todos >50 años o con EPOC: tubo de tórax",
            "  - Pequeño <1cm + mínimos síntomas: observación hospitalaria",
            "  - Mayor morbilidad, umbral bajo para intervención",
            "",
            "PREVENCIÓN DE RECURRENCIA:",
            "  - Cesación tabáquica (reduce recurrencia 40%)",
            "  - Pleurodesis química o quirúrgica (VATS) si:",
            "    - Segundo episodio ipsilateral",
            "    - Primer episodio contralateral",
            "    - Neumotórax bilateral",
            "    - Fuga aérea persistente >5 días",
            "    - Profesiones de riesgo (buceadores, pilotos)",
            "",
            "RETORNO A ACTIVIDADES:",
            "  - Evitar buceo de por vida (riesgo vital)",
            "  - Vuelos comerciales: esperar 1-2 semanas post-resolución",
        ],
        emergency_signs=[
            "NEUMOTÓRAX A TENSIÓN:",
            "  - Disnea severa progresiva",
            "  - Hipotensión",
            "  - Taquicardia severa",
            "  - Desviación traqueal contralateral",
            "  - Ingurgitación yugular",
            "  - Cianosis",
            "  - Disminución del nivel de conciencia",
            "  - Actividad eléctrica sin pulso",
        ],
        prognosis="NSP: excelente pero recurrencia 30-50% sin pleurodesis. NSS: depende de enfermedad subyacente. Tensión: fatal sin tratamiento inmediato.",
        follow_up=[
            "Rx tórax de control a las 24-48h si observación",
            "Rx tórax pre-alta y 2-4 semanas post-alta",
            "Cesación tabáquica",
            "Evitar buceo permanentemente",
            "Evitar vuelos por 1-2 semanas post-resolución",
            "Referir a cirugía torácica si recurrencia o indicación de pleurodesis",
        ],
    ),
}


def get_all_respiratory_conditions():
    """Retorna todas las condiciones respiratorias"""
    return RESPIRATORY_CONDITIONS


def get_condition(icd10_code: str):
    """Obtiene una condición específica por código ICD-10"""
    return RESPIRATORY_CONDITIONS.get(icd10_code)
