#!/usr/bin/env python3
"""
🚨 Condiciones de Emergencia - Base de Conocimiento Expandida
Basado en: ATLS, AHA/ACLS Guidelines, PHTLS, Toxicology Guidelines

Cobertura:
- Paro Cardiorrespiratorio (I46.9) ✓ nuevo
- Anafilaxia (T78.2) ✓ nuevo
- Cetoacidosis Diabética (E10.1/E11.1) ✓ nuevo
- Estado Hiperosmolar Hiperglucémico (E11.0) ✓ nuevo
- Crisis Hipertensiva (I16) ✓ nuevo
- Estatus Epiléptico (G41) ✓ nuevo
- Politraumatismo (T07) ✓ nuevo
- Intoxicación Aguda (T36-T65) ✓ nuevo
"""

from dataclasses import dataclass


@dataclass
class MedicalCondition:
    """Condición médica completa"""

    icd10_code: str
    name: str
    category: str
    description: str
    symptoms: list
    risk_factors: list
    complications: list
    diagnostic_criteria: list
    differential_diagnosis: list
    treatment_protocol: list
    emergency_signs: list
    prognosis: str
    follow_up: list


EMERGENCY_CONDITIONS = {
    # =========================================================================
    # PARO CARDIORRESPIRATORIO (I46.9)
    # Fuente: AHA ACLS Guidelines 2020, ERC Guidelines 2021
    # =========================================================================
    "I46.9": MedicalCondition(
        icd10_code="I46.9",
        name="Paro Cardiorrespiratorio",
        category="Emergencias",
        description="Cese súbito de la actividad mecánica cardíaca efectiva con ausencia de pulso, respiración y conciencia. Requiere intervención inmediata con RCP y desfibrilación para supervivencia",
        symptoms=[
            "RECONOCIMIENTO (en segundos):",
            "  - Pérdida de conciencia súbita",
            "  - Ausencia de pulso (carotídeo en adultos)",
            "  - Ausencia de respiración normal (gasping no cuenta)",
            "",
            "SIGNOS ASOCIADOS:",
            "  - Colapso súbito",
            "  - Cianosis",
            "  - Midriasis (tardío)",
            "  - Palidez extrema",
            "  - Convulsiones (hipoxia cerebral)",
        ],
        risk_factors=[
            "CAUSAS REVERSIBLES (5H y 5T):",
            "  H - Hipoxia",
            "  H - Hipovolemia",
            "  H - Hidrogeniones (acidosis)",
            "  H - Hipopotasemia/Hiperpotasemia",
            "  H - Hipotermia",
            "  T - Tensión (neumotórax a tensión)",
            "  T - Taponamiento cardíaco",
            "  T - Tóxicos/tabletas",
            "  T - Trombosis pulmonar (TEP)",
            "  T - Trombosis coronaria (IAM)",
            "",
            "FACTORES DE RIESGO:",
            "  - Cardiopatía isquémica (más frecuente)",
            "  - Miocardiopatías",
            "  - Canalopatías (QT largo, Brugada)",
            "  - Arritmias previas",
            "  - Insuficiencia cardíaca",
            "  - Electrolitos anormales",
        ],
        complications=[
            "Daño cerebral hipóxico-isquémico",
            "Muerte",
            "Síndrome post-paro cardíaco",
            "Falla multiorgánica",
            "Fracturas costales (por RCP)",
            "Aspiración",
            "Estado vegetativo persistente",
        ],
        diagnostic_criteria=[
            "DIAGNÓSTICO INMEDIATO (clínico):",
            "  - Inconsciencia (no responde a estímulos)",
            "  - Sin respiración normal (verificar <10 segundos)",
            "  - Sin pulso (verificar <10 segundos)",
            "",
            "RITMOS DE PARO:",
            "  Desfibrilables (mejor pronóstico):",
            "    - Fibrilación ventricular (FV)",
            "    - Taquicardia ventricular sin pulso (TVSP)",
            "  No desfibrilables:",
            "    - Asistolia",
            "    - Actividad eléctrica sin pulso (AESP)",
            "",
            "MONITORIZACIÓN:",
            "  - ECG continuo (identificar ritmo)",
            "  - Capnografía (ETCO2) - confirma correcta RCP y ROSC",
            "  - Oximetría",
        ],
        differential_diagnosis=[
            "Síncope (recupera espontáneamente)",
            "Convulsión",
            "Sobredosis con depresión respiratoria",
            "Hipoglucemia severa",
            "Hipotermia severa",
            "Estado catatónico",
        ],
        treatment_protocol=[
            "SECUENCIA BLS/ACLS:",
            "",
            "1. RECONOCER Y ACTIVAR:",
            "   - Verificar seguridad de la escena",
            "   - Comprobar respuesta",
            "   - Llamar a emergencias y pedir DEA",
            "",
            "2. RCP DE ALTA CALIDAD (C-A-B):",
            "   Compresiones:",
            "     - 100-120 por minuto",
            "     - Profundidad 5-6 cm en adultos",
            "     - Permitir reexpansión completa",
            "     - Minimizar interrupciones (<10 seg)",
            "   Vía aérea: extensión de cabeza - elevación de mentón",
            "   Ventilaciones: 2 ventilaciones cada 30 compresiones (30:2)",
            "     - Con vía aérea avanzada: 1 ventilación cada 6 seg",
            "",
            "3. DESFIBRILACIÓN (ritmos desfibrilables):",
            "   - FV/TVSP: Descarga inmediata (bifásico 200J)",
            "   - RCP 2 minutos, reevaluar ritmo",
            "   - Repetir ciclo: RCP → análisis → descarga (si indicado)",
            "",
            "4. MEDICAMENTOS ACLS:",
            "   FV/TVSP:",
            "     - Epinefrina 1mg IV/IO cada 3-5 min (después de 2da descarga)",
            "     - Amiodarona 300mg IV bolo (después de 3ra descarga),",
            "       luego 150mg (puede repetir)",
            "     - Lidocaína alternativa: 1-1.5 mg/kg",
            "   Asistolia/AESP:",
            "     - Epinefrina 1mg IV/IO cada 3-5 min (inmediatamente)",
            "     - Buscar causas reversibles (5H 5T)",
            "",
            "5. VÍA AÉREA AVANZADA:",
            "   - Intubación orotraqueal o dispositivo supraglótico",
            "   - No interrumpir compresiones >10 seg",
            "   - Confirmar con capnografía",
            "",
            "6. POST-PARO (tras ROSC):",
            "   - Optimizar oxigenación (SatO2 92-98%)",
            "   - Evitar hiperventilación (ETCO2 35-45)",
            "   - Control de temperatura dirigido (32-36°C x 24h)",
            "   - Coronariografía si sospecha de IAM",
            "   - Control de glucemia, convulsiones",
        ],
        emergency_signs=[
            "TODO paro cardíaco es la máxima emergencia",
            "El tiempo es crítico:",
            "  - Por cada minuto sin RCP: -10% supervivencia",
            "  - Daño cerebral comienza a los 4-6 minutos",
            "  - Desfibrilación temprana aumenta supervivencia",
        ],
        prognosis="Supervivencia al alta hospitalaria: 10-12% (extrahospitalario), 25% (intrahospitalario). FV/TV mejor pronóstico que asistolia. Pronóstico neurológico: variable.",
        follow_up=[
            "UCI post-paro cardíaco",
            "Neuropronóstico a las 72h post-normotermia",
            "Evaluación cardiológica (eco, coronariografía, estudio electrofisiológico)",
            "Considerar DAI si causa cardíaca primaria",
            "Rehabilitación neurológica y cardíaca",
            "Evaluación genética si canalopatía",
        ],
    ),
    # =========================================================================
    # ANAFILAXIA (T78.2)
    # Fuente: WAO Guidelines 2020, EAACI Guidelines, ACEP
    # =========================================================================
    "T78.2": MedicalCondition(
        icd10_code="T78.2",
        name="Anafilaxia",
        category="Emergencias",
        description="Reacción alérgica sistémica grave, de inicio rápido, potencialmente mortal, mediada principalmente por IgE, que afecta múltiples sistemas orgánicos",
        symptoms=[
            "CUTÁNEOS (80-90%):",
            "  - Urticaria (habones)",
            "  - Angioedema (cara, labios, lengua)",
            "  - Prurito generalizado",
            "  - Eritema difuso",
            "  - Sensación de calor",
            "",
            "RESPIRATORIOS (70%):",
            "  - Disnea, sibilancias",
            "  - Estridor (edema laríngeo)",
            "  - Tos",
            "  - Rinorrea, congestión nasal",
            "  - Sensación de opresión torácica",
            "  - Disfonía",
            "",
            "CARDIOVASCULARES (45%):",
            "  - Hipotensión (shock)",
            "  - Taquicardia",
            "  - Síncope, mareo",
            "  - Dolor torácico",
            "",
            "GASTROINTESTINALES (45%):",
            "  - Náuseas, vómitos",
            "  - Dolor abdominal cólico",
            "  - Diarrea",
            "",
            "NEUROLÓGICOS:",
            "  - Ansiedad, sensación de muerte inminente",
            "  - Confusión",
            "  - Pérdida de conciencia",
        ],
        risk_factors=[
            "ALÉRGENOS COMUNES:",
            "  - Alimentos: maní, frutos secos, mariscos, huevo, leche",
            "  - Medicamentos: penicilinas, AINEs, medios de contraste",
            "  - Venenos: abejas, avispas, hormigas",
            "  - Látex",
            "  - Ejercicio (anafilaxia inducida por ejercicio)",
            "",
            "FACTORES QUE AUMENTAN RIESGO/SEVERIDAD:",
            "  - Antecedente de anafilaxia previa",
            "  - Asma mal controlado",
            "  - Mastocitosis",
            "  - Beta-bloqueadores (dificultan tratamiento)",
            "  - IECA",
            "  - Alcohol, ejercicio, estrés",
            "  - Edad avanzada",
        ],
        complications=[
            "Shock anafiláctico",
            "Paro cardiorrespiratorio",
            "Obstrucción de vía aérea",
            "Broncoespasmo severo",
            "Hipoxia cerebral",
            "Anafilaxia bifásica (recurrencia 1-23%)",
            "Muerte",
        ],
        diagnostic_criteria=[
            "DIAGNÓSTICO CLÍNICO (criterios):",
            "Anafilaxia es ALTAMENTE PROBABLE si CUALQUIERA de:",
            "",
            "1. Inicio agudo (minutos a horas) con afectación de PIEL/MUCOSAS",
            "   + al menos UNO de:",
            "   a) Compromiso respiratorio (disnea, sibilancias, estridor)",
            "   b) Hipotensión o síntomas de disfunción de órgano",
            "",
            "2. Exposición a alérgeno PROBABLE + ≥2 de los siguientes:",
            "   a) Afectación cutáneo-mucosa",
            "   b) Compromiso respiratorio",
            "   c) Hipotensión o síntomas asociados",
            "   d) Síntomas GI persistentes",
            "",
            "3. Hipotensión tras exposición a alérgeno CONOCIDO:",
            "   - Adultos: PAS <90 mmHg o caída >30% de basal",
            "",
            "LABORATORIO (no necesario para diagnóstico inmediato):",
            "  - Triptasa sérica (elevada 15 min - 3h post-inicio)",
            "    Útil para confirmar, especialmente si atípica",
        ],
        differential_diagnosis=[
            "Reacción vasovagal (sin urticaria, bradicardia)",
            "Ataque de pánico/ansiedad",
            "Urticaria aguda aislada",
            "Angioedema hereditario",
            "Asma aguda",
            "Crisis carcinoide",
            "Feocromocitoma",
            "Síndrome del hombre rojo (vancomicina)",
            "Escombroidosis (intoxicación por histamina)",
        ],
        treatment_protocol=[
            "¡EPINEFRINA ES EL TRATAMIENTO DE PRIMERA LÍNEA!",
            "No hay contraindicación absoluta para epinefrina en anafilaxia",
            "",
            "1. EPINEFRINA IM (muslo anterolateral):",
            "   - Adultos: 0.3-0.5 mg (0.3-0.5 mL de 1:1000)",
            "   - Niños: 0.01 mg/kg (máx 0.3 mg)",
            "   - Repetir cada 5-15 minutos si no respuesta",
            "   - Autoinyectores: 0.15 mg (<25 kg), 0.30 mg (>25 kg)",
            "",
            "2. POSICIÓN Y VÍA AÉREA:",
            "   - Posición supina con piernas elevadas (shock)",
            "   - Sentado si predomina disnea",
            "   - Oxígeno alto flujo",
            "   - Preparar intubación si compromiso de vía aérea",
            "",
            "3. FLUIDOTERAPIA (si hipotensión):",
            "   - Bolo de cristaloides 20 mL/kg",
            "   - Repetir según respuesta",
            "",
            "4. TRATAMIENTOS ADYUVANTES (segunda línea):",
            "   - Antihistamínicos H1: Difenhidramina 25-50 mg IV",
            "   - Antihistamínicos H2: Ranitidina 50 mg IV (opcional)",
            "   - Corticoides: Metilprednisolona 1-2 mg/kg IV",
            "     (previenen bifásica, no efecto inmediato)",
            "   - Beta-agonistas: Salbutamol nebulizado si broncoespasmo",
            "",
            "5. SHOCK REFRACTARIO:",
            "   - Epinefrina IV: 0.1-0.5 mg lento o infusión",
            "   - Vasopresores (norepinefrina)",
            "   - Glucagón si beta-bloqueado: 1-5 mg IV",
            "",
            "6. OBSERVACIÓN:",
            "   - Mínimo 4-6 horas post-resolución",
            "   - 24 horas si: severa, bifásica previa, acceso limitado a atención",
        ],
        emergency_signs=[
            "TODA anafilaxia es emergencia",
            "Signos de gravedad:",
            "  - Edema de vía aérea (estridor, disfonía, dificultad para tragar)",
            "  - Hipotensión/shock",
            "  - Disnea severa/cianosis",
            "  - Pérdida de conciencia",
            "  - Rápida progresión de síntomas",
        ],
        prognosis="Con tratamiento inmediato: excelente. Mortalidad <1% si epinefrina temprana. Riesgo de recurrencia bifásica: 1-23% (horas después).",
        follow_up=[
            "Prescribir autoinyector de epinefrina (mínimo 2)",
            "Plan de acción escrito para anafilaxia",
            "Referir a alergología para evaluación",
            "Pruebas de alergia (4-6 semanas después del episodio)",
            "Bracelet de alerta médica",
            "Educación sobre evitar alérgeno",
            "Considerar inmunoterapia si indicada (veneno de himenópteros)",
        ],
    ),
    # =========================================================================
    # CETOACIDOSIS DIABÉTICA (E11.1)
    # Fuente: ADA Guidelines 2024, JBDS Guidelines
    # =========================================================================
    "E11.1": MedicalCondition(
        icd10_code="E11.1",
        name="Cetoacidosis Diabética (CAD)",
        category="Emergencias",
        description="Complicación aguda de la diabetes caracterizada por hiperglucemia, acidosis metabólica con anión gap elevado y cetonemia, debido a deficiencia absoluta o relativa de insulina",
        symptoms=[
            "SÍNTOMAS PROGRESIVOS (horas a días):",
            "  - Poliuria, polidipsia (síntomas de hiperglucemia)",
            "  - Náuseas y vómitos",
            "  - Dolor abdominal (puede simular abdomen agudo)",
            "  - Debilidad, fatiga",
            "  - Alteración del nivel de conciencia",
            "",
            "SIGNOS:",
            "  - Deshidratación (mucosas secas, turgencia reducida)",
            "  - Respiración de Kussmaul (profunda y rápida)",
            "  - Aliento cetónico (olor a frutas/acetona)",
            "  - Taquicardia",
            "  - Hipotensión (deshidratación severa)",
            "  - Hipotermia",
            "  - Abdomen tenso (íleo)",
        ],
        risk_factors=[
            "DESENCADENANTES (5 I):",
            "  - Infección (30-40%, más común)",
            "  - Incumplimiento de insulina (20-40%)",
            "  - Inicio/debut de diabetes tipo 1",
            "  - Infarto (IAM, ACV)",
            "  - Intoxicación, Iatrogenia (corticoides, iSGLT2)",
            "",
            "OTROS:",
            "  - Cirugía, trauma",
            "  - Embarazo",
            "  - Pancreatitis",
            "  - Drogas (cocaína)",
            "  - Mal funcionamiento de bomba de insulina",
        ],
        complications=[
            "Edema cerebral (especialmente en niños)",
            "Hipopotasemia severa (arritmias)",
            "Hipoglucemia (por tratamiento)",
            "SDRA",
            "Tromboembolismo",
            "Rabdomiólisis",
            "Infecciones oportunistas (mucormicosis)",
            "Muerte (mortalidad <1% con tratamiento adecuado)",
        ],
        diagnostic_criteria=[
            "TRÍADA DIAGNÓSTICA:",
            "  1. Hiperglucemia: Glucosa >250 mg/dL (usualmente 300-800)",
            "  2. Cetonemia: Beta-hidroxibutirato >3 mmol/L o cetonuria ≥2+",
            "  3. Acidosis metabólica: pH <7.3 y/o HCO3 <18 mEq/L",
            "",
            "CLASIFICACIÓN DE SEVERIDAD:",
            "  Leve: pH 7.25-7.30, HCO3 15-18, alerta",
            "  Moderada: pH 7.00-7.24, HCO3 10-15, alerta/somnoliento",
            "  Severa: pH <7.00, HCO3 <10, estupor/coma",
            "",
            "OTROS HALLAZGOS DE LABORATORIO:",
            "  - Anión gap elevado (>12): Na - (Cl + HCO3)",
            "  - Potasio: puede estar elevado, normal o bajo",
            "    (déficit corporal total a pesar de nivel sérico)",
            "  - Leucocitosis (estrés, puede haber sin infección)",
            "  - Elevación de amilasa/lipasa (sin pancreatitis)",
            "  - Hiponatremia dilucional",
            "    Na corregido = Na medido + 1.6 x [(glucosa-100)/100]",
            "",
            "DIFERENCIA CON ESTADO HIPEROSMOLAR (EHH):",
            "  - EHH: glucosa >600, osmolaridad >320, cetosis leve, pH >7.30",
        ],
        differential_diagnosis=[
            "Estado hiperosmolar hiperglucémico",
            "Cetoacidosis alcohólica",
            "Cetoacidosis por inanición",
            "Acidosis láctica",
            "Intoxicación por metanol o etilenglicol",
            "Uremia (acidosis)",
            "Gastroenteritis con deshidratación",
        ],
        treatment_protocol=[
            "PRINCIPIOS: Fluidos, Insulina, Potasio, Buscar causa",
            "",
            "1. FLUIDOS (primero y crucial):",
            "   - Salino 0.9% 1-1.5 L en primera hora",
            "   - Luego 250-500 mL/h según hidratación y sodio",
            "   - Cambiar a salino 0.45% si Na >145 o euvolémico",
            "   - Agregar Dextrosa 5% cuando glucosa <250 mg/dL",
            "   - Déficit típico: 5-10 litros",
            "",
            "2. INSULINA (después de confirmar K >3.3):",
            "   - Regular IV en infusión continua",
            "   - Bolo: 0.1 U/kg (opcional según protocolo)",
            "   - Infusión: 0.1 U/kg/h",
            "   - Meta: reducir glucosa 50-75 mg/dL/h",
            "   - Si glucosa <250: reducir a 0.02-0.05 U/kg/h,",
            "     mantener glucosa 150-200 hasta resolver cetosis",
            "",
            "3. POTASIO (déficit universal):",
            "   - Si K <3.3: dar K antes de insulina (40 mEq/h)",
            "   - Si K 3.3-5.0: agregar 20-40 mEq/L de fluidos",
            "   - Si K >5.0: no agregar, monitorear cada 2h",
            "   - Meta: K 4-5 mEq/L",
            "",
            "4. BICARBONATO (controvertido):",
            "   - Solo si pH <6.9",
            "   - 100 mEq NaHCO3 en 400 mL en 2h",
            "   - Riesgos: hipopotasemia, alcalosis tardía",
            "",
            "5. FOSFATO:",
            "   - Considerar si <1 mg/dL y disfunción cardíaca/respiratoria",
            "",
            "6. MONITOREO:",
            "   - Glucosa horaria, electrolitos cada 2-4h",
            "   - Gases/pH cada 2-4h hasta resolución",
            "   - Balance hídrico estricto",
            "",
            "7. CRITERIOS DE RESOLUCIÓN:",
            "   - Glucosa <200 mg/dL",
            "   - pH >7.30",
            "   - HCO3 ≥18 mEq/L",
            "   - Anión gap normalizado",
            "",
            "8. TRANSICIÓN A INSULINA SC:",
            "   - Cuando tolere vía oral y CAD resuelta",
            "   - Dar insulina SC 1-2h ANTES de suspender IV",
            "   - Reiniciar esquema previo o iniciar 0.5-0.7 U/kg/día",
        ],
        emergency_signs=[
            "Toda CAD es emergencia médica",
            "Signos de mayor gravedad:",
            "  - pH <7.0",
            "  - Alteración del nivel de conciencia (coma)",
            "  - Hipotensión/shock",
            "  - Hipopotasemia severa (<2.5)",
            "  - Arritmias",
            "  - En niños: signos de edema cerebral",
        ],
        prognosis="Mortalidad <1-5% con tratamiento adecuado. Mayor mortalidad en ancianos, coma, comorbilidades. Recurrencia si no se aborda causa desencadenante.",
        follow_up=[
            "Identificar y tratar factor desencadenante",
            "Educación diabetológica intensiva",
            "Ajuste de esquema de insulina",
            "Control en 1-2 semanas post-alta",
            "Evaluación de HbA1c",
            "Reglas del día de enfermedad",
            "Monitoreo de glucosa y cetonas en casa",
        ],
    ),
    # =========================================================================
    # CRISIS HIPERTENSIVA (I16)
    # Fuente: AHA/ACC Guidelines, ESC Guidelines
    # =========================================================================
    "I16": MedicalCondition(
        icd10_code="I16",
        name="Crisis Hipertensiva",
        category="Emergencias",
        description="Elevación severa de la presión arterial (típicamente >180/120 mmHg). Se clasifica en urgencia (sin daño de órgano blanco) o emergencia (con daño de órgano blanco agudo)",
        symptoms=[
            "URGENCIA HIPERTENSIVA:",
            "  - PA severa sin síntomas o con síntomas leves",
            "  - Cefalea",
            "  - Ansiedad",
            "  - Epistaxis",
            "",
            "EMERGENCIA HIPERTENSIVA (síntomas según órgano afectado):",
            "  NEUROLÓGICO:",
            "    - Cefalea intensa",
            "    - Alteración de conciencia, confusión",
            "    - Déficit focal (ACV)",
            "    - Convulsiones (encefalopatía hipertensiva)",
            "    - Náuseas, vómitos",
            "    - Visión borrosa, papiledema",
            "  CARDIOVASCULAR:",
            "    - Dolor torácico (SCA, disección aórtica)",
            "    - Disnea (EAP)",
            "    - Dolor dorsal desgarrante (disección)",
            "  RENAL:",
            "    - Oliguria",
            "    - Hematuria",
            "  EMBARAZO:",
            "    - Preeclampsia/eclampsia",
        ],
        risk_factors=[
            "Hipertensión crónica mal controlada",
            "No adherencia a tratamiento antihipertensivo",
            "Uso de drogas (cocaína, anfetaminas)",
            "Suspensión abrupta de antihipertensivos (clonidina)",
            "Feocromocitoma",
            "Renovascular (estenosis de arteria renal)",
            "Glomerulonefritis aguda",
            "Preeclampsia/eclampsia",
            "Interacciones medicamentosas (IMAO + tiramina)",
        ],
        complications=[
            "Accidente cerebrovascular (hemorrágico o isquémico)",
            "Encefalopatía hipertensiva",
            "Síndrome coronario agudo",
            "Disección aórtica",
            "Edema agudo de pulmón",
            "Insuficiencia renal aguda",
            "Eclampsia y complicaciones fetales",
            "Hemorragia retiniana, papiledema",
            "Muerte",
        ],
        diagnostic_criteria=[
            "DEFINICIÓN:",
            "  - Crisis hipertensiva: PA >180/120 mmHg",
            "  - Urgencia: sin evidencia de daño de órgano blanco agudo",
            "  - Emergencia: CON daño de órgano blanco agudo",
            "",
            "EVALUACIÓN DE DAÑO DE ÓRGANO BLANCO:",
            "  Neurológico:",
            "    - Examen neurológico completo",
            "    - Fondo de ojo (hemorragias, exudados, papiledema)",
            "    - TAC/RM cerebral si síntomas neurológicos",
            "  Cardiovascular:",
            "    - ECG (isquemia, hipertrofia)",
            "    - Troponinas",
            "    - Rx tórax (cardiomegalia, edema pulmonar)",
            "    - Ecocardiograma (función VI, disección)",
            "    - AngioTAC si sospecha de disección",
            "  Renal:",
            "    - Creatinina, BUN",
            "    - Uroanálisis (proteinuria, hematuria)",
            "",
            "LABORATORIO BÁSICO:",
            "  - Hemograma (anemia hemolítica microangiopática)",
            "  - Electrolitos, función renal",
            "  - Uroanálisis",
            "  - Test de embarazo en mujeres en edad fértil",
        ],
        differential_diagnosis=[
            "Ansiedad/pánico con HTA reactiva",
            "Dolor con HTA secundaria",
            "Pseudocrisis (manguito inadecuado)",
            "HTA de bata blanca",
            "Hipertensión secundaria no conocida",
        ],
        treatment_protocol=[
            "PRINCIPIO: Distinguir urgencia de emergencia",
            "",
            "URGENCIA HIPERTENSIVA (sin daño de órgano):",
            "  - NO requiere reducción inmediata ni IV",
            "  - Reducir PA gradualmente en horas a días",
            "  - Antihipertensivos orales:",
            "    • Captopril 25-50 mg VO",
            "    • Amlodipino 5-10 mg VO",
            "    • Labetalol 200-400 mg VO",
            "    • Clonidina 0.1-0.2 mg VO",
            "  - Observación 2-6 horas",
            "  - Alta con ajuste de tratamiento y seguimiento",
            "",
            "EMERGENCIA HIPERTENSIVA:",
            "  - Ingreso a UCI/unidad de cuidados intermedios",
            "  - Antihipertensivos IV",
            "  - Meta: reducir PA 10-20% en primera hora",
            "           luego gradualmente en 24-48h",
            "  - Evitar reducción brusca (isquemia)",
            "",
            "AGENTES IV SEGÚN SITUACIÓN:",
            "  General:",
            "    - Labetalol IV: bolos 20mg, luego infusión 2 mg/min",
            "    - Nicardipino IV: 5-15 mg/h (ajuste cada 5-15 min)",
            "    - Nitroprusiato: 0.25-10 μg/kg/min (cuidado con toxicidad por cianuro)",
            "  ",
            "  Encefalopatía hipertensiva/ACV isquémico:",
            "    - Labetalol, Nicardipino",
            "    - Meta menos agresiva en ACV: <185/110 si trombolisis",
            "  ",
            "  Hemorragia intracerebral:",
            "    - Nicardipino, Labetalol",
            "    - Meta PAS 140-160 mmHg",
            "  ",
            "  Disección aórtica:",
            "    - Beta-bloqueador primero (Esmolol, Labetalol)",
            "    - Meta: FC <60, PAS 100-120 mmHg",
            "  ",
            "  Edema agudo de pulmón:",
            "    - Nitroglicerina IV, Furosemida",
            "    - NO beta-bloqueadores si IC descompensada",
            "  ",
            "  SCA:",
            "    - Nitroglicerina IV, Beta-bloqueador",
            "  ",
            "  Feocromocitoma:",
            "    - Fentolamina IV (alfa-bloqueador)",
            "    - NO beta-bloqueadores solos (crisis)",
            "  ",
            "  Eclampsia:",
            "    - Sulfato de magnesio + Labetalol o Hidralazina",
        ],
        emergency_signs=[
            "TODA emergencia hipertensiva requiere tratamiento inmediato",
            "Signos que indican emergencia:",
            "  - Cefalea severa con alteración de conciencia",
            "  - Déficit neurológico focal (ACV)",
            "  - Dolor torácico/dorsal severo (disección, SCA)",
            "  - Disnea severa con edema pulmonar",
            "  - Oliguria con elevación de creatinina",
            "  - Papiledema, hemorragias retinianas",
            "  - Convulsiones",
        ],
        prognosis="Emergencia hipertensiva no tratada: alta mortalidad. Con tratamiento adecuado: pronóstico depende del órgano afectado. Urgencia: excelente si se optimiza tratamiento.",
        follow_up=[
            "Control en 24-72h post-alta (urgencia)",
            "Ajuste de medicación antihipertensiva",
            "Evaluación de causas secundarias si indicado",
            "Educación sobre adherencia y síntomas de alarma",
            "MAPA (monitoreo ambulatorio) para ajuste de tratamiento",
            "Control de factores de riesgo cardiovascular",
        ],
    ),
    # =========================================================================
    # ESTATUS EPILÉPTICO (G41)
    # Fuente: ILAE Guidelines, Neurocritical Care Society
    # =========================================================================
    "G41": MedicalCondition(
        icd10_code="G41",
        name="Estatus Epiléptico",
        category="Emergencias",
        description="Crisis epiléptica que dura >5 minutos o crisis repetidas sin recuperación de conciencia entre ellas. Emergencia neurológica con riesgo de daño cerebral permanente y muerte",
        symptoms=[
            "ESTATUS EPILÉPTICO CONVULSIVO (más común):",
            "  - Movimientos tónico-clónicos generalizados",
            "  - Pérdida de conciencia",
            "  - Cianosis",
            "  - Espuma por boca",
            "  - Incontinencia",
            "  - Mordedura de lengua",
            "",
            "ESTATUS EPILÉPTICO NO CONVULSIVO:",
            "  - Alteración de conciencia prolongada",
            "  - Confusión, estupor",
            "  - Automatismos sutiles",
            "  - Movimientos oculares anormales",
            "  - Puede pasar desapercibido",
            "",
            "FASES:",
            "  - Fase inicial (<5 min): crisis prolongada",
            "  - Estatus establecido (5-30 min): refractario a primera línea",
            "  - Estatus refractario (>30 min): requiere anestésicos",
            "  - Super-refractario (>24h): continúa pese a anestesia",
        ],
        risk_factors=[
            "CAUSAS EN EPILÉPTICOS:",
            "  - No adherencia a antiepilépticos",
            "  - Cambio de medicación",
            "  - Niveles subterapéuticos",
            "  - Privación de sueño",
            "  - Alcohol",
            "",
            "CAUSAS EN NO EPILÉPTICOS:",
            "  - ACV agudo",
            "  - Infección del SNC (meningitis, encefalitis)",
            "  - Trauma craneoencefálico",
            "  - Trastornos metabólicos (hipoglucemia, hiponatremia, uremia)",
            "  - Hipoxia",
            "  - Tumores cerebrales",
            "  - Intoxicaciones (cocaína, anfetaminas)",
            "  - Abstinencia (alcohol, benzodiacepinas)",
            "  - Eclampsia",
        ],
        complications=[
            "Daño neuronal hipóxico",
            "Edema cerebral",
            "Aspiración y neumonía",
            "Rabdomiólisis",
            "Hipertermia",
            "Arritmias cardíacas",
            "Acidosis láctica",
            "Fracturas, luxaciones",
            "Déficit neurológico permanente",
            "Muerte (mortalidad 10-30%)",
        ],
        diagnostic_criteria=[
            "DEFINICIÓN OPERATIVA (ILAE 2015):",
            "  T1: tiempo a partir del cual crisis se considera 'anormalmente prolongada' = 5 min",
            "  T2: tiempo a partir del cual hay riesgo de secuelas = 30 min",
            "",
            "DIAGNÓSTICO:",
            "  - Crisis continua >5 minutos, o",
            "  - ≥2 crisis sin recuperación de conciencia entre ellas",
            "",
            "EEG (electroencefalograma):",
            "  - Útil para confirmar, especialmente en no convulsivo",
            "  - Monitoreo continuo en UCI",
            "",
            "EVALUACIÓN ETIOLÓGICA:",
            "  - Glucosa capilar (inmediato)",
            "  - Electrolitos, función renal y hepática",
            "  - Niveles de antiepilépticos",
            "  - Gases arteriales, lactato",
            "  - Tóxicos en orina/sangre",
            "  - TAC cerebral (descartar lesión estructural)",
            "  - Punción lumbar (si sospecha infección del SNC)",
            "  - RM cerebral (diferido)",
        ],
        differential_diagnosis=[
            "Crisis psicógena no epiléptica",
            "Síncope convulsivo",
            "Temblor severo",
            "Distonía aguda",
            "Rigidez de descerebración",
            "Mioclonías post-hipóxicas",
        ],
        treatment_protocol=[
            "¡TIEMPO ES CEREBRO! - Cada minuto aumenta morbimortalidad",
            "",
            "FASE INICIAL (0-5 min):",
            "  - ABC: vía aérea, oxígeno, acceso IV",
            "  - Glucosa capilar (si <60 mg/dL: Dextrosa IV + Tiamina)",
            "  - Monitorización continua",
            "  - Posición de seguridad",
            "",
            "PRIMERA LÍNEA (5-20 min) - BENZODIACEPINAS:",
            "  - Lorazepam 4 mg IV (0.1 mg/kg) - puede repetir x1",
            "  - Diazepam 10 mg IV (0.15 mg/kg) - puede repetir x1",
            "  - Midazolam 10 mg IM si no acceso IV (0.2 mg/kg)",
            "  - Diazepam rectal si no IV disponible",
            "",
            "SEGUNDA LÍNEA (20-40 min) - ANTIEPILÉPTICO IV:",
            "  Si persiste tras benzodiacepinas:",
            "  - Fenitoína 20 mg/kg IV a 50 mg/min, o",
            "  - Fosfenitoína 20 mg PE/kg a 150 mg PE/min, o",
            "  - Levetiracetam 60 mg/kg IV (máx 4500 mg), o",
            "  - Valproato 40 mg/kg IV (máx 3000 mg), o",
            "  - Lacosamida 400 mg IV",
            "  (Fenitoína/Fosfenitoína: contraindicada en Brugada, bloqueo AV)",
            "",
            "TERCERA LÍNEA (>40 min) - ESTATUS REFRACTARIO:",
            "  - Intubación y ventilación mecánica",
            "  - Anestésicos IV con monitoreo EEG continuo:",
            "    • Midazolam infusión 0.2 mg/kg bolo + 0.05-2 mg/kg/h",
            "    • Propofol 2 mg/kg bolo + 30-200 μg/kg/min",
            "    • Pentobarbital 5-15 mg/kg bolo + 0.5-5 mg/kg/h",
            "  - Meta: supresión de brotes o abolición de crisis en EEG",
            "  - Mantener 24-48h, luego destete gradual",
            "",
            "TRATAMIENTO DE CAUSA SUBYACENTE:",
            "  - Antibióticos si infección SNC",
            "  - Corregir electrolitos",
            "  - Revertir tóxicos (flumazenil, naloxona con precaución)",
        ],
        emergency_signs=[
            "TODO estatus epiléptico es emergencia máxima",
            "Signos de mayor gravedad:",
            "  - Duración >30 minutos",
            "  - Hipoxia persistente",
            "  - Hipertermia",
            "  - Acidosis severa",
            "  - Refractariedad a tratamiento",
            "  - Etiología grave (encefalitis, ACV, anoxia)",
        ],
        prognosis="Mortalidad 10-30% (mayor en refractario y super-refractario). Secuelas neurológicas en 10-20%. Mejor pronóstico en epilépticos con causa reversible.",
        follow_up=[
            "UCI hasta control y destete de sedación",
            "EEG de seguimiento",
            "Neuroimagen si no realizada",
            "Optimización de antiepilépticos crónicos",
            "Evaluación neuropsicológica post-alta",
            "Control neurológico en 2-4 semanas",
            "Restricción de conducción según normativa",
        ],
    ),
}


def get_all_emergency_conditions():
    """Retorna todas las condiciones de emergencia"""
    return EMERGENCY_CONDITIONS


def get_condition(icd10_code: str):
    """Obtiene una condición específica por código ICD-10"""
    return EMERGENCY_CONDITIONS.get(icd10_code)
